// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_calls.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateAICallsForObject = `-- name: AggregateAICallsForObject :one
select
  count(*)::bigint as call_count,
  count(*) filter (where status = 'skipped')::bigint as skipped_count,
  count(*) filter (where status in ('failed', 'partial'))::bigint as unsuccessful_count,
  coalesce(sum(prompt_tokens), 0)::bigint as prompt_tokens,
  coalesce(sum(completion_tokens), 0)::bigint as completion_tokens,
  coalesce(sum(total_tokens), 0)::bigint as total_tokens,
  coalesce(sum(cost_usd), 0)::numeric as cost_usd
from ai_call_records
where project_id = $1
  and linked_object_type = $2
  and linked_object_id = $3
`

type AggregateAICallsForObjectParams struct {
	ProjectID        uuid.UUID `json:"project_id"`
	LinkedObjectType string    `json:"linked_object_type"`
	LinkedObjectID   uuid.UUID `json:"linked_object_id"`
}

type AggregateAICallsForObjectRow struct {
	CallCount         int64          `json:"call_count"`
	SkippedCount      int64          `json:"skipped_count"`
	UnsuccessfulCount int64          `json:"unsuccessful_count"`
	PromptTokens      int64          `json:"prompt_tokens"`
	CompletionTokens  int64          `json:"completion_tokens"`
	TotalTokens       int64          `json:"total_tokens"`
	CostUsd           pgtype.Numeric `json:"cost_usd"`
}

func (q *Queries) AggregateAICallsForObject(ctx context.Context, arg AggregateAICallsForObjectParams) (AggregateAICallsForObjectRow, error) {
	row := q.db.QueryRow(ctx, aggregateAICallsForObject, arg.ProjectID, arg.LinkedObjectType, arg.LinkedObjectID)
	var i AggregateAICallsForObjectRow
	err := row.Scan(
		&i.CallCount,
		&i.SkippedCount,
		&i.UnsuccessfulCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.CostUsd,
	)
	return i, err
}

const createAICallRecord = `-- name: CreateAICallRecord :one
insert into ai_call_records
  (project_id, run_id, stage, linked_object_type, linked_object_id,
   provider, model, prompt_version, request_fingerprint, status, parent_call_id, caused_by_call_id,
   attempt_number, provider_called, provider_started_at, finished_at)
select
   $1, $2, $3,
   $4, $5,
   $6, $7, $8,
   $9, $10, $11, $12,
   coalesce((
     select parent.attempt_number + 1
     from ai_call_records parent
     where parent.id = $11
       and parent.project_id = $1
       and parent.stage = $3
       and parent.linked_object_type = $4
       and parent.linked_object_id = $5
       and parent.request_fingerprint = $9
   ), 1),
   $10 not in ('queued', 'skipped'),
   case when $10 not in ('queued', 'skipped') then now() else null end,
   case when $10 not in ('queued', 'running') then now() else null end
where $11::uuid is null or exists (
  select 1 from ai_call_records parent
  where parent.id = $11
    and parent.project_id = $1
    and parent.stage = $3
    and parent.linked_object_type = $4
    and parent.linked_object_id = $5
    and parent.request_fingerprint = $9
)
returning id, project_id, run_id, stage, linked_object_type, linked_object_id, provider, model, prompt_version, request_fingerprint, status, error_code, prompt_tokens, completion_tokens, total_tokens, cost_usd, parent_call_id, started_at, finished_at, created_at, updated_at, attempt_number, provider_called, provider_started_at, caused_by_call_id, verifier_outcome
`

type CreateAICallRecordParams struct {
	ProjectID          uuid.UUID   `json:"project_id"`
	RunID              pgtype.UUID `json:"run_id"`
	Stage              string      `json:"stage"`
	LinkedObjectType   string      `json:"linked_object_type"`
	LinkedObjectID     uuid.UUID   `json:"linked_object_id"`
	Provider           string      `json:"provider"`
	Model              string      `json:"model"`
	PromptVersion      string      `json:"prompt_version"`
	RequestFingerprint string      `json:"request_fingerprint"`
	Status             string      `json:"status"`
	ParentCallID       pgtype.UUID `json:"parent_call_id"`
	CausedByCallID     pgtype.UUID `json:"caused_by_call_id"`
}

func (q *Queries) CreateAICallRecord(ctx context.Context, arg CreateAICallRecordParams) (AiCallRecord, error) {
	row := q.db.QueryRow(ctx, createAICallRecord,
		arg.ProjectID,
		arg.RunID,
		arg.Stage,
		arg.LinkedObjectType,
		arg.LinkedObjectID,
		arg.Provider,
		arg.Model,
		arg.PromptVersion,
		arg.RequestFingerprint,
		arg.Status,
		arg.ParentCallID,
		arg.CausedByCallID,
	)
	var i AiCallRecord
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RunID,
		&i.Stage,
		&i.LinkedObjectType,
		&i.LinkedObjectID,
		&i.Provider,
		&i.Model,
		&i.PromptVersion,
		&i.RequestFingerprint,
		&i.Status,
		&i.ErrorCode,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.CostUsd,
		&i.ParentCallID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttemptNumber,
		&i.ProviderCalled,
		&i.ProviderStartedAt,
		&i.CausedByCallID,
		&i.VerifierOutcome,
	)
	return i, err
}

const createSkippedAICallRecord = `-- name: CreateSkippedAICallRecord :one
insert into ai_call_records
  (project_id, run_id, stage, linked_object_type, linked_object_id,
   provider, model, prompt_version, request_fingerprint, status, error_code,
   parent_call_id, caused_by_call_id, attempt_number, provider_called, provider_started_at, finished_at)
select
   $1, $2, $3,
   $4, $5,
   $6, $7, $8,
   $9, 'skipped', $10,
   $11, $12,
   coalesce((
     select parent.attempt_number + 1
     from ai_call_records parent
     where parent.id = $11
       and parent.project_id = $1
       and parent.stage = $3
       and parent.linked_object_type = $4
       and parent.linked_object_id = $5
       and parent.request_fingerprint = $9
   ), 1),
   false, null, now()
where $11::uuid is null or exists (
  select 1 from ai_call_records parent
  where parent.id = $11
    and parent.project_id = $1
    and parent.stage = $3
    and parent.linked_object_type = $4
    and parent.linked_object_id = $5
    and parent.request_fingerprint = $9
)
returning id, project_id, run_id, stage, linked_object_type, linked_object_id, provider, model, prompt_version, request_fingerprint, status, error_code, prompt_tokens, completion_tokens, total_tokens, cost_usd, parent_call_id, started_at, finished_at, created_at, updated_at, attempt_number, provider_called, provider_started_at, caused_by_call_id, verifier_outcome
`

type CreateSkippedAICallRecordParams struct {
	ProjectID          uuid.UUID   `json:"project_id"`
	RunID              pgtype.UUID `json:"run_id"`
	Stage              string      `json:"stage"`
	LinkedObjectType   string      `json:"linked_object_type"`
	LinkedObjectID     uuid.UUID   `json:"linked_object_id"`
	Provider           string      `json:"provider"`
	Model              string      `json:"model"`
	PromptVersion      string      `json:"prompt_version"`
	RequestFingerprint string      `json:"request_fingerprint"`
	ErrorCode          *string     `json:"error_code"`
	ParentCallID       pgtype.UUID `json:"parent_call_id"`
	CausedByCallID     pgtype.UUID `json:"caused_by_call_id"`
}

func (q *Queries) CreateSkippedAICallRecord(ctx context.Context, arg CreateSkippedAICallRecordParams) (AiCallRecord, error) {
	row := q.db.QueryRow(ctx, createSkippedAICallRecord,
		arg.ProjectID,
		arg.RunID,
		arg.Stage,
		arg.LinkedObjectType,
		arg.LinkedObjectID,
		arg.Provider,
		arg.Model,
		arg.PromptVersion,
		arg.RequestFingerprint,
		arg.ErrorCode,
		arg.ParentCallID,
		arg.CausedByCallID,
	)
	var i AiCallRecord
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RunID,
		&i.Stage,
		&i.LinkedObjectType,
		&i.LinkedObjectID,
		&i.Provider,
		&i.Model,
		&i.PromptVersion,
		&i.RequestFingerprint,
		&i.Status,
		&i.ErrorCode,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.CostUsd,
		&i.ParentCallID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttemptNumber,
		&i.ProviderCalled,
		&i.ProviderStartedAt,
		&i.CausedByCallID,
		&i.VerifierOutcome,
	)
	return i, err
}

const finishAICallRecord = `-- name: FinishAICallRecord :one
update ai_call_records set
  status = $1,
  provider = coalesce($2, provider),
  model = coalesce($3, model),
  error_code = $4,
  prompt_tokens = case when $1 = 'skipped' then 0 else $5 end,
  completion_tokens = case when $1 = 'skipped' then 0 else $6 end,
  total_tokens = case when $1 = 'skipped' then 0 else $7 end,
  cost_usd = case when $1 = 'skipped' then 0::numeric else $8::numeric end,
  provider_called = $1 <> 'skipped',
  provider_started_at = case when $1 = 'skipped' then null else coalesce(provider_started_at, started_at) end,
  finished_at = now(),
  updated_at = now()
where id = $9
  and project_id = $10
  and status = 'running'
returning id, project_id, run_id, stage, linked_object_type, linked_object_id, provider, model, prompt_version, request_fingerprint, status, error_code, prompt_tokens, completion_tokens, total_tokens, cost_usd, parent_call_id, started_at, finished_at, created_at, updated_at, attempt_number, provider_called, provider_started_at, caused_by_call_id, verifier_outcome
`

type FinishAICallRecordParams struct {
	Status           string         `json:"status"`
	ResolvedProvider *string        `json:"resolved_provider"`
	ResolvedModel    *string        `json:"resolved_model"`
	ErrorCode        *string        `json:"error_code"`
	PromptTokens     int32          `json:"prompt_tokens"`
	CompletionTokens int32          `json:"completion_tokens"`
	TotalTokens      int32          `json:"total_tokens"`
	CostUsd          pgtype.Numeric `json:"cost_usd"`
	ID               uuid.UUID      `json:"id"`
	ProjectID        uuid.UUID      `json:"project_id"`
}

func (q *Queries) FinishAICallRecord(ctx context.Context, arg FinishAICallRecordParams) (AiCallRecord, error) {
	row := q.db.QueryRow(ctx, finishAICallRecord,
		arg.Status,
		arg.ResolvedProvider,
		arg.ResolvedModel,
		arg.ErrorCode,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.CostUsd,
		arg.ID,
		arg.ProjectID,
	)
	var i AiCallRecord
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RunID,
		&i.Stage,
		&i.LinkedObjectType,
		&i.LinkedObjectID,
		&i.Provider,
		&i.Model,
		&i.PromptVersion,
		&i.RequestFingerprint,
		&i.Status,
		&i.ErrorCode,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.CostUsd,
		&i.ParentCallID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttemptNumber,
		&i.ProviderCalled,
		&i.ProviderStartedAt,
		&i.CausedByCallID,
		&i.VerifierOutcome,
	)
	return i, err
}

const finishAICallRecordIfRunning = `-- name: FinishAICallRecordIfRunning :one
update ai_call_records set
  status = 'failed', error_code = $1, finished_at = now(), updated_at = now()
where id = $2 and project_id = $3 and status = 'running'
returning id, project_id, run_id, stage, linked_object_type, linked_object_id, provider, model, prompt_version, request_fingerprint, status, error_code, prompt_tokens, completion_tokens, total_tokens, cost_usd, parent_call_id, started_at, finished_at, created_at, updated_at, attempt_number, provider_called, provider_started_at, caused_by_call_id, verifier_outcome
`

type FinishAICallRecordIfRunningParams struct {
	ErrorCode *string   `json:"error_code"`
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) FinishAICallRecordIfRunning(ctx context.Context, arg FinishAICallRecordIfRunningParams) (AiCallRecord, error) {
	row := q.db.QueryRow(ctx, finishAICallRecordIfRunning, arg.ErrorCode, arg.ID, arg.ProjectID)
	var i AiCallRecord
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RunID,
		&i.Stage,
		&i.LinkedObjectType,
		&i.LinkedObjectID,
		&i.Provider,
		&i.Model,
		&i.PromptVersion,
		&i.RequestFingerprint,
		&i.Status,
		&i.ErrorCode,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.CostUsd,
		&i.ParentCallID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttemptNumber,
		&i.ProviderCalled,
		&i.ProviderStartedAt,
		&i.CausedByCallID,
		&i.VerifierOutcome,
	)
	return i, err
}

const finishCanonicalAICallFenced = `-- name: FinishCanonicalAICallFenced :one
update ai_call_records set
  status = case when status = 'running' or (status = 'queued' and $1::text = 'skipped') then $1::text else status end,
  error_code = case when status = 'running' or (status = 'queued' and $1::text = 'skipped') then $2 else error_code end,
  provider = coalesce($3, provider),
  model = coalesce($4, model),
  prompt_tokens = case when status = 'skipped' or (status in ('queued', 'running') and $1::text = 'skipped') then 0 else $5 end,
  completion_tokens = case when status = 'skipped' or (status in ('queued', 'running') and $1::text = 'skipped') then 0 else $6 end,
  total_tokens = case when status = 'skipped' or (status in ('queued', 'running') and $1::text = 'skipped') then 0 else $7 end,
  cost_usd = case when status = 'skipped' or (status in ('queued', 'running') and $1::text = 'skipped') then 0::numeric else $8::numeric end,
  provider_called = case when status in ('queued', 'running') then $1::text <> 'skipped' else provider_called end,
  provider_started_at = case when status in ('queued', 'running') and $1::text = 'skipped' then null else provider_started_at end,
  verifier_outcome = case when stage = 'fix_grounding_verification'
    and (status in ('ok', 'partial') or (status in ('queued', 'running') and $1::text = 'skipped'))
    then coalesce(verifier_outcome, $9) else verifier_outcome end,
  finished_at = coalesce(finished_at, now()),
  updated_at = now()
where id = $10 and project_id = $11
returning id, project_id, run_id, stage, linked_object_type, linked_object_id, provider, model, prompt_version, request_fingerprint, status, error_code, prompt_tokens, completion_tokens, total_tokens, cost_usd, parent_call_id, started_at, finished_at, created_at, updated_at, attempt_number, provider_called, provider_started_at, caused_by_call_id, verifier_outcome
`

type FinishCanonicalAICallFencedParams struct {
	Status           string         `json:"status"`
	ErrorCode        *string        `json:"error_code"`
	ResolvedProvider *string        `json:"resolved_provider"`
	ResolvedModel    *string        `json:"resolved_model"`
	PromptTokens     int32          `json:"prompt_tokens"`
	CompletionTokens int32          `json:"completion_tokens"`
	TotalTokens      int32          `json:"total_tokens"`
	CostUsd          pgtype.Numeric `json:"cost_usd"`
	VerifierOutcome  []byte         `json:"verifier_outcome"`
	ID               uuid.UUID      `json:"id"`
	ProjectID        uuid.UUID      `json:"project_id"`
}

func (q *Queries) FinishCanonicalAICallFenced(ctx context.Context, arg FinishCanonicalAICallFencedParams) (AiCallRecord, error) {
	row := q.db.QueryRow(ctx, finishCanonicalAICallFenced,
		arg.Status,
		arg.ErrorCode,
		arg.ResolvedProvider,
		arg.ResolvedModel,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.CostUsd,
		arg.VerifierOutcome,
		arg.ID,
		arg.ProjectID,
	)
	var i AiCallRecord
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RunID,
		&i.Stage,
		&i.LinkedObjectType,
		&i.LinkedObjectID,
		&i.Provider,
		&i.Model,
		&i.PromptVersion,
		&i.RequestFingerprint,
		&i.Status,
		&i.ErrorCode,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.CostUsd,
		&i.ParentCallID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttemptNumber,
		&i.ProviderCalled,
		&i.ProviderStartedAt,
		&i.CausedByCallID,
		&i.VerifierOutcome,
	)
	return i, err
}

const finishQueuedAICallSkipped = `-- name: FinishQueuedAICallSkipped :one
update ai_call_records set
  status = 'skipped',
  error_code = $1,
  prompt_tokens = 0,
  completion_tokens = 0,
  total_tokens = 0,
  cost_usd = 0,
  provider_called = false,
  provider_started_at = null,
  finished_at = now(),
  updated_at = now()
where id = $2
  and project_id = $3
  and status = 'queued'
returning id, project_id, run_id, stage, linked_object_type, linked_object_id, provider, model, prompt_version, request_fingerprint, status, error_code, prompt_tokens, completion_tokens, total_tokens, cost_usd, parent_call_id, started_at, finished_at, created_at, updated_at, attempt_number, provider_called, provider_started_at, caused_by_call_id, verifier_outcome
`

type FinishQueuedAICallSkippedParams struct {
	ErrorCode *string   `json:"error_code"`
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) FinishQueuedAICallSkipped(ctx context.Context, arg FinishQueuedAICallSkippedParams) (AiCallRecord, error) {
	row := q.db.QueryRow(ctx, finishQueuedAICallSkipped, arg.ErrorCode, arg.ID, arg.ProjectID)
	var i AiCallRecord
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RunID,
		&i.Stage,
		&i.LinkedObjectType,
		&i.LinkedObjectID,
		&i.Provider,
		&i.Model,
		&i.PromptVersion,
		&i.RequestFingerprint,
		&i.Status,
		&i.ErrorCode,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.CostUsd,
		&i.ParentCallID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttemptNumber,
		&i.ProviderCalled,
		&i.ProviderStartedAt,
		&i.CausedByCallID,
		&i.VerifierOutcome,
	)
	return i, err
}

const getAICallRecord = `-- name: GetAICallRecord :one
select id, project_id, run_id, stage, linked_object_type, linked_object_id, provider, model, prompt_version, request_fingerprint, status, error_code, prompt_tokens, completion_tokens, total_tokens, cost_usd, parent_call_id, started_at, finished_at, created_at, updated_at, attempt_number, provider_called, provider_started_at, caused_by_call_id, verifier_outcome from ai_call_records where id = $1 and project_id = $2
`

type GetAICallRecordParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetAICallRecord(ctx context.Context, arg GetAICallRecordParams) (AiCallRecord, error) {
	row := q.db.QueryRow(ctx, getAICallRecord, arg.ID, arg.ProjectID)
	var i AiCallRecord
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RunID,
		&i.Stage,
		&i.LinkedObjectType,
		&i.LinkedObjectID,
		&i.Provider,
		&i.Model,
		&i.PromptVersion,
		&i.RequestFingerprint,
		&i.Status,
		&i.ErrorCode,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.CostUsd,
		&i.ParentCallID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttemptNumber,
		&i.ProviderCalled,
		&i.ProviderStartedAt,
		&i.CausedByCallID,
		&i.VerifierOutcome,
	)
	return i, err
}

const getLatestAICallForRequest = `-- name: GetLatestAICallForRequest :one
select id, project_id, run_id, stage, linked_object_type, linked_object_id, provider, model, prompt_version, request_fingerprint, status, error_code, prompt_tokens, completion_tokens, total_tokens, cost_usd, parent_call_id, started_at, finished_at, created_at, updated_at, attempt_number, provider_called, provider_started_at, caused_by_call_id, verifier_outcome from ai_call_records
where project_id = $1
  and stage = $2
  and linked_object_type = $3
  and linked_object_id = $4
  and request_fingerprint = $5
order by attempt_number desc, created_at desc, id desc
limit 1
`

type GetLatestAICallForRequestParams struct {
	ProjectID          uuid.UUID `json:"project_id"`
	Stage              string    `json:"stage"`
	LinkedObjectType   string    `json:"linked_object_type"`
	LinkedObjectID     uuid.UUID `json:"linked_object_id"`
	RequestFingerprint string    `json:"request_fingerprint"`
}

func (q *Queries) GetLatestAICallForRequest(ctx context.Context, arg GetLatestAICallForRequestParams) (AiCallRecord, error) {
	row := q.db.QueryRow(ctx, getLatestAICallForRequest,
		arg.ProjectID,
		arg.Stage,
		arg.LinkedObjectType,
		arg.LinkedObjectID,
		arg.RequestFingerprint,
	)
	var i AiCallRecord
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RunID,
		&i.Stage,
		&i.LinkedObjectType,
		&i.LinkedObjectID,
		&i.Provider,
		&i.Model,
		&i.PromptVersion,
		&i.RequestFingerprint,
		&i.Status,
		&i.ErrorCode,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.CostUsd,
		&i.ParentCallID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttemptNumber,
		&i.ProviderCalled,
		&i.ProviderStartedAt,
		&i.CausedByCallID,
		&i.VerifierOutcome,
	)
	return i, err
}

const listAICallsForObject = `-- name: ListAICallsForObject :many
select id, project_id, run_id, stage, linked_object_type, linked_object_id, provider, model, prompt_version, request_fingerprint, status, error_code, prompt_tokens, completion_tokens, total_tokens, cost_usd, parent_call_id, started_at, finished_at, created_at, updated_at, attempt_number, provider_called, provider_started_at, caused_by_call_id, verifier_outcome from ai_call_records
where project_id = $1
  and linked_object_type = $2
  and linked_object_id = $3
order by created_at, id
`

type ListAICallsForObjectParams struct {
	ProjectID        uuid.UUID `json:"project_id"`
	LinkedObjectType string    `json:"linked_object_type"`
	LinkedObjectID   uuid.UUID `json:"linked_object_id"`
}

func (q *Queries) ListAICallsForObject(ctx context.Context, arg ListAICallsForObjectParams) ([]AiCallRecord, error) {
	rows, err := q.db.Query(ctx, listAICallsForObject, arg.ProjectID, arg.LinkedObjectType, arg.LinkedObjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiCallRecord
	for rows.Next() {
		var i AiCallRecord
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RunID,
			&i.Stage,
			&i.LinkedObjectType,
			&i.LinkedObjectID,
			&i.Provider,
			&i.Model,
			&i.PromptVersion,
			&i.RequestFingerprint,
			&i.Status,
			&i.ErrorCode,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.CostUsd,
			&i.ParentCallID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AttemptNumber,
			&i.ProviderCalled,
			&i.ProviderStartedAt,
			&i.CausedByCallID,
			&i.VerifierOutcome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAICallProviderStarted = `-- name: MarkAICallProviderStarted :one
update ai_call_records set
  status = 'running',
  model = coalesce($1, model),
  provider_called = true,
  provider_started_at = now(),
  updated_at = now()
where id = $2
  and project_id = $3
  and status = 'queued'
returning id, project_id, run_id, stage, linked_object_type, linked_object_id, provider, model, prompt_version, request_fingerprint, status, error_code, prompt_tokens, completion_tokens, total_tokens, cost_usd, parent_call_id, started_at, finished_at, created_at, updated_at, attempt_number, provider_called, provider_started_at, caused_by_call_id, verifier_outcome
`

type MarkAICallProviderStartedParams struct {
	ResolvedModel *string   `json:"resolved_model"`
	ID            uuid.UUID `json:"id"`
	ProjectID     uuid.UUID `json:"project_id"`
}

func (q *Queries) MarkAICallProviderStarted(ctx context.Context, arg MarkAICallProviderStartedParams) (AiCallRecord, error) {
	row := q.db.QueryRow(ctx, markAICallProviderStarted, arg.ResolvedModel, arg.ID, arg.ProjectID)
	var i AiCallRecord
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RunID,
		&i.Stage,
		&i.LinkedObjectType,
		&i.LinkedObjectID,
		&i.Provider,
		&i.Model,
		&i.PromptVersion,
		&i.RequestFingerprint,
		&i.Status,
		&i.ErrorCode,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.CostUsd,
		&i.ParentCallID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttemptNumber,
		&i.ProviderCalled,
		&i.ProviderStartedAt,
		&i.CausedByCallID,
		&i.VerifierOutcome,
	)
	return i, err
}

const reclassifyAICallRecordOutputFailure = `-- name: ReclassifyAICallRecordOutputFailure :one
update ai_call_records set
  status = 'failed', error_code = $1, updated_at = now()
where id = $2
  and project_id = $3
  and status in ('ok', 'partial')
returning id, project_id, run_id, stage, linked_object_type, linked_object_id, provider, model, prompt_version, request_fingerprint, status, error_code, prompt_tokens, completion_tokens, total_tokens, cost_usd, parent_call_id, started_at, finished_at, created_at, updated_at, attempt_number, provider_called, provider_started_at, caused_by_call_id, verifier_outcome
`

type ReclassifyAICallRecordOutputFailureParams struct {
	ErrorCode *string   `json:"error_code"`
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) ReclassifyAICallRecordOutputFailure(ctx context.Context, arg ReclassifyAICallRecordOutputFailureParams) (AiCallRecord, error) {
	row := q.db.QueryRow(ctx, reclassifyAICallRecordOutputFailure, arg.ErrorCode, arg.ID, arg.ProjectID)
	var i AiCallRecord
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RunID,
		&i.Stage,
		&i.LinkedObjectType,
		&i.LinkedObjectID,
		&i.Provider,
		&i.Model,
		&i.PromptVersion,
		&i.RequestFingerprint,
		&i.Status,
		&i.ErrorCode,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.CostUsd,
		&i.ParentCallID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttemptNumber,
		&i.ProviderCalled,
		&i.ProviderStartedAt,
		&i.CausedByCallID,
		&i.VerifierOutcome,
	)
	return i, err
}
