// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: autopilot.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSEOActionPlan = `-- name: CreateSEOActionPlan :one
insert into seo_action_plans
  (project_id, autopilot_run_id, objective_id, plan_window_start, plan_window_end,
   status, actions, expected_impact, expected_effort, aggregate_risk,
   risk_classifier_version, approval_required)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
returning id, project_id, autopilot_run_id, objective_id, plan_window_start, plan_window_end, status, actions, expected_impact, expected_effort, aggregate_risk, risk_classifier_version, approval_required, approved_by, approved_at, created_at, updated_at
`

type CreateSEOActionPlanParams struct {
	ProjectID             uuid.UUID       `json:"project_id"`
	AutopilotRunID        pgtype.UUID     `json:"autopilot_run_id"`
	ObjectiveID           pgtype.UUID     `json:"objective_id"`
	PlanWindowStart       pgtype.Date     `json:"plan_window_start"`
	PlanWindowEnd         pgtype.Date     `json:"plan_window_end"`
	Status                string          `json:"status"`
	Actions               json.RawMessage `json:"actions"`
	ExpectedImpact        json.RawMessage `json:"expected_impact"`
	ExpectedEffort        int32           `json:"expected_effort"`
	AggregateRisk         string          `json:"aggregate_risk"`
	RiskClassifierVersion string          `json:"risk_classifier_version"`
	ApprovalRequired      bool            `json:"approval_required"`
}

func (q *Queries) CreateSEOActionPlan(ctx context.Context, arg CreateSEOActionPlanParams) (SeoActionPlan, error) {
	row := q.db.QueryRow(ctx, createSEOActionPlan,
		arg.ProjectID,
		arg.AutopilotRunID,
		arg.ObjectiveID,
		arg.PlanWindowStart,
		arg.PlanWindowEnd,
		arg.Status,
		arg.Actions,
		arg.ExpectedImpact,
		arg.ExpectedEffort,
		arg.AggregateRisk,
		arg.RiskClassifierVersion,
		arg.ApprovalRequired,
	)
	var i SeoActionPlan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AutopilotRunID,
		&i.ObjectiveID,
		&i.PlanWindowStart,
		&i.PlanWindowEnd,
		&i.Status,
		&i.Actions,
		&i.ExpectedImpact,
		&i.ExpectedEffort,
		&i.AggregateRisk,
		&i.RiskClassifierVersion,
		&i.ApprovalRequired,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSEOObjective = `-- name: CreateSEOObjective :one
insert into seo_objectives
  (project_id, name, status, primary_metric, secondary_metrics, target_pages,
   target_topics, target_queries, time_horizon_days, budget_usd)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
returning id, project_id, name, status, primary_metric, secondary_metrics, target_pages, target_topics, target_queries, time_horizon_days, budget_usd, created_at, updated_at
`

type CreateSEOObjectiveParams struct {
	ProjectID        uuid.UUID       `json:"project_id"`
	Name             string          `json:"name"`
	Status           string          `json:"status"`
	PrimaryMetric    string          `json:"primary_metric"`
	SecondaryMetrics json.RawMessage `json:"secondary_metrics"`
	TargetPages      json.RawMessage `json:"target_pages"`
	TargetTopics     json.RawMessage `json:"target_topics"`
	TargetQueries    json.RawMessage `json:"target_queries"`
	TimeHorizonDays  int32           `json:"time_horizon_days"`
	BudgetUsd        pgtype.Numeric  `json:"budget_usd"`
}

func (q *Queries) CreateSEOObjective(ctx context.Context, arg CreateSEOObjectiveParams) (SeoObjective, error) {
	row := q.db.QueryRow(ctx, createSEOObjective,
		arg.ProjectID,
		arg.Name,
		arg.Status,
		arg.PrimaryMetric,
		arg.SecondaryMetrics,
		arg.TargetPages,
		arg.TargetTopics,
		arg.TargetQueries,
		arg.TimeHorizonDays,
		arg.BudgetUsd,
	)
	var i SeoObjective
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Status,
		&i.PrimaryMetric,
		&i.SecondaryMetrics,
		&i.TargetPages,
		&i.TargetTopics,
		&i.TargetQueries,
		&i.TimeHorizonDays,
		&i.BudgetUsd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enterSafeMode = `-- name: EnterSafeMode :one
insert into safe_mode_events
  (project_id, reason, trigger_source, entered_by, related_run_id, related_action_id)
values ($1, $2, $3, $4, $5, $6)
on conflict (project_id) where exited_at is null do update set
  reason = excluded.reason,
  trigger_source = excluded.trigger_source,
  related_run_id = excluded.related_run_id,
  related_action_id = excluded.related_action_id
returning id, project_id, reason, trigger_source, entered_at, entered_by, exited_at, exited_by, exit_reason, related_run_id, related_action_id
`

type EnterSafeModeParams struct {
	ProjectID       uuid.UUID   `json:"project_id"`
	Reason          string      `json:"reason"`
	TriggerSource   string      `json:"trigger_source"`
	EnteredBy       string      `json:"entered_by"`
	RelatedRunID    pgtype.UUID `json:"related_run_id"`
	RelatedActionID pgtype.UUID `json:"related_action_id"`
}

func (q *Queries) EnterSafeMode(ctx context.Context, arg EnterSafeModeParams) (SafeModeEvent, error) {
	row := q.db.QueryRow(ctx, enterSafeMode,
		arg.ProjectID,
		arg.Reason,
		arg.TriggerSource,
		arg.EnteredBy,
		arg.RelatedRunID,
		arg.RelatedActionID,
	)
	var i SafeModeEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Reason,
		&i.TriggerSource,
		&i.EnteredAt,
		&i.EnteredBy,
		&i.ExitedAt,
		&i.ExitedBy,
		&i.ExitReason,
		&i.RelatedRunID,
		&i.RelatedActionID,
	)
	return i, err
}

const exitSafeMode = `-- name: ExitSafeMode :one
update safe_mode_events set
  exited_at = now(),
  exited_by = $3,
  exit_reason = $4
where id = $1 and project_id = $2 and exited_at is null
returning id, project_id, reason, trigger_source, entered_at, entered_by, exited_at, exited_by, exit_reason, related_run_id, related_action_id
`

type ExitSafeModeParams struct {
	ID         uuid.UUID `json:"id"`
	ProjectID  uuid.UUID `json:"project_id"`
	ExitedBy   *string   `json:"exited_by"`
	ExitReason *string   `json:"exit_reason"`
}

func (q *Queries) ExitSafeMode(ctx context.Context, arg ExitSafeModeParams) (SafeModeEvent, error) {
	row := q.db.QueryRow(ctx, exitSafeMode,
		arg.ID,
		arg.ProjectID,
		arg.ExitedBy,
		arg.ExitReason,
	)
	var i SafeModeEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Reason,
		&i.TriggerSource,
		&i.EnteredAt,
		&i.EnteredBy,
		&i.ExitedAt,
		&i.ExitedBy,
		&i.ExitReason,
		&i.RelatedRunID,
		&i.RelatedActionID,
	)
	return i, err
}

const getOpenSafeModeEvent = `-- name: GetOpenSafeModeEvent :one
select id, project_id, reason, trigger_source, entered_at, entered_by, exited_at, exited_by, exit_reason, related_run_id, related_action_id from safe_mode_events
where project_id = $1 and exited_at is null
limit 1
`

func (q *Queries) GetOpenSafeModeEvent(ctx context.Context, projectID uuid.UUID) (SafeModeEvent, error) {
	row := q.db.QueryRow(ctx, getOpenSafeModeEvent, projectID)
	var i SafeModeEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Reason,
		&i.TriggerSource,
		&i.EnteredAt,
		&i.EnteredBy,
		&i.ExitedAt,
		&i.ExitedBy,
		&i.ExitReason,
		&i.RelatedRunID,
		&i.RelatedActionID,
	)
	return i, err
}

const getRiskClassificationRule = `-- name: GetRiskClassificationRule :one
select id, project_id, version, rules, created_by, created_at, retired_at from risk_classification_rules
where project_id = $1 and version = $2
`

type GetRiskClassificationRuleParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Version   string    `json:"version"`
}

func (q *Queries) GetRiskClassificationRule(ctx context.Context, arg GetRiskClassificationRuleParams) (RiskClassificationRule, error) {
	row := q.db.QueryRow(ctx, getRiskClassificationRule, arg.ProjectID, arg.Version)
	var i RiskClassificationRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.Rules,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const getSEOActionPlanForProject = `-- name: GetSEOActionPlanForProject :one
select id, project_id, autopilot_run_id, objective_id, plan_window_start, plan_window_end, status, actions, expected_impact, expected_effort, aggregate_risk, risk_classifier_version, approval_required, approved_by, approved_at, created_at, updated_at from seo_action_plans
where id = $1 and project_id = $2
`

type GetSEOActionPlanForProjectParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetSEOActionPlanForProject(ctx context.Context, arg GetSEOActionPlanForProjectParams) (SeoActionPlan, error) {
	row := q.db.QueryRow(ctx, getSEOActionPlanForProject, arg.ID, arg.ProjectID)
	var i SeoActionPlan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AutopilotRunID,
		&i.ObjectiveID,
		&i.PlanWindowStart,
		&i.PlanWindowEnd,
		&i.Status,
		&i.Actions,
		&i.ExpectedImpact,
		&i.ExpectedEffort,
		&i.AggregateRisk,
		&i.RiskClassifierVersion,
		&i.ApprovalRequired,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSEOPolicy = `-- name: GetSEOPolicy :one
select id, project_id, autopilot_level, weekly_action_limit, monthly_budget_limit, allowed_action_types, blocked_url_patterns, requires_review_action_types, max_auto_changes_per_page_per_month, low_traffic_clicks_28d_threshold, low_traffic_impressions_28d_threshold, min_confidence_for_auto_publish, quiet_hours_start, quiet_hours_end, quiet_hours_timezone, quiet_hours_behavior, kill_switch_enabled, safe_mode_enabled, risk_classifier_version, created_at, updated_at from seo_policies
where project_id = $1
`

func (q *Queries) GetSEOPolicy(ctx context.Context, projectID uuid.UUID) (SeoPolicy, error) {
	row := q.db.QueryRow(ctx, getSEOPolicy, projectID)
	var i SeoPolicy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AutopilotLevel,
		&i.WeeklyActionLimit,
		&i.MonthlyBudgetLimit,
		&i.AllowedActionTypes,
		&i.BlockedUrlPatterns,
		&i.RequiresReviewActionTypes,
		&i.MaxAutoChangesPerPagePerMonth,
		&i.LowTrafficClicks28dThreshold,
		&i.LowTrafficImpressions28dThreshold,
		&i.MinConfidenceForAutoPublish,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.QuietHoursTimezone,
		&i.QuietHoursBehavior,
		&i.KillSwitchEnabled,
		&i.SafeModeEnabled,
		&i.RiskClassifierVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAutopilotAuditEvent = `-- name: InsertAutopilotAuditEvent :one
insert into autopilot_audit_events
  (project_id, actor, event_type, entity_type, entity_id, before_snapshot, after_snapshot)
values ($1, $2, $3, $4, $5, $6, $7)
returning id, project_id, actor, event_type, entity_type, entity_id, before_snapshot, after_snapshot, created_at
`

type InsertAutopilotAuditEventParams struct {
	ProjectID      uuid.UUID       `json:"project_id"`
	Actor          string          `json:"actor"`
	EventType      string          `json:"event_type"`
	EntityType     string          `json:"entity_type"`
	EntityID       pgtype.UUID     `json:"entity_id"`
	BeforeSnapshot json.RawMessage `json:"before_snapshot"`
	AfterSnapshot  json.RawMessage `json:"after_snapshot"`
}

func (q *Queries) InsertAutopilotAuditEvent(ctx context.Context, arg InsertAutopilotAuditEventParams) (AutopilotAuditEvent, error) {
	row := q.db.QueryRow(ctx, insertAutopilotAuditEvent,
		arg.ProjectID,
		arg.Actor,
		arg.EventType,
		arg.EntityType,
		arg.EntityID,
		arg.BeforeSnapshot,
		arg.AfterSnapshot,
	)
	var i AutopilotAuditEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Actor,
		&i.EventType,
		&i.EntityType,
		&i.EntityID,
		&i.BeforeSnapshot,
		&i.AfterSnapshot,
		&i.CreatedAt,
	)
	return i, err
}

const insertAutopilotRun = `-- name: InsertAutopilotRun :one
insert into autopilot_runs
  (project_id, objective_id, status, autopilot_level_snapshot, derived_mode,
   started_at, finished_at, input_snapshot, selected_actions, rejected_actions,
   guardrail_results, published_changes, cost_usd, error)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
returning id, project_id, objective_id, status, autopilot_level_snapshot, derived_mode, started_at, finished_at, input_snapshot, selected_actions, rejected_actions, guardrail_results, published_changes, cost_usd, error
`

type InsertAutopilotRunParams struct {
	ProjectID              uuid.UUID          `json:"project_id"`
	ObjectiveID            pgtype.UUID        `json:"objective_id"`
	Status                 string             `json:"status"`
	AutopilotLevelSnapshot int32              `json:"autopilot_level_snapshot"`
	DerivedMode            string             `json:"derived_mode"`
	StartedAt              pgtype.Timestamptz `json:"started_at"`
	FinishedAt             pgtype.Timestamptz `json:"finished_at"`
	InputSnapshot          json.RawMessage    `json:"input_snapshot"`
	SelectedActions        json.RawMessage    `json:"selected_actions"`
	RejectedActions        json.RawMessage    `json:"rejected_actions"`
	GuardrailResults       json.RawMessage    `json:"guardrail_results"`
	PublishedChanges       json.RawMessage    `json:"published_changes"`
	CostUsd                pgtype.Numeric     `json:"cost_usd"`
	Error                  *string            `json:"error"`
}

func (q *Queries) InsertAutopilotRun(ctx context.Context, arg InsertAutopilotRunParams) (AutopilotRun, error) {
	row := q.db.QueryRow(ctx, insertAutopilotRun,
		arg.ProjectID,
		arg.ObjectiveID,
		arg.Status,
		arg.AutopilotLevelSnapshot,
		arg.DerivedMode,
		arg.StartedAt,
		arg.FinishedAt,
		arg.InputSnapshot,
		arg.SelectedActions,
		arg.RejectedActions,
		arg.GuardrailResults,
		arg.PublishedChanges,
		arg.CostUsd,
		arg.Error,
	)
	var i AutopilotRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ObjectiveID,
		&i.Status,
		&i.AutopilotLevelSnapshot,
		&i.DerivedMode,
		&i.StartedAt,
		&i.FinishedAt,
		&i.InputSnapshot,
		&i.SelectedActions,
		&i.RejectedActions,
		&i.GuardrailResults,
		&i.PublishedChanges,
		&i.CostUsd,
		&i.Error,
	)
	return i, err
}

const listAutopilotRuns = `-- name: ListAutopilotRuns :many
select id, project_id, objective_id, status, autopilot_level_snapshot, derived_mode, started_at, finished_at, input_snapshot, selected_actions, rejected_actions, guardrail_results, published_changes, cost_usd, error from autopilot_runs
where project_id = $1
order by started_at desc
limit $2
`

type ListAutopilotRunsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListAutopilotRuns(ctx context.Context, arg ListAutopilotRunsParams) ([]AutopilotRun, error) {
	rows, err := q.db.Query(ctx, listAutopilotRuns, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutopilotRun
	for rows.Next() {
		var i AutopilotRun
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ObjectiveID,
			&i.Status,
			&i.AutopilotLevelSnapshot,
			&i.DerivedMode,
			&i.StartedAt,
			&i.FinishedAt,
			&i.InputSnapshot,
			&i.SelectedActions,
			&i.RejectedActions,
			&i.GuardrailResults,
			&i.PublishedChanges,
			&i.CostUsd,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSEOActionPlans = `-- name: ListSEOActionPlans :many
select id, project_id, autopilot_run_id, objective_id, plan_window_start, plan_window_end, status, actions, expected_impact, expected_effort, aggregate_risk, risk_classifier_version, approval_required, approved_by, approved_at, created_at, updated_at from seo_action_plans
where project_id = $1
order by created_at desc
limit $2
`

type ListSEOActionPlansParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListSEOActionPlans(ctx context.Context, arg ListSEOActionPlansParams) ([]SeoActionPlan, error) {
	rows, err := q.db.Query(ctx, listSEOActionPlans, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeoActionPlan
	for rows.Next() {
		var i SeoActionPlan
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AutopilotRunID,
			&i.ObjectiveID,
			&i.PlanWindowStart,
			&i.PlanWindowEnd,
			&i.Status,
			&i.Actions,
			&i.ExpectedImpact,
			&i.ExpectedEffort,
			&i.AggregateRisk,
			&i.RiskClassifierVersion,
			&i.ApprovalRequired,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSEOObjectives = `-- name: ListSEOObjectives :many
select id, project_id, name, status, primary_metric, secondary_metrics, target_pages, target_topics, target_queries, time_horizon_days, budget_usd, created_at, updated_at from seo_objectives
where project_id = $1
  and ($2::text = '' or status = $2)
order by created_at desc
`

type ListSEOObjectivesParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Column2   string    `json:"column_2"`
}

func (q *Queries) ListSEOObjectives(ctx context.Context, arg ListSEOObjectivesParams) ([]SeoObjective, error) {
	rows, err := q.db.Query(ctx, listSEOObjectives, arg.ProjectID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeoObjective
	for rows.Next() {
		var i SeoObjective
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Status,
			&i.PrimaryMetric,
			&i.SecondaryMetrics,
			&i.TargetPages,
			&i.TargetTopics,
			&i.TargetQueries,
			&i.TimeHorizonDays,
			&i.BudgetUsd,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSafeModeEvents = `-- name: ListSafeModeEvents :many
select id, project_id, reason, trigger_source, entered_at, entered_by, exited_at, exited_by, exit_reason, related_run_id, related_action_id from safe_mode_events
where project_id = $1
order by entered_at desc
limit $2
`

type ListSafeModeEventsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListSafeModeEvents(ctx context.Context, arg ListSafeModeEventsParams) ([]SafeModeEvent, error) {
	rows, err := q.db.Query(ctx, listSafeModeEvents, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SafeModeEvent
	for rows.Next() {
		var i SafeModeEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Reason,
			&i.TriggerSource,
			&i.EnteredAt,
			&i.EnteredBy,
			&i.ExitedAt,
			&i.ExitedBy,
			&i.ExitReason,
			&i.RelatedRunID,
			&i.RelatedActionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSEOActionPlanStatus = `-- name: UpdateSEOActionPlanStatus :one
update seo_action_plans set
  status = $3,
  updated_at = now()
where id = $1 and project_id = $2
returning id, project_id, autopilot_run_id, objective_id, plan_window_start, plan_window_end, status, actions, expected_impact, expected_effort, aggregate_risk, risk_classifier_version, approval_required, approved_by, approved_at, created_at, updated_at
`

type UpdateSEOActionPlanStatusParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	Status    string    `json:"status"`
}

func (q *Queries) UpdateSEOActionPlanStatus(ctx context.Context, arg UpdateSEOActionPlanStatusParams) (SeoActionPlan, error) {
	row := q.db.QueryRow(ctx, updateSEOActionPlanStatus, arg.ID, arg.ProjectID, arg.Status)
	var i SeoActionPlan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AutopilotRunID,
		&i.ObjectiveID,
		&i.PlanWindowStart,
		&i.PlanWindowEnd,
		&i.Status,
		&i.Actions,
		&i.ExpectedImpact,
		&i.ExpectedEffort,
		&i.AggregateRisk,
		&i.RiskClassifierVersion,
		&i.ApprovalRequired,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSEOObjectiveStatus = `-- name: UpdateSEOObjectiveStatus :one
update seo_objectives set
  status = $3,
  updated_at = now()
where id = $1 and project_id = $2
returning id, project_id, name, status, primary_metric, secondary_metrics, target_pages, target_topics, target_queries, time_horizon_days, budget_usd, created_at, updated_at
`

type UpdateSEOObjectiveStatusParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	Status    string    `json:"status"`
}

func (q *Queries) UpdateSEOObjectiveStatus(ctx context.Context, arg UpdateSEOObjectiveStatusParams) (SeoObjective, error) {
	row := q.db.QueryRow(ctx, updateSEOObjectiveStatus, arg.ID, arg.ProjectID, arg.Status)
	var i SeoObjective
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Status,
		&i.PrimaryMetric,
		&i.SecondaryMetrics,
		&i.TargetPages,
		&i.TargetTopics,
		&i.TargetQueries,
		&i.TimeHorizonDays,
		&i.BudgetUsd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRiskClassificationRule = `-- name: UpsertRiskClassificationRule :one
insert into risk_classification_rules
  (project_id, version, rules, created_by, retired_at)
values ($1, $2, $3, $4, $5)
on conflict (project_id, version) do update set
  rules = excluded.rules,
  retired_at = excluded.retired_at
returning id, project_id, version, rules, created_by, created_at, retired_at
`

type UpsertRiskClassificationRuleParams struct {
	ProjectID uuid.UUID          `json:"project_id"`
	Version   string             `json:"version"`
	Rules     json.RawMessage    `json:"rules"`
	CreatedBy string             `json:"created_by"`
	RetiredAt pgtype.Timestamptz `json:"retired_at"`
}

func (q *Queries) UpsertRiskClassificationRule(ctx context.Context, arg UpsertRiskClassificationRuleParams) (RiskClassificationRule, error) {
	row := q.db.QueryRow(ctx, upsertRiskClassificationRule,
		arg.ProjectID,
		arg.Version,
		arg.Rules,
		arg.CreatedBy,
		arg.RetiredAt,
	)
	var i RiskClassificationRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.Rules,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const upsertSEOPolicy = `-- name: UpsertSEOPolicy :one
insert into seo_policies
  (project_id, autopilot_level, weekly_action_limit, monthly_budget_limit,
   allowed_action_types, blocked_url_patterns, requires_review_action_types,
   max_auto_changes_per_page_per_month, low_traffic_clicks_28d_threshold,
   low_traffic_impressions_28d_threshold, min_confidence_for_auto_publish,
   quiet_hours_start, quiet_hours_end, quiet_hours_timezone, quiet_hours_behavior,
   kill_switch_enabled, safe_mode_enabled, risk_classifier_version)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
on conflict (project_id) do update set
  autopilot_level = excluded.autopilot_level,
  weekly_action_limit = excluded.weekly_action_limit,
  monthly_budget_limit = excluded.monthly_budget_limit,
  allowed_action_types = excluded.allowed_action_types,
  blocked_url_patterns = excluded.blocked_url_patterns,
  requires_review_action_types = excluded.requires_review_action_types,
  max_auto_changes_per_page_per_month = excluded.max_auto_changes_per_page_per_month,
  low_traffic_clicks_28d_threshold = excluded.low_traffic_clicks_28d_threshold,
  low_traffic_impressions_28d_threshold = excluded.low_traffic_impressions_28d_threshold,
  min_confidence_for_auto_publish = excluded.min_confidence_for_auto_publish,
  quiet_hours_start = excluded.quiet_hours_start,
  quiet_hours_end = excluded.quiet_hours_end,
  quiet_hours_timezone = excluded.quiet_hours_timezone,
  quiet_hours_behavior = excluded.quiet_hours_behavior,
  kill_switch_enabled = excluded.kill_switch_enabled,
  safe_mode_enabled = excluded.safe_mode_enabled,
  risk_classifier_version = excluded.risk_classifier_version,
  updated_at = now()
returning id, project_id, autopilot_level, weekly_action_limit, monthly_budget_limit, allowed_action_types, blocked_url_patterns, requires_review_action_types, max_auto_changes_per_page_per_month, low_traffic_clicks_28d_threshold, low_traffic_impressions_28d_threshold, min_confidence_for_auto_publish, quiet_hours_start, quiet_hours_end, quiet_hours_timezone, quiet_hours_behavior, kill_switch_enabled, safe_mode_enabled, risk_classifier_version, created_at, updated_at
`

type UpsertSEOPolicyParams struct {
	ProjectID                         uuid.UUID       `json:"project_id"`
	AutopilotLevel                    int32           `json:"autopilot_level"`
	WeeklyActionLimit                 int32           `json:"weekly_action_limit"`
	MonthlyBudgetLimit                pgtype.Numeric  `json:"monthly_budget_limit"`
	AllowedActionTypes                json.RawMessage `json:"allowed_action_types"`
	BlockedUrlPatterns                json.RawMessage `json:"blocked_url_patterns"`
	RequiresReviewActionTypes         json.RawMessage `json:"requires_review_action_types"`
	MaxAutoChangesPerPagePerMonth     int32           `json:"max_auto_changes_per_page_per_month"`
	LowTrafficClicks28dThreshold      int32           `json:"low_traffic_clicks_28d_threshold"`
	LowTrafficImpressions28dThreshold int32           `json:"low_traffic_impressions_28d_threshold"`
	MinConfidenceForAutoPublish       pgtype.Numeric  `json:"min_confidence_for_auto_publish"`
	QuietHoursStart                   *string         `json:"quiet_hours_start"`
	QuietHoursEnd                     *string         `json:"quiet_hours_end"`
	QuietHoursTimezone                string          `json:"quiet_hours_timezone"`
	QuietHoursBehavior                string          `json:"quiet_hours_behavior"`
	KillSwitchEnabled                 bool            `json:"kill_switch_enabled"`
	SafeModeEnabled                   bool            `json:"safe_mode_enabled"`
	RiskClassifierVersion             string          `json:"risk_classifier_version"`
}

func (q *Queries) UpsertSEOPolicy(ctx context.Context, arg UpsertSEOPolicyParams) (SeoPolicy, error) {
	row := q.db.QueryRow(ctx, upsertSEOPolicy,
		arg.ProjectID,
		arg.AutopilotLevel,
		arg.WeeklyActionLimit,
		arg.MonthlyBudgetLimit,
		arg.AllowedActionTypes,
		arg.BlockedUrlPatterns,
		arg.RequiresReviewActionTypes,
		arg.MaxAutoChangesPerPagePerMonth,
		arg.LowTrafficClicks28dThreshold,
		arg.LowTrafficImpressions28dThreshold,
		arg.MinConfidenceForAutoPublish,
		arg.QuietHoursStart,
		arg.QuietHoursEnd,
		arg.QuietHoursTimezone,
		arg.QuietHoursBehavior,
		arg.KillSwitchEnabled,
		arg.SafeModeEnabled,
		arg.RiskClassifierVersion,
	)
	var i SeoPolicy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AutopilotLevel,
		&i.WeeklyActionLimit,
		&i.MonthlyBudgetLimit,
		&i.AllowedActionTypes,
		&i.BlockedUrlPatterns,
		&i.RequiresReviewActionTypes,
		&i.MaxAutoChangesPerPagePerMonth,
		&i.LowTrafficClicks28dThreshold,
		&i.LowTrafficImpressions28dThreshold,
		&i.MinConfidenceForAutoPublish,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.QuietHoursTimezone,
		&i.QuietHoursBehavior,
		&i.KillSwitchEnabled,
		&i.SafeModeEnabled,
		&i.RiskClassifierVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
