// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discovery.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeDiscoveryShadowRun = `-- name: CompleteDiscoveryShadowRun :one
update discovery_shadow_runs set
  status = 'completed',
  doctor_candidates = $1,
  opportunity_candidates = $2,
  identity_ready = $3,
  needs_specification = $4,
  exact_duplicate_groups = $5,
  possible_conflict_groups = $6,
  error = null,
  finished_at = now(),
  updated_at = now()
where id = $7 and project_id = $8
returning id, project_id, mode, status, candidate_schema_version, signature_version, doctor_candidates, opportunity_candidates, identity_ready, needs_specification, exact_duplicate_groups, possible_conflict_groups, error, started_at, finished_at, created_at, updated_at
`

type CompleteDiscoveryShadowRunParams struct {
	DoctorCandidates       int32     `json:"doctor_candidates"`
	OpportunityCandidates  int32     `json:"opportunity_candidates"`
	IdentityReady          int32     `json:"identity_ready"`
	NeedsSpecification     int32     `json:"needs_specification"`
	ExactDuplicateGroups   int32     `json:"exact_duplicate_groups"`
	PossibleConflictGroups int32     `json:"possible_conflict_groups"`
	ID                     uuid.UUID `json:"id"`
	ProjectID              uuid.UUID `json:"project_id"`
}

func (q *Queries) CompleteDiscoveryShadowRun(ctx context.Context, arg CompleteDiscoveryShadowRunParams) (DiscoveryShadowRun, error) {
	row := q.db.QueryRow(ctx, completeDiscoveryShadowRun,
		arg.DoctorCandidates,
		arg.OpportunityCandidates,
		arg.IdentityReady,
		arg.NeedsSpecification,
		arg.ExactDuplicateGroups,
		arg.PossibleConflictGroups,
		arg.ID,
		arg.ProjectID,
	)
	var i DiscoveryShadowRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Mode,
		&i.Status,
		&i.CandidateSchemaVersion,
		&i.SignatureVersion,
		&i.DoctorCandidates,
		&i.OpportunityCandidates,
		&i.IdentityReady,
		&i.NeedsSpecification,
		&i.ExactDuplicateGroups,
		&i.PossibleConflictGroups,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDiscoveryShadowRun = `-- name: CreateDiscoveryShadowRun :one
insert into discovery_shadow_runs
  (project_id, candidate_schema_version, signature_version)
values
  ($1, $2, $3)
returning id, project_id, mode, status, candidate_schema_version, signature_version, doctor_candidates, opportunity_candidates, identity_ready, needs_specification, exact_duplicate_groups, possible_conflict_groups, error, started_at, finished_at, created_at, updated_at
`

type CreateDiscoveryShadowRunParams struct {
	ProjectID              uuid.UUID `json:"project_id"`
	CandidateSchemaVersion string    `json:"candidate_schema_version"`
	SignatureVersion       string    `json:"signature_version"`
}

func (q *Queries) CreateDiscoveryShadowRun(ctx context.Context, arg CreateDiscoveryShadowRunParams) (DiscoveryShadowRun, error) {
	row := q.db.QueryRow(ctx, createDiscoveryShadowRun, arg.ProjectID, arg.CandidateSchemaVersion, arg.SignatureVersion)
	var i DiscoveryShadowRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Mode,
		&i.Status,
		&i.CandidateSchemaVersion,
		&i.SignatureVersion,
		&i.DoctorCandidates,
		&i.OpportunityCandidates,
		&i.IdentityReady,
		&i.NeedsSpecification,
		&i.ExactDuplicateGroups,
		&i.PossibleConflictGroups,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteShadowWorkSignatureForCandidate = `-- name: DeleteShadowWorkSignatureForCandidate :exec
delete from work_signature_registry
where project_id = $1
  and candidate_id = $2
  and mode = 'shadow'
`

type DeleteShadowWorkSignatureForCandidateParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	CandidateID uuid.UUID `json:"candidate_id"`
}

func (q *Queries) DeleteShadowWorkSignatureForCandidate(ctx context.Context, arg DeleteShadowWorkSignatureForCandidateParams) error {
	_, err := q.db.Exec(ctx, deleteShadowWorkSignatureForCandidate, arg.ProjectID, arg.CandidateID)
	return err
}

const ensureWorkConflictBucket = `-- name: EnsureWorkConflictBucket :one
insert into work_conflict_buckets (project_id, bucket_key, bucket_version)
values ($1, $2, 0)
on conflict (project_id, bucket_key) do update set
  updated_at = work_conflict_buckets.updated_at
returning id, project_id, bucket_key, bucket_version, created_at, updated_at
`

type EnsureWorkConflictBucketParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	BucketKey string    `json:"bucket_key"`
}

func (q *Queries) EnsureWorkConflictBucket(ctx context.Context, arg EnsureWorkConflictBucketParams) (WorkConflictBucket, error) {
	row := q.db.QueryRow(ctx, ensureWorkConflictBucket, arg.ProjectID, arg.BucketKey)
	var i WorkConflictBucket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BucketKey,
		&i.BucketVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failDiscoveryShadowRun = `-- name: FailDiscoveryShadowRun :one
update discovery_shadow_runs set
  status = 'failed',
  error = $1,
  finished_at = now(),
  updated_at = now()
where id = $2 and project_id = $3
returning id, project_id, mode, status, candidate_schema_version, signature_version, doctor_candidates, opportunity_candidates, identity_ready, needs_specification, exact_duplicate_groups, possible_conflict_groups, error, started_at, finished_at, created_at, updated_at
`

type FailDiscoveryShadowRunParams struct {
	Error     *string   `json:"error"`
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) FailDiscoveryShadowRun(ctx context.Context, arg FailDiscoveryShadowRunParams) (DiscoveryShadowRun, error) {
	row := q.db.QueryRow(ctx, failDiscoveryShadowRun, arg.Error, arg.ID, arg.ProjectID)
	var i DiscoveryShadowRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Mode,
		&i.Status,
		&i.CandidateSchemaVersion,
		&i.SignatureVersion,
		&i.DoctorCandidates,
		&i.OpportunityCandidates,
		&i.IdentityReady,
		&i.NeedsSpecification,
		&i.ExactDuplicateGroups,
		&i.PossibleConflictGroups,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestDiscoveryShadowRun = `-- name: GetLatestDiscoveryShadowRun :one
select id, project_id, mode, status, candidate_schema_version, signature_version, doctor_candidates, opportunity_candidates, identity_ready, needs_specification, exact_duplicate_groups, possible_conflict_groups, error, started_at, finished_at, created_at, updated_at from discovery_shadow_runs
where project_id = $1
order by created_at desc
limit 1
`

func (q *Queries) GetLatestDiscoveryShadowRun(ctx context.Context, projectID uuid.UUID) (DiscoveryShadowRun, error) {
	row := q.db.QueryRow(ctx, getLatestDiscoveryShadowRun, projectID)
	var i DiscoveryShadowRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Mode,
		&i.Status,
		&i.CandidateSchemaVersion,
		&i.SignatureVersion,
		&i.DoctorCandidates,
		&i.OpportunityCandidates,
		&i.IdentityReady,
		&i.NeedsSpecification,
		&i.ExactDuplicateGroups,
		&i.PossibleConflictGroups,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveDoctorFindingsForDiscoveryShadow = `-- name: ListActiveDoctorFindingsForDiscoveryShadow :many
select id, project_id, run_id, finding_key, severity, category, issue_type, status, affected_urls, normalized_urls, evidence, why_it_matters, fix_intent, developer_instructions, likely_files_or_surfaces, acceptance_tests, risk_level, review_required, autofix_eligible, linked_opportunity_id, linked_content_action_id, first_seen_at, last_seen_at, resolved_at, created_at, updated_at from seo_doctor_findings
where project_id = $1
  and status in ('active','dismissed','converted')
order by created_at asc
`

func (q *Queries) ListActiveDoctorFindingsForDiscoveryShadow(ctx context.Context, projectID uuid.UUID) ([]SeoDoctorFinding, error) {
	rows, err := q.db.Query(ctx, listActiveDoctorFindingsForDiscoveryShadow, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeoDoctorFinding
	for rows.Next() {
		var i SeoDoctorFinding
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RunID,
			&i.FindingKey,
			&i.Severity,
			&i.Category,
			&i.IssueType,
			&i.Status,
			&i.AffectedUrls,
			&i.NormalizedUrls,
			&i.Evidence,
			&i.WhyItMatters,
			&i.FixIntent,
			&i.DeveloperInstructions,
			&i.LikelyFilesOrSurfaces,
			&i.AcceptanceTests,
			&i.RiskLevel,
			&i.ReviewRequired,
			&i.AutofixEligible,
			&i.LinkedOpportunityID,
			&i.LinkedContentActionID,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSEOOpportunitiesForDiscoveryShadow = `-- name: ListActiveSEOOpportunitiesForDiscoveryShadow :many
select id, project_id, type, status, priority_score, confidence, page_url, normalized_page_url, article_id, topic_id, query, evidence, recommended_action, expected_impact, effort, risk_level, created_by_run_id, created_at, updated_at, opportunity_key, snoozed_until, snooze_reason, unsnoozed_at, opportunity_identity_key, evidence_fingerprint from seo_opportunities
where project_id = $1
  and status in ('open','accepted','converted','dismissed','snoozed','watching')
order by created_at asc
`

func (q *Queries) ListActiveSEOOpportunitiesForDiscoveryShadow(ctx context.Context, projectID uuid.UUID) ([]SeoOpportunity, error) {
	rows, err := q.db.Query(ctx, listActiveSEOOpportunitiesForDiscoveryShadow, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeoOpportunity
	for rows.Next() {
		var i SeoOpportunity
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Status,
			&i.PriorityScore,
			&i.Confidence,
			&i.PageUrl,
			&i.NormalizedPageUrl,
			&i.ArticleID,
			&i.TopicID,
			&i.Query,
			&i.Evidence,
			&i.RecommendedAction,
			&i.ExpectedImpact,
			&i.Effort,
			&i.RiskLevel,
			&i.CreatedByRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OpportunityKey,
			&i.SnoozedUntil,
			&i.SnoozeReason,
			&i.UnsnoozedAt,
			&i.OpportunityIdentityKey,
			&i.EvidenceFingerprint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoveryShadowSignaturesForRun = `-- name: ListDiscoveryShadowSignaturesForRun :many
select
  r.id,
  r.project_id,
  r.candidate_id,
  r.exact_signature_hash,
  r.conflict_bucket_keys,
  r.signature_version,
  r.owner,
  r.source_object_type,
  r.source_object_id,
  c.source_kind,
  c.status as candidate_status
from work_signature_registry r
join discovery_candidates c on c.id = r.candidate_id
where r.project_id = $1
  and r.shadow_run_id = $2
  and r.mode = 'shadow'
order by r.created_at asc
`

type ListDiscoveryShadowSignaturesForRunParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	ShadowRunID uuid.UUID `json:"shadow_run_id"`
}

type ListDiscoveryShadowSignaturesForRunRow struct {
	ID                 uuid.UUID       `json:"id"`
	ProjectID          uuid.UUID       `json:"project_id"`
	CandidateID        uuid.UUID       `json:"candidate_id"`
	ExactSignatureHash string          `json:"exact_signature_hash"`
	ConflictBucketKeys json.RawMessage `json:"conflict_bucket_keys"`
	SignatureVersion   string          `json:"signature_version"`
	Owner              *string         `json:"owner"`
	SourceObjectType   string          `json:"source_object_type"`
	SourceObjectID     string          `json:"source_object_id"`
	SourceKind         string          `json:"source_kind"`
	CandidateStatus    string          `json:"candidate_status"`
}

func (q *Queries) ListDiscoveryShadowSignaturesForRun(ctx context.Context, arg ListDiscoveryShadowSignaturesForRunParams) ([]ListDiscoveryShadowSignaturesForRunRow, error) {
	rows, err := q.db.Query(ctx, listDiscoveryShadowSignaturesForRun, arg.ProjectID, arg.ShadowRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDiscoveryShadowSignaturesForRunRow
	for rows.Next() {
		var i ListDiscoveryShadowSignaturesForRunRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CandidateID,
			&i.ExactSignatureHash,
			&i.ConflictBucketKeys,
			&i.SignatureVersion,
			&i.Owner,
			&i.SourceObjectType,
			&i.SourceObjectID,
			&i.SourceKind,
			&i.CandidateStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDiscoveryCandidate = `-- name: UpsertDiscoveryCandidate :one
insert into discovery_candidates
  (project_id, shadow_run_id, source_kind, source_object_type, source_object_id,
   target_kind, normalized_target_set, issue_or_hypothesis_family, change_family,
   proposed_mutations, artifact_intent, intended_slug_or_canonical,
   topic_entity_identity, audience_identity, primary_success_metric,
   verification_mode, evidence_ids, evidence_fingerprint, suggested_owner,
   confidence, candidate_schema_version, status, hold_reason,
   exact_signature_hash, signature_payload, conflict_bucket_keys)
values
  ($1, $2, $3,
   $4, $5, $6,
   $7::jsonb, $8,
   $9, $10::jsonb,
   $11, $12,
   $13::jsonb, $14::jsonb,
   $15, $16,
   $17::jsonb, $18,
   $19, $20,
   $21, $22, $23,
   $24, $25::jsonb,
   $26::jsonb)
on conflict
  (shadow_run_id, project_id, source_kind, source_object_type, source_object_id, candidate_schema_version)
do update set
  target_kind = excluded.target_kind,
  normalized_target_set = excluded.normalized_target_set,
  issue_or_hypothesis_family = excluded.issue_or_hypothesis_family,
  change_family = excluded.change_family,
  proposed_mutations = excluded.proposed_mutations,
  artifact_intent = excluded.artifact_intent,
  intended_slug_or_canonical = excluded.intended_slug_or_canonical,
  topic_entity_identity = excluded.topic_entity_identity,
  audience_identity = excluded.audience_identity,
  primary_success_metric = excluded.primary_success_metric,
  verification_mode = excluded.verification_mode,
  evidence_ids = excluded.evidence_ids,
  evidence_fingerprint = excluded.evidence_fingerprint,
  suggested_owner = excluded.suggested_owner,
  confidence = excluded.confidence,
  status = excluded.status,
  hold_reason = excluded.hold_reason,
  exact_signature_hash = excluded.exact_signature_hash,
  signature_payload = excluded.signature_payload,
  conflict_bucket_keys = excluded.conflict_bucket_keys,
  updated_at = now()
returning id, project_id, shadow_run_id, source_kind, source_object_type, source_object_id, target_kind, normalized_target_set, issue_or_hypothesis_family, change_family, proposed_mutations, artifact_intent, intended_slug_or_canonical, topic_entity_identity, audience_identity, primary_success_metric, verification_mode, evidence_ids, evidence_fingerprint, suggested_owner, confidence, candidate_schema_version, status, hold_reason, exact_signature_hash, signature_payload, conflict_bucket_keys, created_at, updated_at, candidate_version
`

type UpsertDiscoveryCandidateParams struct {
	ProjectID               uuid.UUID       `json:"project_id"`
	ShadowRunID             uuid.UUID       `json:"shadow_run_id"`
	SourceKind              string          `json:"source_kind"`
	SourceObjectType        string          `json:"source_object_type"`
	SourceObjectID          string          `json:"source_object_id"`
	TargetKind              string          `json:"target_kind"`
	NormalizedTargetSet     json.RawMessage `json:"normalized_target_set"`
	IssueOrHypothesisFamily string          `json:"issue_or_hypothesis_family"`
	ChangeFamily            string          `json:"change_family"`
	ProposedMutations       json.RawMessage `json:"proposed_mutations"`
	ArtifactIntent          string          `json:"artifact_intent"`
	IntendedSlugOrCanonical *string         `json:"intended_slug_or_canonical"`
	TopicEntityIdentity     json.RawMessage `json:"topic_entity_identity"`
	AudienceIdentity        json.RawMessage `json:"audience_identity"`
	PrimarySuccessMetric    string          `json:"primary_success_metric"`
	VerificationMode        string          `json:"verification_mode"`
	EvidenceIds             json.RawMessage `json:"evidence_ids"`
	EvidenceFingerprint     string          `json:"evidence_fingerprint"`
	SuggestedOwner          string          `json:"suggested_owner"`
	Confidence              pgtype.Numeric  `json:"confidence"`
	CandidateSchemaVersion  string          `json:"candidate_schema_version"`
	Status                  string          `json:"status"`
	HoldReason              *string         `json:"hold_reason"`
	ExactSignatureHash      *string         `json:"exact_signature_hash"`
	SignaturePayload        []byte          `json:"signature_payload"`
	ConflictBucketKeys      json.RawMessage `json:"conflict_bucket_keys"`
}

func (q *Queries) UpsertDiscoveryCandidate(ctx context.Context, arg UpsertDiscoveryCandidateParams) (DiscoveryCandidate, error) {
	row := q.db.QueryRow(ctx, upsertDiscoveryCandidate,
		arg.ProjectID,
		arg.ShadowRunID,
		arg.SourceKind,
		arg.SourceObjectType,
		arg.SourceObjectID,
		arg.TargetKind,
		arg.NormalizedTargetSet,
		arg.IssueOrHypothesisFamily,
		arg.ChangeFamily,
		arg.ProposedMutations,
		arg.ArtifactIntent,
		arg.IntendedSlugOrCanonical,
		arg.TopicEntityIdentity,
		arg.AudienceIdentity,
		arg.PrimarySuccessMetric,
		arg.VerificationMode,
		arg.EvidenceIds,
		arg.EvidenceFingerprint,
		arg.SuggestedOwner,
		arg.Confidence,
		arg.CandidateSchemaVersion,
		arg.Status,
		arg.HoldReason,
		arg.ExactSignatureHash,
		arg.SignaturePayload,
		arg.ConflictBucketKeys,
	)
	var i DiscoveryCandidate
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ShadowRunID,
		&i.SourceKind,
		&i.SourceObjectType,
		&i.SourceObjectID,
		&i.TargetKind,
		&i.NormalizedTargetSet,
		&i.IssueOrHypothesisFamily,
		&i.ChangeFamily,
		&i.ProposedMutations,
		&i.ArtifactIntent,
		&i.IntendedSlugOrCanonical,
		&i.TopicEntityIdentity,
		&i.AudienceIdentity,
		&i.PrimarySuccessMetric,
		&i.VerificationMode,
		&i.EvidenceIds,
		&i.EvidenceFingerprint,
		&i.SuggestedOwner,
		&i.Confidence,
		&i.CandidateSchemaVersion,
		&i.Status,
		&i.HoldReason,
		&i.ExactSignatureHash,
		&i.SignaturePayload,
		&i.ConflictBucketKeys,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CandidateVersion,
	)
	return i, err
}

const upsertShadowWorkSignature = `-- name: UpsertShadowWorkSignature :one
insert into work_signature_registry
  (project_id, candidate_id, shadow_run_id, mode, status, active,
   exact_signature_hash, signature_payload, conflict_bucket_keys,
   signature_version, owner, source_object_type, source_object_id)
values
  ($1, $2, $3,
   'shadow', 'shadow_observed', false, $4,
   $5::jsonb, $6::jsonb,
   $7, $8, $9,
   $10)
on conflict (candidate_id, mode) do update set
  shadow_run_id = excluded.shadow_run_id,
  status = 'shadow_observed',
  exact_signature_hash = excluded.exact_signature_hash,
  signature_payload = excluded.signature_payload,
  conflict_bucket_keys = excluded.conflict_bucket_keys,
  signature_version = excluded.signature_version,
  owner = excluded.owner,
  source_object_type = excluded.source_object_type,
  source_object_id = excluded.source_object_id,
  updated_at = now()
returning id, project_id, candidate_id, shadow_run_id, mode, status, active, exact_signature_hash, signature_payload, semantic_fingerprint, conflict_bucket_keys, signature_version, owner, source_object_type, source_object_id, created_at, updated_at, arbitration_decision_id, reserved_work_type, reserved_work_id, evidence_fingerprint
`

type UpsertShadowWorkSignatureParams struct {
	ProjectID          uuid.UUID       `json:"project_id"`
	CandidateID        uuid.UUID       `json:"candidate_id"`
	ShadowRunID        uuid.UUID       `json:"shadow_run_id"`
	ExactSignatureHash string          `json:"exact_signature_hash"`
	SignaturePayload   json.RawMessage `json:"signature_payload"`
	ConflictBucketKeys json.RawMessage `json:"conflict_bucket_keys"`
	SignatureVersion   string          `json:"signature_version"`
	Owner              *string         `json:"owner"`
	SourceObjectType   string          `json:"source_object_type"`
	SourceObjectID     string          `json:"source_object_id"`
}

func (q *Queries) UpsertShadowWorkSignature(ctx context.Context, arg UpsertShadowWorkSignatureParams) (WorkSignatureRegistry, error) {
	row := q.db.QueryRow(ctx, upsertShadowWorkSignature,
		arg.ProjectID,
		arg.CandidateID,
		arg.ShadowRunID,
		arg.ExactSignatureHash,
		arg.SignaturePayload,
		arg.ConflictBucketKeys,
		arg.SignatureVersion,
		arg.Owner,
		arg.SourceObjectType,
		arg.SourceObjectID,
	)
	var i WorkSignatureRegistry
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CandidateID,
		&i.ShadowRunID,
		&i.Mode,
		&i.Status,
		&i.Active,
		&i.ExactSignatureHash,
		&i.SignaturePayload,
		&i.SemanticFingerprint,
		&i.ConflictBucketKeys,
		&i.SignatureVersion,
		&i.Owner,
		&i.SourceObjectType,
		&i.SourceObjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArbitrationDecisionID,
		&i.ReservedWorkType,
		&i.ReservedWorkID,
		&i.EvidenceFingerprint,
	)
	return i, err
}
