// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: evidence.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acquireEvidenceRun = `-- name: AcquireEvidenceRun :one
with acquired as (
insert into evidence_runs (
  id, project_id, source, normalized_target, target_kind, window_start, window_end,
  collection_spec, collection_spec_fingerprint, collection_owner_token, requested_by,
  attempt_number, lease_expires_at, status, started_at
) values (
  $1, $2, $3, $4,
  $5, $6::date, $7::date,
  $8::jsonb, $9,
  $10, $11::jsonb,
  $12, $13, 'running', $14
)
on conflict (
  project_id, source, normalized_target, target_kind,
  (coalesce(window_start, '-infinity'::date)),
  (coalesce(window_end, 'infinity'::date)),
  collection_spec_fingerprint
) do update set
  requested_by = (
    select coalesce(jsonb_agg(requester order by requester), '[]'::jsonb)
    from (
      select distinct jsonb_array_elements_text(evidence_runs.requested_by || excluded.requested_by) as requester
    ) requesters
  ),
  collection_owner_token = case
    when evidence_runs.status in ('failed','partial') or (evidence_runs.status = 'running' and evidence_runs.lease_expires_at <= now())
      then excluded.collection_owner_token else evidence_runs.collection_owner_token end,
  attempt_number = case
    when evidence_runs.status in ('failed','partial') or (evidence_runs.status = 'running' and evidence_runs.lease_expires_at <= now())
      then evidence_runs.attempt_number + 1 else evidence_runs.attempt_number end,
  lease_expires_at = case
    when evidence_runs.status in ('failed','partial') or (evidence_runs.status = 'running' and evidence_runs.lease_expires_at <= now())
      then excluded.lease_expires_at else evidence_runs.lease_expires_at end,
  error_history = case
    when (evidence_runs.status in ('failed','partial') or (evidence_runs.status = 'running' and evidence_runs.lease_expires_at <= now()))
      and evidence_runs.error_summary is not null
      then evidence_runs.error_history || jsonb_build_array(jsonb_build_object('attempt', evidence_runs.attempt_number, 'status', evidence_runs.status, 'error', evidence_runs.error_summary, 'finished_at', evidence_runs.finished_at))
    else evidence_runs.error_history end,
  status = case
    when evidence_runs.status in ('failed','partial') or (evidence_runs.status = 'running' and evidence_runs.lease_expires_at <= now())
      then 'running' else evidence_runs.status end,
  error_summary = case
    when evidence_runs.status in ('failed','partial') or (evidence_runs.status = 'running' and evidence_runs.lease_expires_at <= now())
      then null else evidence_runs.error_summary end,
  finished_at = case
    when evidence_runs.status in ('failed','partial') or (evidence_runs.status = 'running' and evidence_runs.lease_expires_at <= now())
      then null else evidence_runs.finished_at end,
  started_at = case
    when evidence_runs.status in ('failed','partial') or (evidence_runs.status = 'running' and evidence_runs.lease_expires_at <= now())
      then excluded.started_at else evidence_runs.started_at end,
  updated_at = now()
returning evidence_runs.id, evidence_runs.project_id, evidence_runs.source, evidence_runs.normalized_target, evidence_runs.target_kind, evidence_runs.window_start, evidence_runs.window_end, evidence_runs.collection_spec, evidence_runs.collection_spec_fingerprint, evidence_runs.collection_owner_token, evidence_runs.attempt_number, evidence_runs.lease_expires_at, evidence_runs.error_history, evidence_runs.requested_by, evidence_runs.status, evidence_runs.error_summary, evidence_runs.started_at, evidence_runs.finished_at, evidence_runs.created_at, evidence_runs.updated_at
), expired_attempt as (
  update evidence_run_attempts attempt set
    status = 'failed', error_summary = 'collection lease expired before terminalization',
    finished_at = now()
  from acquired
  where attempt.run_id = acquired.id and attempt.project_id = acquired.project_id
    and attempt.attempt_number < acquired.attempt_number and attempt.status = 'running'
  returning attempt.run_id
), ensured_attempt as (
  insert into evidence_run_attempts (
    run_id, project_id, attempt_number, collection_owner_token, status,
    started_at, lease_expires_at
  )
  select id, project_id, attempt_number, collection_owner_token, 'running', started_at, lease_expires_at
  from acquired
  on conflict (run_id, attempt_number) do nothing
  returning run_id
)
select acquired.id, acquired.project_id, acquired.source, acquired.normalized_target, acquired.target_kind, acquired.window_start, acquired.window_end, acquired.collection_spec, acquired.collection_spec_fingerprint, acquired.collection_owner_token, acquired.attempt_number, acquired.lease_expires_at, acquired.error_history, acquired.requested_by, acquired.status, acquired.error_summary, acquired.started_at, acquired.finished_at, acquired.created_at, acquired.updated_at from acquired
left join ensured_attempt on ensured_attempt.run_id = acquired.id
left join expired_attempt on expired_attempt.run_id = acquired.id
limit 1
`

type AcquireEvidenceRunParams struct {
	ID                        uuid.UUID          `json:"id"`
	ProjectID                 uuid.UUID          `json:"project_id"`
	Source                    string             `json:"source"`
	NormalizedTarget          string             `json:"normalized_target"`
	TargetKind                string             `json:"target_kind"`
	WindowStart               pgtype.Date        `json:"window_start"`
	WindowEnd                 pgtype.Date        `json:"window_end"`
	CollectionSpec            json.RawMessage    `json:"collection_spec"`
	CollectionSpecFingerprint string             `json:"collection_spec_fingerprint"`
	CollectionOwnerToken      uuid.UUID          `json:"collection_owner_token"`
	RequestedBy               json.RawMessage    `json:"requested_by"`
	AttemptNumber             int32              `json:"attempt_number"`
	LeaseExpiresAt            pgtype.Timestamptz `json:"lease_expires_at"`
	StartedAt                 pgtype.Timestamptz `json:"started_at"`
}

type AcquireEvidenceRunRow struct {
	ID                        uuid.UUID          `json:"id"`
	ProjectID                 uuid.UUID          `json:"project_id"`
	Source                    string             `json:"source"`
	NormalizedTarget          string             `json:"normalized_target"`
	TargetKind                string             `json:"target_kind"`
	WindowStart               pgtype.Date        `json:"window_start"`
	WindowEnd                 pgtype.Date        `json:"window_end"`
	CollectionSpec            json.RawMessage    `json:"collection_spec"`
	CollectionSpecFingerprint string             `json:"collection_spec_fingerprint"`
	CollectionOwnerToken      uuid.UUID          `json:"collection_owner_token"`
	AttemptNumber             int32              `json:"attempt_number"`
	LeaseExpiresAt            pgtype.Timestamptz `json:"lease_expires_at"`
	ErrorHistory              json.RawMessage    `json:"error_history"`
	RequestedBy               json.RawMessage    `json:"requested_by"`
	Status                    string             `json:"status"`
	ErrorSummary              *string            `json:"error_summary"`
	StartedAt                 pgtype.Timestamptz `json:"started_at"`
	FinishedAt                pgtype.Timestamptz `json:"finished_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) AcquireEvidenceRun(ctx context.Context, arg AcquireEvidenceRunParams) (AcquireEvidenceRunRow, error) {
	row := q.db.QueryRow(ctx, acquireEvidenceRun,
		arg.ID,
		arg.ProjectID,
		arg.Source,
		arg.NormalizedTarget,
		arg.TargetKind,
		arg.WindowStart,
		arg.WindowEnd,
		arg.CollectionSpec,
		arg.CollectionSpecFingerprint,
		arg.CollectionOwnerToken,
		arg.RequestedBy,
		arg.AttemptNumber,
		arg.LeaseExpiresAt,
		arg.StartedAt,
	)
	var i AcquireEvidenceRunRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Source,
		&i.NormalizedTarget,
		&i.TargetKind,
		&i.WindowStart,
		&i.WindowEnd,
		&i.CollectionSpec,
		&i.CollectionSpecFingerprint,
		&i.CollectionOwnerToken,
		&i.AttemptNumber,
		&i.LeaseExpiresAt,
		&i.ErrorHistory,
		&i.RequestedBy,
		&i.Status,
		&i.ErrorSummary,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEvidenceObservation = `-- name: CreateEvidenceObservation :one
insert into evidence_observations (
  id, project_id, run_id, attempt_number, source, source_observation_key, normalized_target, target_kind,
  evidence_state, facts, raw_snapshot, confidence, completeness, provider, model,
  provider_version, prompt_version, call_status, prompt_tokens, completion_tokens, total_tokens, cost_usd,
  privacy_state, permission_state, error_code, observed_at, window_start, window_end
) values (
  $1, $2, $3, $4, $5,
  $6, $7, $8,
  $9, $10::jsonb, $11::jsonb,
  $12, $13, $14, $15,
  $16, $17, $18, $19,
  $20, $21, $22,
  $23, $24, $25,
  $26, $27::date, $28::date
)
on conflict do nothing
returning id, project_id, run_id, attempt_number, source, source_observation_key, normalized_target, target_kind, evidence_state, facts, raw_snapshot, confidence, completeness, provider, model, provider_version, prompt_version, call_status, prompt_tokens, completion_tokens, total_tokens, cost_usd, privacy_state, permission_state, error_code, observed_at, window_start, window_end, created_at
`

type CreateEvidenceObservationParams struct {
	ID                   uuid.UUID          `json:"id"`
	ProjectID            uuid.UUID          `json:"project_id"`
	RunID                uuid.UUID          `json:"run_id"`
	AttemptNumber        int32              `json:"attempt_number"`
	Source               string             `json:"source"`
	SourceObservationKey string             `json:"source_observation_key"`
	NormalizedTarget     string             `json:"normalized_target"`
	TargetKind           string             `json:"target_kind"`
	EvidenceState        string             `json:"evidence_state"`
	Facts                json.RawMessage    `json:"facts"`
	RawSnapshot          json.RawMessage    `json:"raw_snapshot"`
	Confidence           pgtype.Numeric     `json:"confidence"`
	Completeness         pgtype.Numeric     `json:"completeness"`
	Provider             *string            `json:"provider"`
	Model                *string            `json:"model"`
	ProviderVersion      *string            `json:"provider_version"`
	PromptVersion        *string            `json:"prompt_version"`
	CallStatus           *string            `json:"call_status"`
	PromptTokens         int64              `json:"prompt_tokens"`
	CompletionTokens     int64              `json:"completion_tokens"`
	TotalTokens          int64              `json:"total_tokens"`
	CostUsd              pgtype.Numeric     `json:"cost_usd"`
	PrivacyState         string             `json:"privacy_state"`
	PermissionState      string             `json:"permission_state"`
	ErrorCode            *string            `json:"error_code"`
	ObservedAt           pgtype.Timestamptz `json:"observed_at"`
	WindowStart          pgtype.Date        `json:"window_start"`
	WindowEnd            pgtype.Date        `json:"window_end"`
}

func (q *Queries) CreateEvidenceObservation(ctx context.Context, arg CreateEvidenceObservationParams) (EvidenceObservation, error) {
	row := q.db.QueryRow(ctx, createEvidenceObservation,
		arg.ID,
		arg.ProjectID,
		arg.RunID,
		arg.AttemptNumber,
		arg.Source,
		arg.SourceObservationKey,
		arg.NormalizedTarget,
		arg.TargetKind,
		arg.EvidenceState,
		arg.Facts,
		arg.RawSnapshot,
		arg.Confidence,
		arg.Completeness,
		arg.Provider,
		arg.Model,
		arg.ProviderVersion,
		arg.PromptVersion,
		arg.CallStatus,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.CostUsd,
		arg.PrivacyState,
		arg.PermissionState,
		arg.ErrorCode,
		arg.ObservedAt,
		arg.WindowStart,
		arg.WindowEnd,
	)
	var i EvidenceObservation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RunID,
		&i.AttemptNumber,
		&i.Source,
		&i.SourceObservationKey,
		&i.NormalizedTarget,
		&i.TargetKind,
		&i.EvidenceState,
		&i.Facts,
		&i.RawSnapshot,
		&i.Confidence,
		&i.Completeness,
		&i.Provider,
		&i.Model,
		&i.ProviderVersion,
		&i.PromptVersion,
		&i.CallStatus,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.CostUsd,
		&i.PrivacyState,
		&i.PermissionState,
		&i.ErrorCode,
		&i.ObservedAt,
		&i.WindowStart,
		&i.WindowEnd,
		&i.CreatedAt,
	)
	return i, err
}

const finishEvidenceRun = `-- name: FinishEvidenceRun :one
with locked_run as (
  select run.id, run.project_id, run.source, run.normalized_target, run.target_kind, run.window_start, run.window_end, run.collection_spec, run.collection_spec_fingerprint, run.collection_owner_token, run.attempt_number, run.lease_expires_at, run.error_history, run.requested_by, run.status, run.error_summary, run.started_at, run.finished_at, run.created_at, run.updated_at from evidence_runs run
  where run.id = $1 and run.project_id = $2
  for update
), finished_attempt as (
  update evidence_run_attempts attempt set
    status = $3, error_summary = $4,
    finished_at = $5
  from locked_run
  where attempt.run_id = locked_run.id and attempt.project_id = locked_run.project_id
    and attempt.attempt_number = $6
    and attempt.collection_owner_token = $7
    and attempt.status = 'running'
  returning attempt.run_id, attempt.project_id, attempt.attempt_number, attempt.collection_owner_token, attempt.status, attempt.error_summary, attempt.started_at, attempt.lease_expires_at, attempt.finished_at, attempt.created_at
), finished_run as (
  update evidence_runs run set
    status = finished_attempt.status, error_summary = finished_attempt.error_summary,
    finished_at = finished_attempt.finished_at, updated_at = now()
  from finished_attempt
  where run.id = finished_attempt.run_id and run.project_id = finished_attempt.project_id
    and run.attempt_number = finished_attempt.attempt_number
    and run.collection_owner_token = finished_attempt.collection_owner_token
  returning run.id, run.project_id, run.source, run.normalized_target, run.target_kind, run.window_start, run.window_end, run.collection_spec, run.collection_spec_fingerprint, run.collection_owner_token, run.attempt_number, run.lease_expires_at, run.error_history, run.requested_by, run.status, run.error_summary, run.started_at, run.finished_at, run.created_at, run.updated_at
)
select id, project_id, source, normalized_target, target_kind, window_start, window_end, collection_spec, collection_spec_fingerprint, collection_owner_token, attempt_number, lease_expires_at, error_history, requested_by, status, error_summary, started_at, finished_at, created_at, updated_at from finished_run
`

type FinishEvidenceRunParams struct {
	ID                   uuid.UUID          `json:"id"`
	ProjectID            uuid.UUID          `json:"project_id"`
	Status               string             `json:"status"`
	ErrorSummary         *string            `json:"error_summary"`
	FinishedAt           pgtype.Timestamptz `json:"finished_at"`
	AttemptNumber        int32              `json:"attempt_number"`
	CollectionOwnerToken uuid.UUID          `json:"collection_owner_token"`
}

type FinishEvidenceRunRow struct {
	ID                        uuid.UUID          `json:"id"`
	ProjectID                 uuid.UUID          `json:"project_id"`
	Source                    string             `json:"source"`
	NormalizedTarget          string             `json:"normalized_target"`
	TargetKind                string             `json:"target_kind"`
	WindowStart               pgtype.Date        `json:"window_start"`
	WindowEnd                 pgtype.Date        `json:"window_end"`
	CollectionSpec            json.RawMessage    `json:"collection_spec"`
	CollectionSpecFingerprint string             `json:"collection_spec_fingerprint"`
	CollectionOwnerToken      uuid.UUID          `json:"collection_owner_token"`
	AttemptNumber             int32              `json:"attempt_number"`
	LeaseExpiresAt            pgtype.Timestamptz `json:"lease_expires_at"`
	ErrorHistory              json.RawMessage    `json:"error_history"`
	RequestedBy               json.RawMessage    `json:"requested_by"`
	Status                    string             `json:"status"`
	ErrorSummary              *string            `json:"error_summary"`
	StartedAt                 pgtype.Timestamptz `json:"started_at"`
	FinishedAt                pgtype.Timestamptz `json:"finished_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FinishEvidenceRun(ctx context.Context, arg FinishEvidenceRunParams) (FinishEvidenceRunRow, error) {
	row := q.db.QueryRow(ctx, finishEvidenceRun,
		arg.ID,
		arg.ProjectID,
		arg.Status,
		arg.ErrorSummary,
		arg.FinishedAt,
		arg.AttemptNumber,
		arg.CollectionOwnerToken,
	)
	var i FinishEvidenceRunRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Source,
		&i.NormalizedTarget,
		&i.TargetKind,
		&i.WindowStart,
		&i.WindowEnd,
		&i.CollectionSpec,
		&i.CollectionSpecFingerprint,
		&i.CollectionOwnerToken,
		&i.AttemptNumber,
		&i.LeaseExpiresAt,
		&i.ErrorHistory,
		&i.RequestedBy,
		&i.Status,
		&i.ErrorSummary,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEvidenceObservation = `-- name: GetEvidenceObservation :one
select id, project_id, run_id, attempt_number, source, source_observation_key, normalized_target, target_kind, evidence_state, facts, raw_snapshot, confidence, completeness, provider, model, provider_version, prompt_version, call_status, prompt_tokens, completion_tokens, total_tokens, cost_usd, privacy_state, permission_state, error_code, observed_at, window_start, window_end, created_at from evidence_observations
where project_id = $1 and run_id = $2
  and attempt_number = $3
  and source_observation_key = $4
`

type GetEvidenceObservationParams struct {
	ProjectID            uuid.UUID `json:"project_id"`
	RunID                uuid.UUID `json:"run_id"`
	AttemptNumber        int32     `json:"attempt_number"`
	SourceObservationKey string    `json:"source_observation_key"`
}

func (q *Queries) GetEvidenceObservation(ctx context.Context, arg GetEvidenceObservationParams) (EvidenceObservation, error) {
	row := q.db.QueryRow(ctx, getEvidenceObservation,
		arg.ProjectID,
		arg.RunID,
		arg.AttemptNumber,
		arg.SourceObservationKey,
	)
	var i EvidenceObservation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RunID,
		&i.AttemptNumber,
		&i.Source,
		&i.SourceObservationKey,
		&i.NormalizedTarget,
		&i.TargetKind,
		&i.EvidenceState,
		&i.Facts,
		&i.RawSnapshot,
		&i.Confidence,
		&i.Completeness,
		&i.Provider,
		&i.Model,
		&i.ProviderVersion,
		&i.PromptVersion,
		&i.CallStatus,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.CostUsd,
		&i.PrivacyState,
		&i.PermissionState,
		&i.ErrorCode,
		&i.ObservedAt,
		&i.WindowStart,
		&i.WindowEnd,
		&i.CreatedAt,
	)
	return i, err
}

const getEvidenceRun = `-- name: GetEvidenceRun :one
select id, project_id, source, normalized_target, target_kind, window_start, window_end, collection_spec, collection_spec_fingerprint, collection_owner_token, attempt_number, lease_expires_at, error_history, requested_by, status, error_summary, started_at, finished_at, created_at, updated_at from evidence_runs where id = $1 and project_id = $2
`

type GetEvidenceRunParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetEvidenceRun(ctx context.Context, arg GetEvidenceRunParams) (EvidenceRun, error) {
	row := q.db.QueryRow(ctx, getEvidenceRun, arg.ID, arg.ProjectID)
	var i EvidenceRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Source,
		&i.NormalizedTarget,
		&i.TargetKind,
		&i.WindowStart,
		&i.WindowEnd,
		&i.CollectionSpec,
		&i.CollectionSpecFingerprint,
		&i.CollectionOwnerToken,
		&i.AttemptNumber,
		&i.LeaseExpiresAt,
		&i.ErrorHistory,
		&i.RequestedBy,
		&i.Status,
		&i.ErrorSummary,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkEvidenceConsumption = `-- name: LinkEvidenceConsumption :one
insert into evidence_consumptions (project_id, evidence_run_id, attempt_number, consumer_type, consumer_id)
values ($1, $2, $3, $4, $5)
on conflict (project_id, evidence_run_id, attempt_number, consumer_type, consumer_id) do update
set consumer_id = excluded.consumer_id
returning id, project_id, evidence_run_id, attempt_number, consumer_type, consumer_id, created_at
`

type LinkEvidenceConsumptionParams struct {
	ProjectID     uuid.UUID `json:"project_id"`
	EvidenceRunID uuid.UUID `json:"evidence_run_id"`
	AttemptNumber int32     `json:"attempt_number"`
	ConsumerType  string    `json:"consumer_type"`
	ConsumerID    uuid.UUID `json:"consumer_id"`
}

func (q *Queries) LinkEvidenceConsumption(ctx context.Context, arg LinkEvidenceConsumptionParams) (EvidenceConsumption, error) {
	row := q.db.QueryRow(ctx, linkEvidenceConsumption,
		arg.ProjectID,
		arg.EvidenceRunID,
		arg.AttemptNumber,
		arg.ConsumerType,
		arg.ConsumerID,
	)
	var i EvidenceConsumption
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EvidenceRunID,
		&i.AttemptNumber,
		&i.ConsumerType,
		&i.ConsumerID,
		&i.CreatedAt,
	)
	return i, err
}

const listEvidenceObservations = `-- name: ListEvidenceObservations :many
select id, project_id, run_id, attempt_number, source, source_observation_key, normalized_target, target_kind, evidence_state, facts, raw_snapshot, confidence, completeness, provider, model, provider_version, prompt_version, call_status, prompt_tokens, completion_tokens, total_tokens, cost_usd, privacy_state, permission_state, error_code, observed_at, window_start, window_end, created_at from evidence_observations
where project_id = $1 and run_id = $2
  and attempt_number = $3
order by created_at, id
`

type ListEvidenceObservationsParams struct {
	ProjectID     uuid.UUID `json:"project_id"`
	RunID         uuid.UUID `json:"run_id"`
	AttemptNumber int32     `json:"attempt_number"`
}

func (q *Queries) ListEvidenceObservations(ctx context.Context, arg ListEvidenceObservationsParams) ([]EvidenceObservation, error) {
	rows, err := q.db.Query(ctx, listEvidenceObservations, arg.ProjectID, arg.RunID, arg.AttemptNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EvidenceObservation
	for rows.Next() {
		var i EvidenceObservation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RunID,
			&i.AttemptNumber,
			&i.Source,
			&i.SourceObservationKey,
			&i.NormalizedTarget,
			&i.TargetKind,
			&i.EvidenceState,
			&i.Facts,
			&i.RawSnapshot,
			&i.Confidence,
			&i.Completeness,
			&i.Provider,
			&i.Model,
			&i.ProviderVersion,
			&i.PromptVersion,
			&i.CallStatus,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.CostUsd,
			&i.PrivacyState,
			&i.PermissionState,
			&i.ErrorCode,
			&i.ObservedAt,
			&i.WindowStart,
			&i.WindowEnd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceRuns = `-- name: ListEvidenceRuns :many
select id, project_id, source, normalized_target, target_kind, window_start, window_end, collection_spec, collection_spec_fingerprint, collection_owner_token, attempt_number, lease_expires_at, error_history, requested_by, status, error_summary, started_at, finished_at, created_at, updated_at from evidence_runs where project_id = $1
order by created_at desc limit $2
`

type ListEvidenceRunsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	LimitRows int32     `json:"limit_rows"`
}

func (q *Queries) ListEvidenceRuns(ctx context.Context, arg ListEvidenceRunsParams) ([]EvidenceRun, error) {
	rows, err := q.db.Query(ctx, listEvidenceRuns, arg.ProjectID, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EvidenceRun
	for rows.Next() {
		var i EvidenceRun
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Source,
			&i.NormalizedTarget,
			&i.TargetKind,
			&i.WindowStart,
			&i.WindowEnd,
			&i.CollectionSpec,
			&i.CollectionSpecFingerprint,
			&i.CollectionOwnerToken,
			&i.AttemptNumber,
			&i.LeaseExpiresAt,
			&i.ErrorHistory,
			&i.RequestedBy,
			&i.Status,
			&i.ErrorSummary,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceRunsForConsumers = `-- name: ListEvidenceRunsForConsumers :many
select distinct run.id, run.project_id, run.source, run.normalized_target, run.target_kind, run.window_start, run.window_end, run.collection_spec, run.collection_spec_fingerprint, run.collection_owner_token, run.attempt_number, run.lease_expires_at, run.error_history, run.requested_by, run.status, run.error_summary, run.started_at, run.finished_at, run.created_at, run.updated_at, attempt.attempt_number as consumed_attempt_number,
  attempt.status as consumed_status, attempt.error_summary as consumed_error_summary,
  attempt.started_at as consumed_started_at, attempt.finished_at as consumed_finished_at
from evidence_consumptions consumption
join evidence_runs run on run.id = consumption.evidence_run_id and run.project_id = consumption.project_id
join evidence_run_attempts attempt
  on attempt.run_id = consumption.evidence_run_id and attempt.project_id = consumption.project_id
 and attempt.attempt_number = consumption.attempt_number
where consumption.project_id = $1
  and consumption.consumer_type = $2
  and consumption.consumer_id = any($3::uuid[])
order by run.created_at, run.id
`

type ListEvidenceRunsForConsumersParams struct {
	ProjectID    uuid.UUID   `json:"project_id"`
	ConsumerType string      `json:"consumer_type"`
	ConsumerIds  []uuid.UUID `json:"consumer_ids"`
}

type ListEvidenceRunsForConsumersRow struct {
	ID                        uuid.UUID          `json:"id"`
	ProjectID                 uuid.UUID          `json:"project_id"`
	Source                    string             `json:"source"`
	NormalizedTarget          string             `json:"normalized_target"`
	TargetKind                string             `json:"target_kind"`
	WindowStart               pgtype.Date        `json:"window_start"`
	WindowEnd                 pgtype.Date        `json:"window_end"`
	CollectionSpec            json.RawMessage    `json:"collection_spec"`
	CollectionSpecFingerprint string             `json:"collection_spec_fingerprint"`
	CollectionOwnerToken      uuid.UUID          `json:"collection_owner_token"`
	AttemptNumber             int32              `json:"attempt_number"`
	LeaseExpiresAt            pgtype.Timestamptz `json:"lease_expires_at"`
	ErrorHistory              json.RawMessage    `json:"error_history"`
	RequestedBy               json.RawMessage    `json:"requested_by"`
	Status                    string             `json:"status"`
	ErrorSummary              *string            `json:"error_summary"`
	StartedAt                 pgtype.Timestamptz `json:"started_at"`
	FinishedAt                pgtype.Timestamptz `json:"finished_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	ConsumedAttemptNumber     int32              `json:"consumed_attempt_number"`
	ConsumedStatus            string             `json:"consumed_status"`
	ConsumedErrorSummary      *string            `json:"consumed_error_summary"`
	ConsumedStartedAt         pgtype.Timestamptz `json:"consumed_started_at"`
	ConsumedFinishedAt        pgtype.Timestamptz `json:"consumed_finished_at"`
}

func (q *Queries) ListEvidenceRunsForConsumers(ctx context.Context, arg ListEvidenceRunsForConsumersParams) ([]ListEvidenceRunsForConsumersRow, error) {
	rows, err := q.db.Query(ctx, listEvidenceRunsForConsumers, arg.ProjectID, arg.ConsumerType, arg.ConsumerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEvidenceRunsForConsumersRow
	for rows.Next() {
		var i ListEvidenceRunsForConsumersRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Source,
			&i.NormalizedTarget,
			&i.TargetKind,
			&i.WindowStart,
			&i.WindowEnd,
			&i.CollectionSpec,
			&i.CollectionSpecFingerprint,
			&i.CollectionOwnerToken,
			&i.AttemptNumber,
			&i.LeaseExpiresAt,
			&i.ErrorHistory,
			&i.RequestedBy,
			&i.Status,
			&i.ErrorSummary,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConsumedAttemptNumber,
			&i.ConsumedStatus,
			&i.ConsumedErrorSummary,
			&i.ConsumedStartedAt,
			&i.ConsumedFinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
