// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: geo.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const finishGEORun = `-- name: FinishGEORun :one
update geo_runs set
  status = $3,
  finished_at = $4,
  output = $5,
  error = $6,
  cost_usd = $7
where id = $1 and project_id = $2
returning id, project_id, agent, status, provider, started_at, finished_at, input, output, error, cost_usd
`

type FinishGEORunParams struct {
	ID         uuid.UUID          `json:"id"`
	ProjectID  uuid.UUID          `json:"project_id"`
	Status     string             `json:"status"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	Output     json.RawMessage    `json:"output"`
	Error      *string            `json:"error"`
	CostUsd    pgtype.Numeric     `json:"cost_usd"`
}

func (q *Queries) FinishGEORun(ctx context.Context, arg FinishGEORunParams) (GeoRun, error) {
	row := q.db.QueryRow(ctx, finishGEORun,
		arg.ID,
		arg.ProjectID,
		arg.Status,
		arg.FinishedAt,
		arg.Output,
		arg.Error,
		arg.CostUsd,
	)
	var i GeoRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Agent,
		&i.Status,
		&i.Provider,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Input,
		&i.Output,
		&i.Error,
		&i.CostUsd,
	)
	return i, err
}

const listGEORuns = `-- name: ListGEORuns :many
select id, project_id, agent, status, provider, started_at, finished_at, input, output, error, cost_usd from geo_runs
where project_id = $1
  and ($2::text = '' or agent = $2)
  and ($3::text = '' or status = $3)
  and ($4::timestamptz is null or started_at < $4)
order by started_at desc
limit $5
`

type ListGEORunsParams struct {
	ProjectID       uuid.UUID          `json:"project_id"`
	Agent           string             `json:"agent"`
	Status          string             `json:"status"`
	CursorStartedAt pgtype.Timestamptz `json:"cursor_started_at"`
	LimitRows       int32              `json:"limit_rows"`
}

func (q *Queries) ListGEORuns(ctx context.Context, arg ListGEORunsParams) ([]GeoRun, error) {
	rows, err := q.db.Query(ctx, listGEORuns,
		arg.ProjectID,
		arg.Agent,
		arg.Status,
		arg.CursorStartedAt,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GeoRun
	for rows.Next() {
		var i GeoRun
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Agent,
			&i.Status,
			&i.Provider,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Input,
			&i.Output,
			&i.Error,
			&i.CostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestAICrawlerAccessSnapshots = `-- name: ListLatestAICrawlerAccessSnapshots :many
select s.id, s.project_id, s.run_id, s.page_url, s.normalized_page_url, s.target_user_agent, s.probe_user_agent, s.evidence_type, s.robots_state, s.http_status, s.access_state, s.confidence, s.inferred, s.meta_robots_state, s.sitemap_state, s.body_extractable, s.raw_details, s.checked_at
from ai_crawler_access_snapshots s
join geo_runs r on r.id = s.run_id
where s.project_id = $1
  and r.started_at = (
    select max(started_at)
    from geo_runs
    where project_id = $1 and agent = 'geo_crawler_audit'
  )
order by s.normalized_page_url asc, s.target_user_agent asc, s.evidence_type asc
`

func (q *Queries) ListLatestAICrawlerAccessSnapshots(ctx context.Context, projectID uuid.UUID) ([]AiCrawlerAccessSnapshot, error) {
	rows, err := q.db.Query(ctx, listLatestAICrawlerAccessSnapshots, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiCrawlerAccessSnapshot
	for rows.Next() {
		var i AiCrawlerAccessSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RunID,
			&i.PageUrl,
			&i.NormalizedPageUrl,
			&i.TargetUserAgent,
			&i.ProbeUserAgent,
			&i.EvidenceType,
			&i.RobotsState,
			&i.HttpStatus,
			&i.AccessState,
			&i.Confidence,
			&i.Inferred,
			&i.MetaRobotsState,
			&i.SitemapState,
			&i.BodyExtractable,
			&i.RawDetails,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startGEORun = `-- name: StartGEORun :one
insert into geo_runs (project_id, agent, status, provider, started_at, input)
values ($1, $2, 'degraded', $3, $4, $5)
returning id, project_id, agent, status, provider, started_at, finished_at, input, output, error, cost_usd
`

type StartGEORunParams struct {
	ProjectID uuid.UUID          `json:"project_id"`
	Agent     string             `json:"agent"`
	Provider  string             `json:"provider"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	Input     json.RawMessage    `json:"input"`
}

func (q *Queries) StartGEORun(ctx context.Context, arg StartGEORunParams) (GeoRun, error) {
	row := q.db.QueryRow(ctx, startGEORun,
		arg.ProjectID,
		arg.Agent,
		arg.Provider,
		arg.StartedAt,
		arg.Input,
	)
	var i GeoRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Agent,
		&i.Status,
		&i.Provider,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Input,
		&i.Output,
		&i.Error,
		&i.CostUsd,
	)
	return i, err
}

const upsertAICrawlerAccessSnapshot = `-- name: UpsertAICrawlerAccessSnapshot :one
insert into ai_crawler_access_snapshots
  (project_id, run_id, page_url, normalized_page_url, target_user_agent, probe_user_agent,
   evidence_type, robots_state, http_status, access_state, confidence, inferred,
   meta_robots_state, sitemap_state, body_extractable, raw_details, checked_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
on conflict (project_id, run_id, normalized_page_url, target_user_agent, evidence_type) do update set
  page_url = excluded.page_url,
  probe_user_agent = excluded.probe_user_agent,
  robots_state = excluded.robots_state,
  http_status = excluded.http_status,
  access_state = excluded.access_state,
  confidence = excluded.confidence,
  inferred = excluded.inferred,
  meta_robots_state = excluded.meta_robots_state,
  sitemap_state = excluded.sitemap_state,
  body_extractable = excluded.body_extractable,
  raw_details = excluded.raw_details,
  checked_at = excluded.checked_at
returning id, project_id, run_id, page_url, normalized_page_url, target_user_agent, probe_user_agent, evidence_type, robots_state, http_status, access_state, confidence, inferred, meta_robots_state, sitemap_state, body_extractable, raw_details, checked_at
`

type UpsertAICrawlerAccessSnapshotParams struct {
	ProjectID         uuid.UUID          `json:"project_id"`
	RunID             uuid.UUID          `json:"run_id"`
	PageUrl           string             `json:"page_url"`
	NormalizedPageUrl string             `json:"normalized_page_url"`
	TargetUserAgent   string             `json:"target_user_agent"`
	ProbeUserAgent    string             `json:"probe_user_agent"`
	EvidenceType      string             `json:"evidence_type"`
	RobotsState       string             `json:"robots_state"`
	HttpStatus        *int32             `json:"http_status"`
	AccessState       string             `json:"access_state"`
	Confidence        string             `json:"confidence"`
	Inferred          bool               `json:"inferred"`
	MetaRobotsState   *string            `json:"meta_robots_state"`
	SitemapState      *string            `json:"sitemap_state"`
	BodyExtractable   bool               `json:"body_extractable"`
	RawDetails        json.RawMessage    `json:"raw_details"`
	CheckedAt         pgtype.Timestamptz `json:"checked_at"`
}

func (q *Queries) UpsertAICrawlerAccessSnapshot(ctx context.Context, arg UpsertAICrawlerAccessSnapshotParams) (AiCrawlerAccessSnapshot, error) {
	row := q.db.QueryRow(ctx, upsertAICrawlerAccessSnapshot,
		arg.ProjectID,
		arg.RunID,
		arg.PageUrl,
		arg.NormalizedPageUrl,
		arg.TargetUserAgent,
		arg.ProbeUserAgent,
		arg.EvidenceType,
		arg.RobotsState,
		arg.HttpStatus,
		arg.AccessState,
		arg.Confidence,
		arg.Inferred,
		arg.MetaRobotsState,
		arg.SitemapState,
		arg.BodyExtractable,
		arg.RawDetails,
		arg.CheckedAt,
	)
	var i AiCrawlerAccessSnapshot
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RunID,
		&i.PageUrl,
		&i.NormalizedPageUrl,
		&i.TargetUserAgent,
		&i.ProbeUserAgent,
		&i.EvidenceType,
		&i.RobotsState,
		&i.HttpStatus,
		&i.AccessState,
		&i.Confidence,
		&i.Inferred,
		&i.MetaRobotsState,
		&i.SitemapState,
		&i.BodyExtractable,
		&i.RawDetails,
		&i.CheckedAt,
	)
	return i, err
}

const upsertCrawlerAccessOpportunity = `-- name: UpsertCrawlerAccessOpportunity :one
with updated as (
  update seo_opportunities so set
    priority_score = $4,
    confidence = $5,
    page_url = $6,
    normalized_page_url = $7,
    evidence = so.evidence || $8,
    recommended_action = $9,
    expected_impact = $10,
    effort = $11,
    risk_level = $12,
    updated_at = now()
  where so.project_id = $1
    and so.type = $2
    and so.status in ('open','accepted','converted')
    and so.normalized_page_url = $7
    and coalesce(so.query, '') = ''
  returning id, project_id, type, status, priority_score, confidence, page_url, normalized_page_url, article_id, topic_id, query, evidence, recommended_action, expected_impact, effort, risk_level, created_by_run_id, created_at, updated_at
), inserted as (
  insert into seo_opportunities
    (project_id, type, status, priority_score, confidence, page_url, normalized_page_url,
     query, evidence, recommended_action, expected_impact, effort, risk_level, created_by_run_id)
  select $1, $2, $3, $4, $5, $6, $7, null, $8, $9, $10, $11, $12, null
  where not exists (select 1 from updated)
  returning id, project_id, type, status, priority_score, confidence, page_url, normalized_page_url, article_id, topic_id, query, evidence, recommended_action, expected_impact, effort, risk_level, created_by_run_id, created_at, updated_at
)
select id, project_id, type, status, priority_score, confidence, page_url, normalized_page_url, article_id, topic_id, query, evidence, recommended_action, expected_impact, effort, risk_level, created_by_run_id, created_at, updated_at from updated
union all
select id, project_id, type, status, priority_score, confidence, page_url, normalized_page_url, article_id, topic_id, query, evidence, recommended_action, expected_impact, effort, risk_level, created_by_run_id, created_at, updated_at from inserted
`

type UpsertCrawlerAccessOpportunityParams struct {
	ProjectID         uuid.UUID       `json:"project_id"`
	Type              string          `json:"type"`
	Status            string          `json:"status"`
	PriorityScore     pgtype.Numeric  `json:"priority_score"`
	Confidence        pgtype.Numeric  `json:"confidence"`
	PageUrl           *string         `json:"page_url"`
	NormalizedPageUrl string          `json:"normalized_page_url"`
	Evidence          json.RawMessage `json:"evidence"`
	RecommendedAction *string         `json:"recommended_action"`
	ExpectedImpact    *string         `json:"expected_impact"`
	Effort            int32           `json:"effort"`
	RiskLevel         string          `json:"risk_level"`
}

type UpsertCrawlerAccessOpportunityRow struct {
	ID                uuid.UUID          `json:"id"`
	ProjectID         uuid.UUID          `json:"project_id"`
	Type              string             `json:"type"`
	Status            string             `json:"status"`
	PriorityScore     pgtype.Numeric     `json:"priority_score"`
	Confidence        pgtype.Numeric     `json:"confidence"`
	PageUrl           *string            `json:"page_url"`
	NormalizedPageUrl string             `json:"normalized_page_url"`
	ArticleID         pgtype.UUID        `json:"article_id"`
	TopicID           pgtype.UUID        `json:"topic_id"`
	Query             *string            `json:"query"`
	Evidence          json.RawMessage    `json:"evidence"`
	RecommendedAction *string            `json:"recommended_action"`
	ExpectedImpact    *string            `json:"expected_impact"`
	Effort            int32              `json:"effort"`
	RiskLevel         string             `json:"risk_level"`
	CreatedByRunID    pgtype.UUID        `json:"created_by_run_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertCrawlerAccessOpportunity(ctx context.Context, arg UpsertCrawlerAccessOpportunityParams) (UpsertCrawlerAccessOpportunityRow, error) {
	row := q.db.QueryRow(ctx, upsertCrawlerAccessOpportunity,
		arg.ProjectID,
		arg.Type,
		arg.Status,
		arg.PriorityScore,
		arg.Confidence,
		arg.PageUrl,
		arg.NormalizedPageUrl,
		arg.Evidence,
		arg.RecommendedAction,
		arg.ExpectedImpact,
		arg.Effort,
		arg.RiskLevel,
	)
	var i UpsertCrawlerAccessOpportunityRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Status,
		&i.PriorityScore,
		&i.Confidence,
		&i.PageUrl,
		&i.NormalizedPageUrl,
		&i.ArticleID,
		&i.TopicID,
		&i.Query,
		&i.Evidence,
		&i.RecommendedAction,
		&i.ExpectedImpact,
		&i.Effort,
		&i.RiskLevel,
		&i.CreatedByRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
