// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: growth_radar.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGrowthSearchEvidence = `-- name: CreateGrowthSearchEvidence :one
insert into growth_search_evidence (
  project_id, normalized_query, request_hash, result_set_hash, provider,
  provider_order_not_rank, results, synthetic, trigger_kind, request_cost_usd,
  fetched_at, expires_at
) values (
  $1, $2, $3, $4, $5,
  true, $6, $7, $8, $9,
  $10, $11
)
returning id, project_id, normalized_query, request_hash, result_set_hash, provider, provider_order_not_rank, results, synthetic, trigger_kind, request_cost_usd, fetched_at, expires_at, created_at
`

type CreateGrowthSearchEvidenceParams struct {
	ProjectID       uuid.UUID          `json:"project_id"`
	NormalizedQuery string             `json:"normalized_query"`
	RequestHash     string             `json:"request_hash"`
	ResultSetHash   string             `json:"result_set_hash"`
	Provider        string             `json:"provider"`
	Results         json.RawMessage    `json:"results"`
	Synthetic       bool               `json:"synthetic"`
	TriggerKind     string             `json:"trigger_kind"`
	RequestCostUsd  pgtype.Numeric     `json:"request_cost_usd"`
	FetchedAt       pgtype.Timestamptz `json:"fetched_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateGrowthSearchEvidence(ctx context.Context, arg CreateGrowthSearchEvidenceParams) (GrowthSearchEvidence, error) {
	row := q.db.QueryRow(ctx, createGrowthSearchEvidence,
		arg.ProjectID,
		arg.NormalizedQuery,
		arg.RequestHash,
		arg.ResultSetHash,
		arg.Provider,
		arg.Results,
		arg.Synthetic,
		arg.TriggerKind,
		arg.RequestCostUsd,
		arg.FetchedAt,
		arg.ExpiresAt,
	)
	var i GrowthSearchEvidence
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.NormalizedQuery,
		&i.RequestHash,
		&i.ResultSetHash,
		&i.Provider,
		&i.ProviderOrderNotRank,
		&i.Results,
		&i.Synthetic,
		&i.TriggerKind,
		&i.RequestCostUsd,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCachedGrowthSearchEvidence = `-- name: GetCachedGrowthSearchEvidence :one
select id, project_id, normalized_query, request_hash, result_set_hash, provider, provider_order_not_rank, results, synthetic, trigger_kind, request_cost_usd, fetched_at, expires_at, created_at from growth_search_evidence
where project_id = $1
  and request_hash = $2
  and expires_at > $3
order by fetched_at desc
limit 1
`

type GetCachedGrowthSearchEvidenceParams struct {
	ProjectID   uuid.UUID          `json:"project_id"`
	RequestHash string             `json:"request_hash"`
	NowAt       pgtype.Timestamptz `json:"now_at"`
}

func (q *Queries) GetCachedGrowthSearchEvidence(ctx context.Context, arg GetCachedGrowthSearchEvidenceParams) (GrowthSearchEvidence, error) {
	row := q.db.QueryRow(ctx, getCachedGrowthSearchEvidence, arg.ProjectID, arg.RequestHash, arg.NowAt)
	var i GrowthSearchEvidence
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.NormalizedQuery,
		&i.RequestHash,
		&i.ResultSetHash,
		&i.Provider,
		&i.ProviderOrderNotRank,
		&i.Results,
		&i.Synthetic,
		&i.TriggerKind,
		&i.RequestCostUsd,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getGrowthSearchUsage = `-- name: GetGrowthSearchUsage :one
select
  count(*) filter (where project_id = $1 and fetched_at >= $2 - interval '1 day')::int daily_requests,
  count(*) filter (where project_id = $1 and trigger_kind = 'weekly_rebuild' and fetched_at >= $2 - interval '7 days')::int weekly_rebuild_requests,
  count(*) filter (where project_id = $1 and fetched_at >= $2 - interval '30 days')::int rolling_requests,
  coalesce(sum(request_cost_usd) filter (where project_id = $1 and fetched_at >= $2 - interval '30 days'), 0)::numeric rolling_cost_usd,
  coalesce(sum(request_cost_usd) filter (where fetched_at >= $2 - interval '30 days'), 0)::numeric installation_cost_usd
from growth_search_evidence
`

type GetGrowthSearchUsageParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	NowAt     interface{} `json:"now_at"`
}

type GetGrowthSearchUsageRow struct {
	DailyRequests         int32          `json:"daily_requests"`
	WeeklyRebuildRequests int32          `json:"weekly_rebuild_requests"`
	RollingRequests       int32          `json:"rolling_requests"`
	RollingCostUsd        pgtype.Numeric `json:"rolling_cost_usd"`
	InstallationCostUsd   pgtype.Numeric `json:"installation_cost_usd"`
}

func (q *Queries) GetGrowthSearchUsage(ctx context.Context, arg GetGrowthSearchUsageParams) (GetGrowthSearchUsageRow, error) {
	row := q.db.QueryRow(ctx, getGrowthSearchUsage, arg.ProjectID, arg.NowAt)
	var i GetGrowthSearchUsageRow
	err := row.Scan(
		&i.DailyRequests,
		&i.WeeklyRebuildRequests,
		&i.RollingRequests,
		&i.RollingCostUsd,
		&i.InstallationCostUsd,
	)
	return i, err
}
