// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotificationChannel = `-- name: CreateNotificationChannel :one
insert into notification_channels (project_id, kind, config, label)
values ($1, $2, $3, $4)
returning id, project_id, kind, config, label, verified_at, created_at, deleted_at
`

type CreateNotificationChannelParams struct {
	ProjectID uuid.UUID       `json:"project_id"`
	Kind      string          `json:"kind"`
	Config    json.RawMessage `json:"config"`
	Label     string          `json:"label"`
}

func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, createNotificationChannel,
		arg.ProjectID,
		arg.Kind,
		arg.Config,
		arg.Label,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Config,
		&i.Label,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createNotificationDelivery = `-- name: CreateNotificationDelivery :one
insert into notification_deliveries (project_id, subscription_id, channel_id, event_type, event_id, payload, next_retry_at)
values ($1, $2, $3, $4, $5, $6, now())
on conflict (event_id, channel_id) do nothing
returning id, project_id, subscription_id, channel_id, event_type, event_id, payload, status, attempts, next_retry_at, last_error, delivered_at, created_at
`

type CreateNotificationDeliveryParams struct {
	ProjectID      uuid.UUID       `json:"project_id"`
	SubscriptionID pgtype.UUID     `json:"subscription_id"`
	ChannelID      uuid.UUID       `json:"channel_id"`
	EventType      string          `json:"event_type"`
	EventID        string          `json:"event_id"`
	Payload        json.RawMessage `json:"payload"`
}

func (q *Queries) CreateNotificationDelivery(ctx context.Context, arg CreateNotificationDeliveryParams) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, createNotificationDelivery,
		arg.ProjectID,
		arg.SubscriptionID,
		arg.ChannelID,
		arg.EventType,
		arg.EventID,
		arg.Payload,
	)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SubscriptionID,
		&i.ChannelID,
		&i.EventType,
		&i.EventID,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextRetryAt,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationChannel = `-- name: GetNotificationChannel :one
select id, project_id, kind, config, label, verified_at, created_at, deleted_at from notification_channels
where id = $1
  and project_id = $2
  and deleted_at is null
`

type GetNotificationChannelParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetNotificationChannel(ctx context.Context, arg GetNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannel, arg.ID, arg.ProjectID)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Config,
		&i.Label,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listEnabledNotificationSubscriptionsForEvent = `-- name: ListEnabledNotificationSubscriptionsForEvent :many
select s.id, s.project_id, s.event_type, s.channel_id, s.enabled, s.filter, s.created_at from notification_subscriptions s
join notification_channels c
  on c.id = s.channel_id
where s.project_id = $1
  and s.event_type = $2
  and s.enabled = true
  and c.deleted_at is null
order by s.created_at asc
`

type ListEnabledNotificationSubscriptionsForEventParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	EventType string    `json:"event_type"`
}

func (q *Queries) ListEnabledNotificationSubscriptionsForEvent(ctx context.Context, arg ListEnabledNotificationSubscriptionsForEventParams) ([]NotificationSubscription, error) {
	rows, err := q.db.Query(ctx, listEnabledNotificationSubscriptionsForEvent, arg.ProjectID, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationSubscription
	for rows.Next() {
		var i NotificationSubscription
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EventType,
			&i.ChannelID,
			&i.Enabled,
			&i.Filter,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannels = `-- name: ListNotificationChannels :many
select id, project_id, kind, config, label, verified_at, created_at, deleted_at from notification_channels
where project_id = $1
  and deleted_at is null
order by created_at desc
`

func (q *Queries) ListNotificationChannels(ctx context.Context, projectID uuid.UUID) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listNotificationChannels, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationChannel
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Config,
			&i.Label,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationDeliveries = `-- name: ListNotificationDeliveries :many
select id, project_id, subscription_id, channel_id, event_type, event_id, payload, status, attempts, next_retry_at, last_error, delivered_at, created_at from notification_deliveries
where project_id = $1
  and ($2::text = '' or status = $2)
order by created_at desc
limit $3
`

type ListNotificationDeliveriesParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Status    string    `json:"status"`
	LimitRows int32     `json:"limit_rows"`
}

func (q *Queries) ListNotificationDeliveries(ctx context.Context, arg ListNotificationDeliveriesParams) ([]NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, listNotificationDeliveries, arg.ProjectID, arg.Status, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationDelivery
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SubscriptionID,
			&i.ChannelID,
			&i.EventType,
			&i.EventID,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextRetryAt,
			&i.LastError,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationSubscriptions = `-- name: ListNotificationSubscriptions :many
select id, project_id, event_type, channel_id, enabled, filter, created_at from notification_subscriptions
where project_id = $1
order by event_type, created_at desc
`

func (q *Queries) ListNotificationSubscriptions(ctx context.Context, projectID uuid.UUID) ([]NotificationSubscription, error) {
	rows, err := q.db.Query(ctx, listNotificationSubscriptions, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationSubscription
	for rows.Next() {
		var i NotificationSubscription
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EventType,
			&i.ChannelID,
			&i.Enabled,
			&i.Filter,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingNotificationDeliveries = `-- name: ListPendingNotificationDeliveries :many
select
  d.id,
  d.project_id,
  d.subscription_id,
  d.channel_id,
  d.event_type,
  d.event_id,
  d.payload,
  d.status,
  d.attempts,
  d.next_retry_at,
  d.last_error,
  d.delivered_at,
  d.created_at,
  c.kind as channel_kind,
  c.config as channel_config
from notification_deliveries d
join notification_channels c
  on c.id = d.channel_id
where d.status = 'pending'
  and (d.next_retry_at is null or d.next_retry_at <= now())
  and c.deleted_at is null
order by d.created_at asc
for update skip locked
limit $1
`

type ListPendingNotificationDeliveriesRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	SubscriptionID pgtype.UUID        `json:"subscription_id"`
	ChannelID      uuid.UUID          `json:"channel_id"`
	EventType      string             `json:"event_type"`
	EventID        string             `json:"event_id"`
	Payload        json.RawMessage    `json:"payload"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	NextRetryAt    pgtype.Timestamptz `json:"next_retry_at"`
	LastError      *string            `json:"last_error"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ChannelKind    string             `json:"channel_kind"`
	ChannelConfig  json.RawMessage    `json:"channel_config"`
}

func (q *Queries) ListPendingNotificationDeliveries(ctx context.Context, limit int32) ([]ListPendingNotificationDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listPendingNotificationDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingNotificationDeliveriesRow
	for rows.Next() {
		var i ListPendingNotificationDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SubscriptionID,
			&i.ChannelID,
			&i.EventType,
			&i.EventID,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextRetryAt,
			&i.LastError,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.ChannelKind,
			&i.ChannelConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationChannelVerified = `-- name: MarkNotificationChannelVerified :one
update notification_channels
set verified_at = now()
where id = $1
  and project_id = $2
  and deleted_at is null
returning id, project_id, kind, config, label, verified_at, created_at, deleted_at
`

type MarkNotificationChannelVerifiedParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) MarkNotificationChannelVerified(ctx context.Context, arg MarkNotificationChannelVerifiedParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, markNotificationChannelVerified, arg.ID, arg.ProjectID)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Config,
		&i.Label,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markNotificationDeliveryFailed = `-- name: MarkNotificationDeliveryFailed :one
update notification_deliveries
set attempts = attempts + 1,
    status = case when attempts + 1 >= 4 then 'dead' else 'pending' end,
    next_retry_at = case
      when attempts + 1 >= 4 then null
      when attempts + 1 = 1 then now() + interval '1 minute'
      when attempts + 1 = 2 then now() + interval '5 minutes'
      else now() + interval '30 minutes'
    end,
    last_error = $2
where id = $1
returning id, project_id, subscription_id, channel_id, event_type, event_id, payload, status, attempts, next_retry_at, last_error, delivered_at, created_at
`

type MarkNotificationDeliveryFailedParams struct {
	ID        uuid.UUID `json:"id"`
	LastError *string   `json:"last_error"`
}

func (q *Queries) MarkNotificationDeliveryFailed(ctx context.Context, arg MarkNotificationDeliveryFailedParams) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, markNotificationDeliveryFailed, arg.ID, arg.LastError)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SubscriptionID,
		&i.ChannelID,
		&i.EventType,
		&i.EventID,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextRetryAt,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const markNotificationDeliverySent = `-- name: MarkNotificationDeliverySent :one
update notification_deliveries
set status = 'sent',
    delivered_at = now(),
    last_error = null
where id = $1
returning id, project_id, subscription_id, channel_id, event_type, event_id, payload, status, attempts, next_retry_at, last_error, delivered_at, created_at
`

func (q *Queries) MarkNotificationDeliverySent(ctx context.Context, id uuid.UUID) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, markNotificationDeliverySent, id)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SubscriptionID,
		&i.ChannelID,
		&i.EventType,
		&i.EventID,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextRetryAt,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const retryNotificationDelivery = `-- name: RetryNotificationDelivery :one
update notification_deliveries
set status = 'pending',
    next_retry_at = now(),
    last_error = null
where id = $1
  and project_id = $2
returning id, project_id, subscription_id, channel_id, event_type, event_id, payload, status, attempts, next_retry_at, last_error, delivered_at, created_at
`

type RetryNotificationDeliveryParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) RetryNotificationDelivery(ctx context.Context, arg RetryNotificationDeliveryParams) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, retryNotificationDelivery, arg.ID, arg.ProjectID)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SubscriptionID,
		&i.ChannelID,
		&i.EventType,
		&i.EventID,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextRetryAt,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const softDeleteNotificationChannel = `-- name: SoftDeleteNotificationChannel :one
update notification_channels
set deleted_at = now()
where id = $1
  and project_id = $2
returning id, project_id, kind, config, label, verified_at, created_at, deleted_at
`

type SoftDeleteNotificationChannelParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) SoftDeleteNotificationChannel(ctx context.Context, arg SoftDeleteNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, softDeleteNotificationChannel, arg.ID, arg.ProjectID)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Config,
		&i.Label,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertNotificationSubscription = `-- name: UpsertNotificationSubscription :one
insert into notification_subscriptions (project_id, event_type, channel_id, enabled, filter)
values ($1, $2, $3, $4, $5)
on conflict (project_id, event_type, channel_id) do update
set enabled = excluded.enabled,
    filter = excluded.filter
returning id, project_id, event_type, channel_id, enabled, filter, created_at
`

type UpsertNotificationSubscriptionParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	EventType string    `json:"event_type"`
	ChannelID uuid.UUID `json:"channel_id"`
	Enabled   bool      `json:"enabled"`
	Filter    []byte    `json:"filter"`
}

func (q *Queries) UpsertNotificationSubscription(ctx context.Context, arg UpsertNotificationSubscriptionParams) (NotificationSubscription, error) {
	row := q.db.QueryRow(ctx, upsertNotificationSubscription,
		arg.ProjectID,
		arg.EventType,
		arg.ChannelID,
		arg.Enabled,
		arg.Filter,
	)
	var i NotificationSubscription
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EventType,
		&i.ChannelID,
		&i.Enabled,
		&i.Filter,
		&i.CreatedAt,
	)
	return i, err
}
