// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: opportunity_finding.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acquireOpportunityFindingStage = `-- name: AcquireOpportunityFindingStage :one
insert into opportunity_finding_stage_checkpoints
  (id, project_id, workflow_event_id, stage, stage_order, request_fingerprint,
   status, attempt_number, owner_token, lease_expires_at, started_at)
values
  ($1, $2, $3, $4,
   $5, $6, 'running', 1,
   $7, $8, now())
on conflict (workflow_event_id, stage) do update set
  status = case
    when opportunity_finding_stage_checkpoints.status = 'running'
      and opportunity_finding_stage_checkpoints.lease_expires_at <= now()
    then 'running'
    else opportunity_finding_stage_checkpoints.status
  end,
  attempt_number = case
    when opportunity_finding_stage_checkpoints.status = 'running'
      and opportunity_finding_stage_checkpoints.lease_expires_at <= now()
    then opportunity_finding_stage_checkpoints.attempt_number + 1
    else opportunity_finding_stage_checkpoints.attempt_number
  end,
  owner_token = case
    when opportunity_finding_stage_checkpoints.status = 'running'
      and opportunity_finding_stage_checkpoints.lease_expires_at <= now()
    then excluded.owner_token
    else opportunity_finding_stage_checkpoints.owner_token
  end,
  lease_expires_at = case
    when opportunity_finding_stage_checkpoints.status = 'running'
      and opportunity_finding_stage_checkpoints.lease_expires_at <= now()
    then excluded.lease_expires_at
    else opportunity_finding_stage_checkpoints.lease_expires_at
  end,
  started_at = case
    when opportunity_finding_stage_checkpoints.status = 'running'
      and opportunity_finding_stage_checkpoints.lease_expires_at <= now()
    then now()
    else opportunity_finding_stage_checkpoints.started_at
  end,
  output_summary = case
    when opportunity_finding_stage_checkpoints.status = 'running'
      and opportunity_finding_stage_checkpoints.lease_expires_at <= now()
    then '{}'::jsonb
    else opportunity_finding_stage_checkpoints.output_summary
  end,
  error = case
    when opportunity_finding_stage_checkpoints.status = 'running'
      and opportunity_finding_stage_checkpoints.lease_expires_at <= now()
    then null
    else opportunity_finding_stage_checkpoints.error
  end,
  updated_at = case
    when opportunity_finding_stage_checkpoints.status = 'running'
      and opportunity_finding_stage_checkpoints.lease_expires_at <= now()
    then now()
    else opportunity_finding_stage_checkpoints.updated_at
  end
returning id, project_id, workflow_event_id, stage, stage_order, request_fingerprint, status, attempt_number, owner_token, lease_expires_at, output_summary, error, started_at, finished_at, created_at, updated_at
`

type AcquireOpportunityFindingStageParams struct {
	ID                 uuid.UUID          `json:"id"`
	ProjectID          uuid.UUID          `json:"project_id"`
	WorkflowEventID    uuid.UUID          `json:"workflow_event_id"`
	Stage              string             `json:"stage"`
	StageOrder         int16              `json:"stage_order"`
	RequestFingerprint string             `json:"request_fingerprint"`
	OwnerToken         uuid.UUID          `json:"owner_token"`
	LeaseExpiresAt     pgtype.Timestamptz `json:"lease_expires_at"`
}

func (q *Queries) AcquireOpportunityFindingStage(ctx context.Context, arg AcquireOpportunityFindingStageParams) (OpportunityFindingStageCheckpoint, error) {
	row := q.db.QueryRow(ctx, acquireOpportunityFindingStage,
		arg.ID,
		arg.ProjectID,
		arg.WorkflowEventID,
		arg.Stage,
		arg.StageOrder,
		arg.RequestFingerprint,
		arg.OwnerToken,
		arg.LeaseExpiresAt,
	)
	var i OpportunityFindingStageCheckpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.WorkflowEventID,
		&i.Stage,
		&i.StageOrder,
		&i.RequestFingerprint,
		&i.Status,
		&i.AttemptNumber,
		&i.OwnerToken,
		&i.LeaseExpiresAt,
		&i.OutputSummary,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finishOpportunityFindingStage = `-- name: FinishOpportunityFindingStage :one
update opportunity_finding_stage_checkpoints set
  status = $1,
  output_summary = $2::jsonb,
  error = $3,
  lease_expires_at = null,
  finished_at = now(),
  updated_at = now()
where id = $4
  and project_id = $5
  and workflow_event_id = $6
  and stage = $7
  and status = 'running'
  and owner_token = $8
  and $1::text in ('succeeded','partial','failed','skipped')
returning id, project_id, workflow_event_id, stage, stage_order, request_fingerprint, status, attempt_number, owner_token, lease_expires_at, output_summary, error, started_at, finished_at, created_at, updated_at
`

type FinishOpportunityFindingStageParams struct {
	Status          string          `json:"status"`
	OutputSummary   json.RawMessage `json:"output_summary"`
	Error           *string         `json:"error"`
	ID              uuid.UUID       `json:"id"`
	ProjectID       uuid.UUID       `json:"project_id"`
	WorkflowEventID uuid.UUID       `json:"workflow_event_id"`
	Stage           string          `json:"stage"`
	OwnerToken      uuid.UUID       `json:"owner_token"`
}

func (q *Queries) FinishOpportunityFindingStage(ctx context.Context, arg FinishOpportunityFindingStageParams) (OpportunityFindingStageCheckpoint, error) {
	row := q.db.QueryRow(ctx, finishOpportunityFindingStage,
		arg.Status,
		arg.OutputSummary,
		arg.Error,
		arg.ID,
		arg.ProjectID,
		arg.WorkflowEventID,
		arg.Stage,
		arg.OwnerToken,
	)
	var i OpportunityFindingStageCheckpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.WorkflowEventID,
		&i.Stage,
		&i.StageOrder,
		&i.RequestFingerprint,
		&i.Status,
		&i.AttemptNumber,
		&i.OwnerToken,
		&i.LeaseExpiresAt,
		&i.OutputSummary,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOpportunityFindingStages = `-- name: ListOpportunityFindingStages :many
select id, project_id, workflow_event_id, stage, stage_order, request_fingerprint, status, attempt_number, owner_token, lease_expires_at, output_summary, error, started_at, finished_at, created_at, updated_at from opportunity_finding_stage_checkpoints
where project_id = $1
  and workflow_event_id = $2
order by stage_order, created_at, id
`

type ListOpportunityFindingStagesParams struct {
	ProjectID       uuid.UUID `json:"project_id"`
	WorkflowEventID uuid.UUID `json:"workflow_event_id"`
}

func (q *Queries) ListOpportunityFindingStages(ctx context.Context, arg ListOpportunityFindingStagesParams) ([]OpportunityFindingStageCheckpoint, error) {
	rows, err := q.db.Query(ctx, listOpportunityFindingStages, arg.ProjectID, arg.WorkflowEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpportunityFindingStageCheckpoint
	for rows.Next() {
		var i OpportunityFindingStageCheckpoint
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.WorkflowEventID,
			&i.Stage,
			&i.StageOrder,
			&i.RequestFingerprint,
			&i.Status,
			&i.AttemptNumber,
			&i.OwnerToken,
			&i.LeaseExpiresAt,
			&i.OutputSummary,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
