// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform_contracts.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmPlatformTargetContext = `-- name: ConfirmPlatformTargetContext :one
update platform_target_contexts
set status = 'confirmed', confirmed_by = $1,
    confirmed_at = $2, expires_at = $3,
    updated_at = now()
where id = $4 and project_id = $5 and status = 'draft'
returning id, project_id, platform, target_key, version, status, source_kind, source_url, rules_url, rules_text, allowed_post_types, required_flair, link_policy, self_promotion_policy, disclosure_requirements, notes, content_hash, confirmed_by, confirmed_at, expires_at, supersedes_context_id, created_at, updated_at
`

type ConfirmPlatformTargetContextParams struct {
	ConfirmedBy *string            `json:"confirmed_by"`
	ConfirmedAt pgtype.Timestamptz `json:"confirmed_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
}

func (q *Queries) ConfirmPlatformTargetContext(ctx context.Context, arg ConfirmPlatformTargetContextParams) (PlatformTargetContext, error) {
	row := q.db.QueryRow(ctx, confirmPlatformTargetContext,
		arg.ConfirmedBy,
		arg.ConfirmedAt,
		arg.ExpiresAt,
		arg.ID,
		arg.ProjectID,
	)
	var i PlatformTargetContext
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Platform,
		&i.TargetKey,
		&i.Version,
		&i.Status,
		&i.SourceKind,
		&i.SourceUrl,
		&i.RulesUrl,
		&i.RulesText,
		&i.AllowedPostTypes,
		&i.RequiredFlair,
		&i.LinkPolicy,
		&i.SelfPromotionPolicy,
		&i.DisclosureRequirements,
		&i.Notes,
		&i.ContentHash,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
		&i.ExpiresAt,
		&i.SupersedesContextID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createContentTargetPlan = `-- name: CreateContentTargetPlan :one
insert into content_target_plans (
  project_id, opportunity_id, content_action_id, asset_type,
  canonical_target, selection_mode, status, capability_snapshot
) values (
  $1, $2, $3,
  $4, $5, $6,
  $7, $8
)
returning id, project_id, opportunity_id, content_action_id, asset_type, canonical_target, selection_mode, status, capability_snapshot, created_at, updated_at
`

type CreateContentTargetPlanParams struct {
	ProjectID          uuid.UUID       `json:"project_id"`
	OpportunityID      pgtype.UUID     `json:"opportunity_id"`
	ContentActionID    pgtype.UUID     `json:"content_action_id"`
	AssetType          string          `json:"asset_type"`
	CanonicalTarget    string          `json:"canonical_target"`
	SelectionMode      string          `json:"selection_mode"`
	Status             string          `json:"status"`
	CapabilitySnapshot json.RawMessage `json:"capability_snapshot"`
}

func (q *Queries) CreateContentTargetPlan(ctx context.Context, arg CreateContentTargetPlanParams) (ContentTargetPlan, error) {
	row := q.db.QueryRow(ctx, createContentTargetPlan,
		arg.ProjectID,
		arg.OpportunityID,
		arg.ContentActionID,
		arg.AssetType,
		arg.CanonicalTarget,
		arg.SelectionMode,
		arg.Status,
		arg.CapabilitySnapshot,
	)
	var i ContentTargetPlan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OpportunityID,
		&i.ContentActionID,
		&i.AssetType,
		&i.CanonicalTarget,
		&i.SelectionMode,
		&i.Status,
		&i.CapabilitySnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createContentTargetPlanItem = `-- name: CreateContentTargetPlanItem :one
insert into content_target_plan_items (
  plan_id, ordinal, platform, target_key, output_type, is_canonical,
  platform_contract_id, platform_contract_version, target_context_id,
  target_context_version, rationale, status
) values (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8, $9,
  $10, $11, $12
)
returning id, plan_id, ordinal, platform, target_key, output_type, is_canonical, platform_contract_id, platform_contract_version, target_context_id, target_context_version, rationale, status, created_at, updated_at
`

type CreateContentTargetPlanItemParams struct {
	PlanID                  uuid.UUID   `json:"plan_id"`
	Ordinal                 int32       `json:"ordinal"`
	Platform                string      `json:"platform"`
	TargetKey               string      `json:"target_key"`
	OutputType              string      `json:"output_type"`
	IsCanonical             bool        `json:"is_canonical"`
	PlatformContractID      pgtype.UUID `json:"platform_contract_id"`
	PlatformContractVersion string      `json:"platform_contract_version"`
	TargetContextID         pgtype.UUID `json:"target_context_id"`
	TargetContextVersion    *int32      `json:"target_context_version"`
	Rationale               string      `json:"rationale"`
	Status                  string      `json:"status"`
}

func (q *Queries) CreateContentTargetPlanItem(ctx context.Context, arg CreateContentTargetPlanItemParams) (ContentTargetPlanItem, error) {
	row := q.db.QueryRow(ctx, createContentTargetPlanItem,
		arg.PlanID,
		arg.Ordinal,
		arg.Platform,
		arg.TargetKey,
		arg.OutputType,
		arg.IsCanonical,
		arg.PlatformContractID,
		arg.PlatformContractVersion,
		arg.TargetContextID,
		arg.TargetContextVersion,
		arg.Rationale,
		arg.Status,
	)
	var i ContentTargetPlanItem
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Ordinal,
		&i.Platform,
		&i.TargetKey,
		&i.OutputType,
		&i.IsCanonical,
		&i.PlatformContractID,
		&i.PlatformContractVersion,
		&i.TargetContextID,
		&i.TargetContextVersion,
		&i.Rationale,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPlatformTargetContext = `-- name: CreatePlatformTargetContext :one
insert into platform_target_contexts (
  project_id, platform, target_key, version, status, source_kind,
  source_url, rules_url, rules_text, allowed_post_types, required_flair,
  link_policy, self_promotion_policy, disclosure_requirements, notes,
  content_hash, supersedes_context_id
) values (
  $1, $2, $3, $4,
  'draft', $5, $6, $7,
  $8, $9, $10,
  $11, $12, $13,
  $14, $15, $16
)
returning id, project_id, platform, target_key, version, status, source_kind, source_url, rules_url, rules_text, allowed_post_types, required_flair, link_policy, self_promotion_policy, disclosure_requirements, notes, content_hash, confirmed_by, confirmed_at, expires_at, supersedes_context_id, created_at, updated_at
`

type CreatePlatformTargetContextParams struct {
	ProjectID              uuid.UUID       `json:"project_id"`
	Platform               string          `json:"platform"`
	TargetKey              string          `json:"target_key"`
	Version                int32           `json:"version"`
	SourceKind             string          `json:"source_kind"`
	SourceUrl              *string         `json:"source_url"`
	RulesUrl               *string         `json:"rules_url"`
	RulesText              string          `json:"rules_text"`
	AllowedPostTypes       json.RawMessage `json:"allowed_post_types"`
	RequiredFlair          *string         `json:"required_flair"`
	LinkPolicy             string          `json:"link_policy"`
	SelfPromotionPolicy    string          `json:"self_promotion_policy"`
	DisclosureRequirements string          `json:"disclosure_requirements"`
	Notes                  string          `json:"notes"`
	ContentHash            string          `json:"content_hash"`
	SupersedesContextID    pgtype.UUID     `json:"supersedes_context_id"`
}

func (q *Queries) CreatePlatformTargetContext(ctx context.Context, arg CreatePlatformTargetContextParams) (PlatformTargetContext, error) {
	row := q.db.QueryRow(ctx, createPlatformTargetContext,
		arg.ProjectID,
		arg.Platform,
		arg.TargetKey,
		arg.Version,
		arg.SourceKind,
		arg.SourceUrl,
		arg.RulesUrl,
		arg.RulesText,
		arg.AllowedPostTypes,
		arg.RequiredFlair,
		arg.LinkPolicy,
		arg.SelfPromotionPolicy,
		arg.DisclosureRequirements,
		arg.Notes,
		arg.ContentHash,
		arg.SupersedesContextID,
	)
	var i PlatformTargetContext
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Platform,
		&i.TargetKey,
		&i.Version,
		&i.Status,
		&i.SourceKind,
		&i.SourceUrl,
		&i.RulesUrl,
		&i.RulesText,
		&i.AllowedPostTypes,
		&i.RequiredFlair,
		&i.LinkPolicy,
		&i.SelfPromotionPolicy,
		&i.DisclosureRequirements,
		&i.Notes,
		&i.ContentHash,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
		&i.ExpiresAt,
		&i.SupersedesContextID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expirePlatformTargetContexts = `-- name: ExpirePlatformTargetContexts :many
update platform_target_contexts
set status = 'expired', updated_at = now()
where status = 'confirmed' and expires_at <= $1
returning id, project_id, platform, target_key, version, status, source_kind, source_url, rules_url, rules_text, allowed_post_types, required_flair, link_policy, self_promotion_policy, disclosure_requirements, notes, content_hash, confirmed_by, confirmed_at, expires_at, supersedes_context_id, created_at, updated_at
`

func (q *Queries) ExpirePlatformTargetContexts(ctx context.Context, nowAt pgtype.Timestamptz) ([]PlatformTargetContext, error) {
	rows, err := q.db.Query(ctx, expirePlatformTargetContexts, nowAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformTargetContext
	for rows.Next() {
		var i PlatformTargetContext
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Platform,
			&i.TargetKey,
			&i.Version,
			&i.Status,
			&i.SourceKind,
			&i.SourceUrl,
			&i.RulesUrl,
			&i.RulesText,
			&i.AllowedPostTypes,
			&i.RequiredFlair,
			&i.LinkPolicy,
			&i.SelfPromotionPolicy,
			&i.DisclosureRequirements,
			&i.Notes,
			&i.ContentHash,
			&i.ConfirmedBy,
			&i.ConfirmedAt,
			&i.ExpiresAt,
			&i.SupersedesContextID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveContentTargetPlanByOpportunity = `-- name: GetActiveContentTargetPlanByOpportunity :one
select id, project_id, opportunity_id, content_action_id, asset_type, canonical_target, selection_mode, status, capability_snapshot, created_at, updated_at from content_target_plans
where project_id = $1
  and opportunity_id = $2
  and status <> 'archived'
`

type GetActiveContentTargetPlanByOpportunityParams struct {
	ProjectID     uuid.UUID   `json:"project_id"`
	OpportunityID pgtype.UUID `json:"opportunity_id"`
}

func (q *Queries) GetActiveContentTargetPlanByOpportunity(ctx context.Context, arg GetActiveContentTargetPlanByOpportunityParams) (ContentTargetPlan, error) {
	row := q.db.QueryRow(ctx, getActiveContentTargetPlanByOpportunity, arg.ProjectID, arg.OpportunityID)
	var i ContentTargetPlan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OpportunityID,
		&i.ContentActionID,
		&i.AssetType,
		&i.CanonicalTarget,
		&i.SelectionMode,
		&i.Status,
		&i.CapabilitySnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivePlatformContentContract = `-- name: GetActivePlatformContentContract :one
select id, platform, version, status, source_urls, source_retrieved_at, effective_at, review_due_at, generation_supported, publish_mode, allowed_output_types, compatible_asset_types, required_context_fields, capabilities, canonical_policy, hard_rules, prompt_template, semantic_rubric, preview_renderer_key, supersedes_contract_id, created_at, updated_at from platform_content_contracts
where platform = $1 and status = 'active'
`

func (q *Queries) GetActivePlatformContentContract(ctx context.Context, platform string) (PlatformContentContract, error) {
	row := q.db.QueryRow(ctx, getActivePlatformContentContract, platform)
	var i PlatformContentContract
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Version,
		&i.Status,
		&i.SourceUrls,
		&i.SourceRetrievedAt,
		&i.EffectiveAt,
		&i.ReviewDueAt,
		&i.GenerationSupported,
		&i.PublishMode,
		&i.AllowedOutputTypes,
		&i.CompatibleAssetTypes,
		&i.RequiredContextFields,
		&i.Capabilities,
		&i.CanonicalPolicy,
		&i.HardRules,
		&i.PromptTemplate,
		&i.SemanticRubric,
		&i.PreviewRendererKey,
		&i.SupersedesContractID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContentTargetPlanForProject = `-- name: GetContentTargetPlanForProject :one
select id, project_id, opportunity_id, content_action_id, asset_type, canonical_target, selection_mode, status, capability_snapshot, created_at, updated_at from content_target_plans
where id = $1 and project_id = $2
`

type GetContentTargetPlanForProjectParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetContentTargetPlanForProject(ctx context.Context, arg GetContentTargetPlanForProjectParams) (ContentTargetPlan, error) {
	row := q.db.QueryRow(ctx, getContentTargetPlanForProject, arg.ID, arg.ProjectID)
	var i ContentTargetPlan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OpportunityID,
		&i.ContentActionID,
		&i.AssetType,
		&i.CanonicalTarget,
		&i.SelectionMode,
		&i.Status,
		&i.CapabilitySnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentPlatformTargetContext = `-- name: GetCurrentPlatformTargetContext :one
select id, project_id, platform, target_key, version, status, source_kind, source_url, rules_url, rules_text, allowed_post_types, required_flair, link_policy, self_promotion_policy, disclosure_requirements, notes, content_hash, confirmed_by, confirmed_at, expires_at, supersedes_context_id, created_at, updated_at from platform_target_contexts
where project_id = $1
  and platform = $2
  and target_key = $3
  and status = 'confirmed'
  and expires_at > now()
`

type GetCurrentPlatformTargetContextParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Platform  string    `json:"platform"`
	TargetKey string    `json:"target_key"`
}

func (q *Queries) GetCurrentPlatformTargetContext(ctx context.Context, arg GetCurrentPlatformTargetContextParams) (PlatformTargetContext, error) {
	row := q.db.QueryRow(ctx, getCurrentPlatformTargetContext, arg.ProjectID, arg.Platform, arg.TargetKey)
	var i PlatformTargetContext
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Platform,
		&i.TargetKey,
		&i.Version,
		&i.Status,
		&i.SourceKind,
		&i.SourceUrl,
		&i.RulesUrl,
		&i.RulesText,
		&i.AllowedPostTypes,
		&i.RequiredFlair,
		&i.LinkPolicy,
		&i.SelfPromotionPolicy,
		&i.DisclosureRequirements,
		&i.Notes,
		&i.ContentHash,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
		&i.ExpiresAt,
		&i.SupersedesContextID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformContentContractByID = `-- name: GetPlatformContentContractByID :one
select id, platform, version, status, source_urls, source_retrieved_at, effective_at, review_due_at, generation_supported, publish_mode, allowed_output_types, compatible_asset_types, required_context_fields, capabilities, canonical_policy, hard_rules, prompt_template, semantic_rubric, preview_renderer_key, supersedes_contract_id, created_at, updated_at from platform_content_contracts
where id = $1 and version = $2
`

type GetPlatformContentContractByIDParams struct {
	ID      uuid.UUID `json:"id"`
	Version string    `json:"version"`
}

func (q *Queries) GetPlatformContentContractByID(ctx context.Context, arg GetPlatformContentContractByIDParams) (PlatformContentContract, error) {
	row := q.db.QueryRow(ctx, getPlatformContentContractByID, arg.ID, arg.Version)
	var i PlatformContentContract
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Version,
		&i.Status,
		&i.SourceUrls,
		&i.SourceRetrievedAt,
		&i.EffectiveAt,
		&i.ReviewDueAt,
		&i.GenerationSupported,
		&i.PublishMode,
		&i.AllowedOutputTypes,
		&i.CompatibleAssetTypes,
		&i.RequiredContextFields,
		&i.Capabilities,
		&i.CanonicalPolicy,
		&i.HardRules,
		&i.PromptTemplate,
		&i.SemanticRubric,
		&i.PreviewRendererKey,
		&i.SupersedesContractID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformTargetContextForProject = `-- name: GetPlatformTargetContextForProject :one
select id, project_id, platform, target_key, version, status, source_kind, source_url, rules_url, rules_text, allowed_post_types, required_flair, link_policy, self_promotion_policy, disclosure_requirements, notes, content_hash, confirmed_by, confirmed_at, expires_at, supersedes_context_id, created_at, updated_at from platform_target_contexts
where id = $1 and project_id = $2
`

type GetPlatformTargetContextForProjectParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetPlatformTargetContextForProject(ctx context.Context, arg GetPlatformTargetContextForProjectParams) (PlatformTargetContext, error) {
	row := q.db.QueryRow(ctx, getPlatformTargetContextForProject, arg.ID, arg.ProjectID)
	var i PlatformTargetContext
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Platform,
		&i.TargetKey,
		&i.Version,
		&i.Status,
		&i.SourceKind,
		&i.SourceUrl,
		&i.RulesUrl,
		&i.RulesText,
		&i.AllowedPostTypes,
		&i.RequiredFlair,
		&i.LinkPolicy,
		&i.SelfPromotionPolicy,
		&i.DisclosureRequirements,
		&i.Notes,
		&i.ContentHash,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
		&i.ExpiresAt,
		&i.SupersedesContextID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePlatformContentContracts = `-- name: ListActivePlatformContentContracts :many
select id, platform, version, status, source_urls, source_retrieved_at, effective_at, review_due_at, generation_supported, publish_mode, allowed_output_types, compatible_asset_types, required_context_fields, capabilities, canonical_policy, hard_rules, prompt_template, semantic_rubric, preview_renderer_key, supersedes_contract_id, created_at, updated_at from platform_content_contracts
where status = 'active'
order by platform
`

func (q *Queries) ListActivePlatformContentContracts(ctx context.Context) ([]PlatformContentContract, error) {
	rows, err := q.db.Query(ctx, listActivePlatformContentContracts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformContentContract
	for rows.Next() {
		var i PlatformContentContract
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Version,
			&i.Status,
			&i.SourceUrls,
			&i.SourceRetrievedAt,
			&i.EffectiveAt,
			&i.ReviewDueAt,
			&i.GenerationSupported,
			&i.PublishMode,
			&i.AllowedOutputTypes,
			&i.CompatibleAssetTypes,
			&i.RequiredContextFields,
			&i.Capabilities,
			&i.CanonicalPolicy,
			&i.HardRules,
			&i.PromptTemplate,
			&i.SemanticRubric,
			&i.PreviewRendererKey,
			&i.SupersedesContractID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentTargetPlanItems = `-- name: ListContentTargetPlanItems :many
select id, plan_id, ordinal, platform, target_key, output_type, is_canonical, platform_contract_id, platform_contract_version, target_context_id, target_context_version, rationale, status, created_at, updated_at from content_target_plan_items
where plan_id = $1
order by ordinal, id
`

func (q *Queries) ListContentTargetPlanItems(ctx context.Context, planID uuid.UUID) ([]ContentTargetPlanItem, error) {
	rows, err := q.db.Query(ctx, listContentTargetPlanItems, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentTargetPlanItem
	for rows.Next() {
		var i ContentTargetPlanItem
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Ordinal,
			&i.Platform,
			&i.TargetKey,
			&i.OutputType,
			&i.IsCanonical,
			&i.PlatformContractID,
			&i.PlatformContractVersion,
			&i.TargetContextID,
			&i.TargetContextVersion,
			&i.Rationale,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformTargetContexts = `-- name: ListPlatformTargetContexts :many
select id, project_id, platform, target_key, version, status, source_kind, source_url, rules_url, rules_text, allowed_post_types, required_flair, link_policy, self_promotion_policy, disclosure_requirements, notes, content_hash, confirmed_by, confirmed_at, expires_at, supersedes_context_id, created_at, updated_at from platform_target_contexts
where project_id = $1
  and ($2::text = '' or platform = $2)
order by platform, target_key, version desc
`

type ListPlatformTargetContextsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Platform  string    `json:"platform"`
}

func (q *Queries) ListPlatformTargetContexts(ctx context.Context, arg ListPlatformTargetContextsParams) ([]PlatformTargetContext, error) {
	rows, err := q.db.Query(ctx, listPlatformTargetContexts, arg.ProjectID, arg.Platform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformTargetContext
	for rows.Next() {
		var i PlatformTargetContext
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Platform,
			&i.TargetKey,
			&i.Version,
			&i.Status,
			&i.SourceKind,
			&i.SourceUrl,
			&i.RulesUrl,
			&i.RulesText,
			&i.AllowedPostTypes,
			&i.RequiredFlair,
			&i.LinkPolicy,
			&i.SelfPromotionPolicy,
			&i.DisclosureRequirements,
			&i.Notes,
			&i.ContentHash,
			&i.ConfirmedBy,
			&i.ConfirmedAt,
			&i.ExpiresAt,
			&i.SupersedesContextID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextPlatformTargetContextVersion = `-- name: NextPlatformTargetContextVersion :one
select coalesce(max(version), 0)::int + 1
from platform_target_contexts
where project_id = $1
  and platform = $2
  and target_key = $3
`

type NextPlatformTargetContextVersionParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Platform  string    `json:"platform"`
	TargetKey string    `json:"target_key"`
}

func (q *Queries) NextPlatformTargetContextVersion(ctx context.Context, arg NextPlatformTargetContextVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextPlatformTargetContextVersion, arg.ProjectID, arg.Platform, arg.TargetKey)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const supersedeCurrentPlatformTargetContext = `-- name: SupersedeCurrentPlatformTargetContext :exec
update platform_target_contexts
set status = 'superseded', updated_at = now()
where project_id = $1
  and platform = $2
  and target_key = $3
  and status = 'confirmed'
`

type SupersedeCurrentPlatformTargetContextParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Platform  string    `json:"platform"`
	TargetKey string    `json:"target_key"`
}

func (q *Queries) SupersedeCurrentPlatformTargetContext(ctx context.Context, arg SupersedeCurrentPlatformTargetContextParams) error {
	_, err := q.db.Exec(ctx, supersedeCurrentPlatformTargetContext, arg.ProjectID, arg.Platform, arg.TargetKey)
	return err
}

const updateContentTargetPlanStatus = `-- name: UpdateContentTargetPlanStatus :one
update content_target_plans
set status = $1, updated_at = now()
where id = $2 and project_id = $3
returning id, project_id, opportunity_id, content_action_id, asset_type, canonical_target, selection_mode, status, capability_snapshot, created_at, updated_at
`

type UpdateContentTargetPlanStatusParams struct {
	Status    string    `json:"status"`
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) UpdateContentTargetPlanStatus(ctx context.Context, arg UpdateContentTargetPlanStatusParams) (ContentTargetPlan, error) {
	row := q.db.QueryRow(ctx, updateContentTargetPlanStatus, arg.Status, arg.ID, arg.ProjectID)
	var i ContentTargetPlan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OpportunityID,
		&i.ContentActionID,
		&i.AssetType,
		&i.CanonicalTarget,
		&i.SelectionMode,
		&i.Status,
		&i.CapabilitySnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
