// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
insert into projects (owner_id, name, slug, config)
values ($1, $2, $3, $4)
returning id, owner_id, name, slug, config, created_at, updated_at
`

type CreateProjectParams struct {
	OwnerID string          `json:"owner_id"`
	Name    string          `json:"name"`
	Slug    string          `json:"slug"`
	Config  json.RawMessage `json:"config"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OwnerID,
		arg.Name,
		arg.Slug,
		arg.Config,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :one
delete from projects
where id = $1
returning id, owner_id, name, slug, config, created_at, updated_at
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, deleteProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectForOwner = `-- name: DeleteProjectForOwner :one
delete from projects
where id = $1
  and owner_id = $2
returning id, owner_id, name, slug, config, created_at, updated_at
`

type DeleteProjectForOwnerParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID string    `json:"owner_id"`
}

func (q *Queries) DeleteProjectForOwner(ctx context.Context, arg DeleteProjectForOwnerParams) (Project, error) {
	row := q.db.QueryRow(ctx, deleteProjectForOwner, arg.ID, arg.OwnerID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
select id, owner_id, name, slug, config, created_at, updated_at from projects where id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
select id, owner_id, name, slug, config, created_at, updated_at from projects where slug = $1
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectForOwner = `-- name: GetProjectForOwner :one
select id, owner_id, name, slug, config, created_at, updated_at from projects
where id = $1
  and owner_id = $2
`

type GetProjectForOwnerParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID string    `json:"owner_id"`
}

func (q *Queries) GetProjectForOwner(ctx context.Context, arg GetProjectForOwnerParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectForOwner, arg.ID, arg.OwnerID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminProjects = `-- name: ListAdminProjects :many
select id, owner_id, name, slug, config, created_at, updated_at from projects order by updated_at desc, created_at desc
`

func (q *Queries) ListAdminProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listAdminProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Slug,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
select id, owner_id, name, slug, config, created_at, updated_at from projects order by created_at desc
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Slug,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByOwner = `-- name: ListProjectsByOwner :many
select id, owner_id, name, slug, config, created_at, updated_at from projects
where owner_id = $1
order by created_at desc
`

func (q *Queries) ListProjectsByOwner(ctx context.Context, ownerID string) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Slug,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectConfig = `-- name: UpdateProjectConfig :one
update projects set config = $2, updated_at = now() where id = $1
returning id, owner_id, name, slug, config, created_at, updated_at
`

type UpdateProjectConfigParams struct {
	ID     uuid.UUID       `json:"id"`
	Config json.RawMessage `json:"config"`
}

func (q *Queries) UpdateProjectConfig(ctx context.Context, arg UpdateProjectConfigParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectConfig, arg.ID, arg.Config)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectConfigForOwner = `-- name: UpdateProjectConfigForOwner :one
update projects set config = $2, updated_at = now()
where id = $1
  and owner_id = $3
returning id, owner_id, name, slug, config, created_at, updated_at
`

type UpdateProjectConfigForOwnerParams struct {
	ID      uuid.UUID       `json:"id"`
	Config  json.RawMessage `json:"config"`
	OwnerID string          `json:"owner_id"`
}

func (q *Queries) UpdateProjectConfigForOwner(ctx context.Context, arg UpdateProjectConfigForOwnerParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectConfigForOwner, arg.ID, arg.Config, arg.OwnerID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
