// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: publisher_connections.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearPublisherConnectionCredentialRef = `-- name: ClearPublisherConnectionCredentialRef :one
update publisher_connections
set credential_ref = null,
    status = 'missing',
    last_error = null,
    pr_readiness_status = 'not_connected',
    pr_readiness_checked_at = null,
    pr_readiness_detail = null,
    updated_at = now()
where id = $1 and project_id = $2
returning id, project_id, kind, label, status, is_default, enabled, capabilities, capability_schema_version, credential_ref, config, oauth_access_expires_at, oauth_refresh_status, revoked_at, last_verified_at, last_error, created_at, updated_at, pr_readiness_status, pr_readiness_checked_at, pr_readiness_detail
`

type ClearPublisherConnectionCredentialRefParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) ClearPublisherConnectionCredentialRef(ctx context.Context, arg ClearPublisherConnectionCredentialRefParams) (PublisherConnection, error) {
	row := q.db.QueryRow(ctx, clearPublisherConnectionCredentialRef, arg.ID, arg.ProjectID)
	var i PublisherConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Label,
		&i.Status,
		&i.IsDefault,
		&i.Enabled,
		&i.Capabilities,
		&i.CapabilitySchemaVersion,
		&i.CredentialRef,
		&i.Config,
		&i.OauthAccessExpiresAt,
		&i.OauthRefreshStatus,
		&i.RevokedAt,
		&i.LastVerifiedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrReadinessStatus,
		&i.PrReadinessCheckedAt,
		&i.PrReadinessDetail,
	)
	return i, err
}

const deletePublisherConnectionForProject = `-- name: DeletePublisherConnectionForProject :one
delete from publisher_connections
where id = $1 and project_id = $2
returning id, project_id, kind, label, status, is_default, enabled, capabilities, capability_schema_version, credential_ref, config, oauth_access_expires_at, oauth_refresh_status, revoked_at, last_verified_at, last_error, created_at, updated_at, pr_readiness_status, pr_readiness_checked_at, pr_readiness_detail
`

type DeletePublisherConnectionForProjectParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeletePublisherConnectionForProject(ctx context.Context, arg DeletePublisherConnectionForProjectParams) (PublisherConnection, error) {
	row := q.db.QueryRow(ctx, deletePublisherConnectionForProject, arg.ID, arg.ProjectID)
	var i PublisherConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Label,
		&i.Status,
		&i.IsDefault,
		&i.Enabled,
		&i.Capabilities,
		&i.CapabilitySchemaVersion,
		&i.CredentialRef,
		&i.Config,
		&i.OauthAccessExpiresAt,
		&i.OauthRefreshStatus,
		&i.RevokedAt,
		&i.LastVerifiedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrReadinessStatus,
		&i.PrReadinessCheckedAt,
		&i.PrReadinessDetail,
	)
	return i, err
}

const findReusableGitHubInstallation = `-- name: FindReusableGitHubInstallation :one
select coalesce(pc.config ->> 'installation_id', '')::text as installation_id
from publisher_connections pc
join projects p on p.id = pc.project_id
where p.owner_id = (select owner.owner_id from projects owner where owner.id = $1)
  and pc.project_id <> $1
  and pc.kind = 'github_nextjs'
  and coalesce(pc.config ->> 'installation_id', '') <> ''
order by pc.updated_at desc
limit 1
`

// FindReusableGitHubInstallation returns a GitHub App installation_id already
// linked by ANOTHER project of the SAME owner. A GitHub App installs once per
// account, so a second project can reuse the existing installation instead of
// re-running the install flow (which dead-ends on GitHub's "already installed"
// page). Scoped to the current project's owner so it never crosses tenants.
func (q *Queries) FindReusableGitHubInstallation(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, findReusableGitHubInstallation, id)
	var installation_id string
	err := row.Scan(&installation_id)
	return installation_id, err
}

const getActivePublisherCredential = `-- name: GetActivePublisherCredential :one
select id, project_id, connection_id, kind, encrypted_value, redacted_value, created_at, updated_at, revoked_at from publisher_credentials
where id = $1
  and project_id = $2
  and connection_id = $3
  and revoked_at is null
`

type GetActivePublisherCredentialParams struct {
	ID           uuid.UUID `json:"id"`
	ProjectID    uuid.UUID `json:"project_id"`
	ConnectionID uuid.UUID `json:"connection_id"`
}

func (q *Queries) GetActivePublisherCredential(ctx context.Context, arg GetActivePublisherCredentialParams) (PublisherCredential, error) {
	row := q.db.QueryRow(ctx, getActivePublisherCredential, arg.ID, arg.ProjectID, arg.ConnectionID)
	var i PublisherCredential
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ConnectionID,
		&i.Kind,
		&i.EncryptedValue,
		&i.RedactedValue,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActivePublisherCredentialForConnection = `-- name: GetActivePublisherCredentialForConnection :one
select id, project_id, connection_id, kind, encrypted_value, redacted_value, created_at, updated_at, revoked_at from publisher_credentials
where project_id = $1
  and connection_id = $2
  and kind = $3
  and revoked_at is null
limit 1
`

type GetActivePublisherCredentialForConnectionParams struct {
	ProjectID    uuid.UUID `json:"project_id"`
	ConnectionID uuid.UUID `json:"connection_id"`
	Kind         string    `json:"kind"`
}

func (q *Queries) GetActivePublisherCredentialForConnection(ctx context.Context, arg GetActivePublisherCredentialForConnectionParams) (PublisherCredential, error) {
	row := q.db.QueryRow(ctx, getActivePublisherCredentialForConnection, arg.ProjectID, arg.ConnectionID, arg.Kind)
	var i PublisherCredential
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ConnectionID,
		&i.Kind,
		&i.EncryptedValue,
		&i.RedactedValue,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getDefaultPublisherConnectionForProject = `-- name: GetDefaultPublisherConnectionForProject :one
select id, project_id, kind, label, status, is_default, enabled, capabilities, capability_schema_version, credential_ref, config, oauth_access_expires_at, oauth_refresh_status, revoked_at, last_verified_at, last_error, created_at, updated_at, pr_readiness_status, pr_readiness_checked_at, pr_readiness_detail from publisher_connections
where project_id = $1 and kind = $2 and is_default
limit 1
`

type GetDefaultPublisherConnectionForProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Kind      string    `json:"kind"`
}

func (q *Queries) GetDefaultPublisherConnectionForProject(ctx context.Context, arg GetDefaultPublisherConnectionForProjectParams) (PublisherConnection, error) {
	row := q.db.QueryRow(ctx, getDefaultPublisherConnectionForProject, arg.ProjectID, arg.Kind)
	var i PublisherConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Label,
		&i.Status,
		&i.IsDefault,
		&i.Enabled,
		&i.Capabilities,
		&i.CapabilitySchemaVersion,
		&i.CredentialRef,
		&i.Config,
		&i.OauthAccessExpiresAt,
		&i.OauthRefreshStatus,
		&i.RevokedAt,
		&i.LastVerifiedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrReadinessStatus,
		&i.PrReadinessCheckedAt,
		&i.PrReadinessDetail,
	)
	return i, err
}

const getEnabledPublisherConnectionForProject = `-- name: GetEnabledPublisherConnectionForProject :one
select id, project_id, kind, label, status, is_default, enabled, capabilities, capability_schema_version, credential_ref, config, oauth_access_expires_at, oauth_refresh_status, revoked_at, last_verified_at, last_error, created_at, updated_at, pr_readiness_status, pr_readiness_checked_at, pr_readiness_detail from publisher_connections
where project_id = $1
  and kind = $2
  and is_default
  and enabled = true
  and status = 'connected'
limit 1
`

type GetEnabledPublisherConnectionForProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Kind      string    `json:"kind"`
}

func (q *Queries) GetEnabledPublisherConnectionForProject(ctx context.Context, arg GetEnabledPublisherConnectionForProjectParams) (PublisherConnection, error) {
	row := q.db.QueryRow(ctx, getEnabledPublisherConnectionForProject, arg.ProjectID, arg.Kind)
	var i PublisherConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Label,
		&i.Status,
		&i.IsDefault,
		&i.Enabled,
		&i.Capabilities,
		&i.CapabilitySchemaVersion,
		&i.CredentialRef,
		&i.Config,
		&i.OauthAccessExpiresAt,
		&i.OauthRefreshStatus,
		&i.RevokedAt,
		&i.LastVerifiedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrReadinessStatus,
		&i.PrReadinessCheckedAt,
		&i.PrReadinessDetail,
	)
	return i, err
}

const getGitHubPRReadinessForProject = `-- name: GetGitHubPRReadinessForProject :one
select id, project_id, kind, label, status, is_default, enabled, capabilities, capability_schema_version, credential_ref, config, oauth_access_expires_at, oauth_refresh_status, revoked_at, last_verified_at, last_error, created_at, updated_at, pr_readiness_status, pr_readiness_checked_at, pr_readiness_detail from publisher_connections
where project_id = $1
  and kind = 'github_nextjs'
  and is_default
limit 1
`

func (q *Queries) GetGitHubPRReadinessForProject(ctx context.Context, projectID uuid.UUID) (PublisherConnection, error) {
	row := q.db.QueryRow(ctx, getGitHubPRReadinessForProject, projectID)
	var i PublisherConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Label,
		&i.Status,
		&i.IsDefault,
		&i.Enabled,
		&i.Capabilities,
		&i.CapabilitySchemaVersion,
		&i.CredentialRef,
		&i.Config,
		&i.OauthAccessExpiresAt,
		&i.OauthRefreshStatus,
		&i.RevokedAt,
		&i.LastVerifiedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrReadinessStatus,
		&i.PrReadinessCheckedAt,
		&i.PrReadinessDetail,
	)
	return i, err
}

const getPublisherConnectionForProject = `-- name: GetPublisherConnectionForProject :one
select id, project_id, kind, label, status, is_default, enabled, capabilities, capability_schema_version, credential_ref, config, oauth_access_expires_at, oauth_refresh_status, revoked_at, last_verified_at, last_error, created_at, updated_at, pr_readiness_status, pr_readiness_checked_at, pr_readiness_detail from publisher_connections
where id = $1 and project_id = $2
`

type GetPublisherConnectionForProjectParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetPublisherConnectionForProject(ctx context.Context, arg GetPublisherConnectionForProjectParams) (PublisherConnection, error) {
	row := q.db.QueryRow(ctx, getPublisherConnectionForProject, arg.ID, arg.ProjectID)
	var i PublisherConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Label,
		&i.Status,
		&i.IsDefault,
		&i.Enabled,
		&i.Capabilities,
		&i.CapabilitySchemaVersion,
		&i.CredentialRef,
		&i.Config,
		&i.OauthAccessExpiresAt,
		&i.OauthRefreshStatus,
		&i.RevokedAt,
		&i.LastVerifiedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrReadinessStatus,
		&i.PrReadinessCheckedAt,
		&i.PrReadinessDetail,
	)
	return i, err
}

const listPublisherConnections = `-- name: ListPublisherConnections :many
select id, project_id, kind, label, status, is_default, enabled, capabilities, capability_schema_version, credential_ref, config, oauth_access_expires_at, oauth_refresh_status, revoked_at, last_verified_at, last_error, created_at, updated_at, pr_readiness_status, pr_readiness_checked_at, pr_readiness_detail from publisher_connections
where project_id = $1
order by is_default desc, created_at desc
`

func (q *Queries) ListPublisherConnections(ctx context.Context, projectID uuid.UUID) ([]PublisherConnection, error) {
	rows, err := q.db.Query(ctx, listPublisherConnections, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublisherConnection
	for rows.Next() {
		var i PublisherConnection
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Label,
			&i.Status,
			&i.IsDefault,
			&i.Enabled,
			&i.Capabilities,
			&i.CapabilitySchemaVersion,
			&i.CredentialRef,
			&i.Config,
			&i.OauthAccessExpiresAt,
			&i.OauthRefreshStatus,
			&i.RevokedAt,
			&i.LastVerifiedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrReadinessStatus,
			&i.PrReadinessCheckedAt,
			&i.PrReadinessDetail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPublisherConnectionError = `-- name: MarkPublisherConnectionError :one
update publisher_connections
set status = 'error',
    last_error = $3,
    pr_readiness_status = 'not_connected',
    pr_readiness_checked_at = null,
    pr_readiness_detail = null,
    updated_at = now()
where id = $1 and project_id = $2
returning id, project_id, kind, label, status, is_default, enabled, capabilities, capability_schema_version, credential_ref, config, oauth_access_expires_at, oauth_refresh_status, revoked_at, last_verified_at, last_error, created_at, updated_at, pr_readiness_status, pr_readiness_checked_at, pr_readiness_detail
`

type MarkPublisherConnectionErrorParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	LastError *string   `json:"last_error"`
}

func (q *Queries) MarkPublisherConnectionError(ctx context.Context, arg MarkPublisherConnectionErrorParams) (PublisherConnection, error) {
	row := q.db.QueryRow(ctx, markPublisherConnectionError, arg.ID, arg.ProjectID, arg.LastError)
	var i PublisherConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Label,
		&i.Status,
		&i.IsDefault,
		&i.Enabled,
		&i.Capabilities,
		&i.CapabilitySchemaVersion,
		&i.CredentialRef,
		&i.Config,
		&i.OauthAccessExpiresAt,
		&i.OauthRefreshStatus,
		&i.RevokedAt,
		&i.LastVerifiedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrReadinessStatus,
		&i.PrReadinessCheckedAt,
		&i.PrReadinessDetail,
	)
	return i, err
}

const markPublisherConnectionVerified = `-- name: MarkPublisherConnectionVerified :one
update publisher_connections
set status = 'connected',
    last_verified_at = now(),
    last_error = null,
    pr_readiness_status = case
      when kind = 'github_nextjs' and enabled then 'not_checked'
      else 'not_connected'
    end,
    pr_readiness_checked_at = null,
    pr_readiness_detail = null,
    updated_at = now()
where id = $1 and project_id = $2
returning id, project_id, kind, label, status, is_default, enabled, capabilities, capability_schema_version, credential_ref, config, oauth_access_expires_at, oauth_refresh_status, revoked_at, last_verified_at, last_error, created_at, updated_at, pr_readiness_status, pr_readiness_checked_at, pr_readiness_detail
`

type MarkPublisherConnectionVerifiedParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) MarkPublisherConnectionVerified(ctx context.Context, arg MarkPublisherConnectionVerifiedParams) (PublisherConnection, error) {
	row := q.db.QueryRow(ctx, markPublisherConnectionVerified, arg.ID, arg.ProjectID)
	var i PublisherConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Label,
		&i.Status,
		&i.IsDefault,
		&i.Enabled,
		&i.Capabilities,
		&i.CapabilitySchemaVersion,
		&i.CredentialRef,
		&i.Config,
		&i.OauthAccessExpiresAt,
		&i.OauthRefreshStatus,
		&i.RevokedAt,
		&i.LastVerifiedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrReadinessStatus,
		&i.PrReadinessCheckedAt,
		&i.PrReadinessDetail,
	)
	return i, err
}

const revokePublisherCredentialForConnection = `-- name: RevokePublisherCredentialForConnection :one
with invalidated_connection as (
  update publisher_connections connection
  set pr_readiness_status = case
        when connection.kind = 'github_nextjs'
          and connection.status = 'connected'
          and connection.enabled then 'not_checked'
        else 'not_connected'
      end,
      pr_readiness_checked_at = null,
      pr_readiness_detail = null,
      updated_at = now()
  where connection.id = $2
    and connection.project_id = $3
    and exists (
      select 1
      from publisher_credentials credential
      where credential.project_id = connection.project_id
        and credential.connection_id = connection.id
        and credential.kind = $1
        and credential.revoked_at is null
    )
  returning connection.id, connection.project_id
)
update publisher_credentials credential
set revoked_at = now(),
    updated_at = now()
from invalidated_connection connection
where credential.project_id = connection.project_id
  and credential.connection_id = connection.id
  and credential.kind = $1
  and credential.revoked_at is null
returning credential.id, credential.project_id, credential.connection_id, credential.kind, credential.encrypted_value, credential.redacted_value, credential.created_at, credential.updated_at, credential.revoked_at
`

type RevokePublisherCredentialForConnectionParams struct {
	Kind         string    `json:"kind"`
	ConnectionID uuid.UUID `json:"connection_id"`
	ProjectID    uuid.UUID `json:"project_id"`
}

func (q *Queries) RevokePublisherCredentialForConnection(ctx context.Context, arg RevokePublisherCredentialForConnectionParams) (PublisherCredential, error) {
	row := q.db.QueryRow(ctx, revokePublisherCredentialForConnection, arg.Kind, arg.ConnectionID, arg.ProjectID)
	var i PublisherCredential
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ConnectionID,
		&i.Kind,
		&i.EncryptedValue,
		&i.RedactedValue,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const setGitHubPRReadinessIfUnchanged = `-- name: SetGitHubPRReadinessIfUnchanged :one
update publisher_connections
set pr_readiness_status = $1,
    pr_readiness_checked_at = $2,
    pr_readiness_detail = $3
where id = $4
  and project_id = $5
  and kind = 'github_nextjs'
  and is_default
  and updated_at = $6
  and $2::timestamptz is not null
  and (
    publisher_connections.pr_readiness_checked_at is null
    or publisher_connections.pr_readiness_checked_at < $2::timestamptz
  )
returning id, project_id, kind, label, status, is_default, enabled, capabilities, capability_schema_version, credential_ref, config, oauth_access_expires_at, oauth_refresh_status, revoked_at, last_verified_at, last_error, created_at, updated_at, pr_readiness_status, pr_readiness_checked_at, pr_readiness_detail
`

type SetGitHubPRReadinessIfUnchangedParams struct {
	PrReadinessStatus    string             `json:"pr_readiness_status"`
	PrReadinessCheckedAt pgtype.Timestamptz `json:"pr_readiness_checked_at"`
	PrReadinessDetail    *string            `json:"pr_readiness_detail"`
	ConnectionID         uuid.UUID          `json:"connection_id"`
	ProjectID            uuid.UUID          `json:"project_id"`
	ExpectedUpdatedAt    pgtype.Timestamptz `json:"expected_updated_at"`
}

func (q *Queries) SetGitHubPRReadinessIfUnchanged(ctx context.Context, arg SetGitHubPRReadinessIfUnchangedParams) (PublisherConnection, error) {
	row := q.db.QueryRow(ctx, setGitHubPRReadinessIfUnchanged,
		arg.PrReadinessStatus,
		arg.PrReadinessCheckedAt,
		arg.PrReadinessDetail,
		arg.ConnectionID,
		arg.ProjectID,
		arg.ExpectedUpdatedAt,
	)
	var i PublisherConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Label,
		&i.Status,
		&i.IsDefault,
		&i.Enabled,
		&i.Capabilities,
		&i.CapabilitySchemaVersion,
		&i.CredentialRef,
		&i.Config,
		&i.OauthAccessExpiresAt,
		&i.OauthRefreshStatus,
		&i.RevokedAt,
		&i.LastVerifiedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrReadinessStatus,
		&i.PrReadinessCheckedAt,
		&i.PrReadinessDetail,
	)
	return i, err
}

const setPublisherConnectionCredentialRef = `-- name: SetPublisherConnectionCredentialRef :one
update publisher_connections
set credential_ref = $3,
    status = 'missing',
    last_error = null,
    pr_readiness_status = 'not_connected',
    pr_readiness_checked_at = null,
    pr_readiness_detail = null,
    updated_at = now()
where id = $1 and project_id = $2
returning id, project_id, kind, label, status, is_default, enabled, capabilities, capability_schema_version, credential_ref, config, oauth_access_expires_at, oauth_refresh_status, revoked_at, last_verified_at, last_error, created_at, updated_at, pr_readiness_status, pr_readiness_checked_at, pr_readiness_detail
`

type SetPublisherConnectionCredentialRefParams struct {
	ID            uuid.UUID `json:"id"`
	ProjectID     uuid.UUID `json:"project_id"`
	CredentialRef *string   `json:"credential_ref"`
}

func (q *Queries) SetPublisherConnectionCredentialRef(ctx context.Context, arg SetPublisherConnectionCredentialRefParams) (PublisherConnection, error) {
	row := q.db.QueryRow(ctx, setPublisherConnectionCredentialRef, arg.ID, arg.ProjectID, arg.CredentialRef)
	var i PublisherConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Label,
		&i.Status,
		&i.IsDefault,
		&i.Enabled,
		&i.Capabilities,
		&i.CapabilitySchemaVersion,
		&i.CredentialRef,
		&i.Config,
		&i.OauthAccessExpiresAt,
		&i.OauthRefreshStatus,
		&i.RevokedAt,
		&i.LastVerifiedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrReadinessStatus,
		&i.PrReadinessCheckedAt,
		&i.PrReadinessDetail,
	)
	return i, err
}

const setPublisherConnectionEnabled = `-- name: SetPublisherConnectionEnabled :one
update publisher_connections
set enabled = $3,
    pr_readiness_status = case
      when kind = 'github_nextjs' and status = 'connected' and $3 then 'not_checked'
      else 'not_connected'
    end,
    pr_readiness_checked_at = null,
    pr_readiness_detail = null,
    updated_at = now()
where id = $1 and project_id = $2
returning id, project_id, kind, label, status, is_default, enabled, capabilities, capability_schema_version, credential_ref, config, oauth_access_expires_at, oauth_refresh_status, revoked_at, last_verified_at, last_error, created_at, updated_at, pr_readiness_status, pr_readiness_checked_at, pr_readiness_detail
`

type SetPublisherConnectionEnabledParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	Enabled   bool      `json:"enabled"`
}

func (q *Queries) SetPublisherConnectionEnabled(ctx context.Context, arg SetPublisherConnectionEnabledParams) (PublisherConnection, error) {
	row := q.db.QueryRow(ctx, setPublisherConnectionEnabled, arg.ID, arg.ProjectID, arg.Enabled)
	var i PublisherConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Label,
		&i.Status,
		&i.IsDefault,
		&i.Enabled,
		&i.Capabilities,
		&i.CapabilitySchemaVersion,
		&i.CredentialRef,
		&i.Config,
		&i.OauthAccessExpiresAt,
		&i.OauthRefreshStatus,
		&i.RevokedAt,
		&i.LastVerifiedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrReadinessStatus,
		&i.PrReadinessCheckedAt,
		&i.PrReadinessDetail,
	)
	return i, err
}

const upsertDefaultPublisherConnection = `-- name: UpsertDefaultPublisherConnection :one
insert into publisher_connections
  (project_id, kind, label, status, is_default, capabilities, capability_schema_version, credential_ref, config, last_verified_at, last_error)
values
  ($1, $2, $3, $4, true, $5, $6, $7, $8, $9, $10)
on conflict (project_id, kind) where is_default
do update set
  label = excluded.label,
  status = excluded.status,
  capabilities = excluded.capabilities,
  capability_schema_version = excluded.capability_schema_version,
  credential_ref = excluded.credential_ref,
  config = excluded.config,
  last_verified_at = excluded.last_verified_at,
  last_error = excluded.last_error,
  pr_readiness_status = case
    when publisher_connections.kind = 'github_nextjs'
      and excluded.status = 'connected'
      and publisher_connections.enabled then 'not_checked'
    else 'not_connected'
  end,
  pr_readiness_checked_at = null,
  pr_readiness_detail = null,
  updated_at = now()
returning id, project_id, kind, label, status, is_default, enabled, capabilities, capability_schema_version, credential_ref, config, oauth_access_expires_at, oauth_refresh_status, revoked_at, last_verified_at, last_error, created_at, updated_at, pr_readiness_status, pr_readiness_checked_at, pr_readiness_detail
`

type UpsertDefaultPublisherConnectionParams struct {
	ProjectID               uuid.UUID          `json:"project_id"`
	Kind                    string             `json:"kind"`
	Label                   string             `json:"label"`
	Status                  string             `json:"status"`
	Capabilities            json.RawMessage    `json:"capabilities"`
	CapabilitySchemaVersion int32              `json:"capability_schema_version"`
	CredentialRef           *string            `json:"credential_ref"`
	Config                  json.RawMessage    `json:"config"`
	LastVerifiedAt          pgtype.Timestamptz `json:"last_verified_at"`
	LastError               *string            `json:"last_error"`
}

func (q *Queries) UpsertDefaultPublisherConnection(ctx context.Context, arg UpsertDefaultPublisherConnectionParams) (PublisherConnection, error) {
	row := q.db.QueryRow(ctx, upsertDefaultPublisherConnection,
		arg.ProjectID,
		arg.Kind,
		arg.Label,
		arg.Status,
		arg.Capabilities,
		arg.CapabilitySchemaVersion,
		arg.CredentialRef,
		arg.Config,
		arg.LastVerifiedAt,
		arg.LastError,
	)
	var i PublisherConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Label,
		&i.Status,
		&i.IsDefault,
		&i.Enabled,
		&i.Capabilities,
		&i.CapabilitySchemaVersion,
		&i.CredentialRef,
		&i.Config,
		&i.OauthAccessExpiresAt,
		&i.OauthRefreshStatus,
		&i.RevokedAt,
		&i.LastVerifiedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrReadinessStatus,
		&i.PrReadinessCheckedAt,
		&i.PrReadinessDetail,
	)
	return i, err
}

const upsertPublisherCredential = `-- name: UpsertPublisherCredential :one
with invalidated_connection as (
  update publisher_connections
  set pr_readiness_status = case
        when kind = 'github_nextjs' and status = 'connected' and enabled then 'not_checked'
        else 'not_connected'
      end,
      pr_readiness_checked_at = null,
      pr_readiness_detail = null,
      updated_at = now()
  where id = $2
    and project_id = $1
  returning id, project_id
)
insert into publisher_credentials
  (project_id, connection_id, kind, encrypted_value, redacted_value)
select
  $1,
  $2,
  $3,
  $4,
  $5
from invalidated_connection
where true
on conflict (project_id, connection_id, kind)
do update set
  encrypted_value = excluded.encrypted_value,
  redacted_value = excluded.redacted_value,
  revoked_at = null,
  updated_at = now()
returning id, project_id, connection_id, kind, encrypted_value, redacted_value, created_at, updated_at, revoked_at
`

type UpsertPublisherCredentialParams struct {
	ProjectID      uuid.UUID `json:"project_id"`
	ConnectionID   uuid.UUID `json:"connection_id"`
	Kind           string    `json:"kind"`
	EncryptedValue string    `json:"encrypted_value"`
	RedactedValue  string    `json:"redacted_value"`
}

func (q *Queries) UpsertPublisherCredential(ctx context.Context, arg UpsertPublisherCredentialParams) (PublisherCredential, error) {
	row := q.db.QueryRow(ctx, upsertPublisherCredential,
		arg.ProjectID,
		arg.ConnectionID,
		arg.Kind,
		arg.EncryptedValue,
		arg.RedactedValue,
	)
	var i PublisherCredential
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ConnectionID,
		&i.Kind,
		&i.EncryptedValue,
		&i.RedactedValue,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}
