// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: publisher_connections.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDefaultPublisherConnectionForProject = `-- name: GetDefaultPublisherConnectionForProject :one
select id, project_id, kind, label, status, is_default, capabilities, capability_schema_version, credential_ref, config, oauth_access_expires_at, oauth_refresh_status, revoked_at, last_verified_at, last_error, created_at, updated_at from publisher_connections
where project_id = $1 and kind = $2 and is_default
limit 1
`

type GetDefaultPublisherConnectionForProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Kind      string    `json:"kind"`
}

func (q *Queries) GetDefaultPublisherConnectionForProject(ctx context.Context, arg GetDefaultPublisherConnectionForProjectParams) (PublisherConnection, error) {
	row := q.db.QueryRow(ctx, getDefaultPublisherConnectionForProject, arg.ProjectID, arg.Kind)
	var i PublisherConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Label,
		&i.Status,
		&i.IsDefault,
		&i.Capabilities,
		&i.CapabilitySchemaVersion,
		&i.CredentialRef,
		&i.Config,
		&i.OauthAccessExpiresAt,
		&i.OauthRefreshStatus,
		&i.RevokedAt,
		&i.LastVerifiedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublisherConnectionForProject = `-- name: GetPublisherConnectionForProject :one
select id, project_id, kind, label, status, is_default, capabilities, capability_schema_version, credential_ref, config, oauth_access_expires_at, oauth_refresh_status, revoked_at, last_verified_at, last_error, created_at, updated_at from publisher_connections
where id = $1 and project_id = $2
`

type GetPublisherConnectionForProjectParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetPublisherConnectionForProject(ctx context.Context, arg GetPublisherConnectionForProjectParams) (PublisherConnection, error) {
	row := q.db.QueryRow(ctx, getPublisherConnectionForProject, arg.ID, arg.ProjectID)
	var i PublisherConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Label,
		&i.Status,
		&i.IsDefault,
		&i.Capabilities,
		&i.CapabilitySchemaVersion,
		&i.CredentialRef,
		&i.Config,
		&i.OauthAccessExpiresAt,
		&i.OauthRefreshStatus,
		&i.RevokedAt,
		&i.LastVerifiedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublisherConnections = `-- name: ListPublisherConnections :many
select id, project_id, kind, label, status, is_default, capabilities, capability_schema_version, credential_ref, config, oauth_access_expires_at, oauth_refresh_status, revoked_at, last_verified_at, last_error, created_at, updated_at from publisher_connections
where project_id = $1
order by is_default desc, created_at desc
`

func (q *Queries) ListPublisherConnections(ctx context.Context, projectID uuid.UUID) ([]PublisherConnection, error) {
	rows, err := q.db.Query(ctx, listPublisherConnections, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublisherConnection
	for rows.Next() {
		var i PublisherConnection
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Label,
			&i.Status,
			&i.IsDefault,
			&i.Capabilities,
			&i.CapabilitySchemaVersion,
			&i.CredentialRef,
			&i.Config,
			&i.OauthAccessExpiresAt,
			&i.OauthRefreshStatus,
			&i.RevokedAt,
			&i.LastVerifiedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPublisherConnectionError = `-- name: MarkPublisherConnectionError :one
update publisher_connections
set status = 'error',
    last_error = $3,
    updated_at = now()
where id = $1 and project_id = $2
returning id, project_id, kind, label, status, is_default, capabilities, capability_schema_version, credential_ref, config, oauth_access_expires_at, oauth_refresh_status, revoked_at, last_verified_at, last_error, created_at, updated_at
`

type MarkPublisherConnectionErrorParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	LastError *string   `json:"last_error"`
}

func (q *Queries) MarkPublisherConnectionError(ctx context.Context, arg MarkPublisherConnectionErrorParams) (PublisherConnection, error) {
	row := q.db.QueryRow(ctx, markPublisherConnectionError, arg.ID, arg.ProjectID, arg.LastError)
	var i PublisherConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Label,
		&i.Status,
		&i.IsDefault,
		&i.Capabilities,
		&i.CapabilitySchemaVersion,
		&i.CredentialRef,
		&i.Config,
		&i.OauthAccessExpiresAt,
		&i.OauthRefreshStatus,
		&i.RevokedAt,
		&i.LastVerifiedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPublisherConnectionVerified = `-- name: MarkPublisherConnectionVerified :one
update publisher_connections
set status = 'connected',
    last_verified_at = now(),
    last_error = null,
    updated_at = now()
where id = $1 and project_id = $2
returning id, project_id, kind, label, status, is_default, capabilities, capability_schema_version, credential_ref, config, oauth_access_expires_at, oauth_refresh_status, revoked_at, last_verified_at, last_error, created_at, updated_at
`

type MarkPublisherConnectionVerifiedParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) MarkPublisherConnectionVerified(ctx context.Context, arg MarkPublisherConnectionVerifiedParams) (PublisherConnection, error) {
	row := q.db.QueryRow(ctx, markPublisherConnectionVerified, arg.ID, arg.ProjectID)
	var i PublisherConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Label,
		&i.Status,
		&i.IsDefault,
		&i.Capabilities,
		&i.CapabilitySchemaVersion,
		&i.CredentialRef,
		&i.Config,
		&i.OauthAccessExpiresAt,
		&i.OauthRefreshStatus,
		&i.RevokedAt,
		&i.LastVerifiedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDefaultPublisherConnection = `-- name: UpsertDefaultPublisherConnection :one
insert into publisher_connections
  (project_id, kind, label, status, is_default, capabilities, capability_schema_version, credential_ref, config, last_verified_at, last_error)
values
  ($1, $2, $3, $4, true, $5, $6, $7, $8, $9, $10)
on conflict (project_id, kind) where is_default
do update set
  label = excluded.label,
  status = excluded.status,
  capabilities = excluded.capabilities,
  capability_schema_version = excluded.capability_schema_version,
  credential_ref = excluded.credential_ref,
  config = excluded.config,
  last_verified_at = excluded.last_verified_at,
  last_error = excluded.last_error,
  updated_at = now()
returning id, project_id, kind, label, status, is_default, capabilities, capability_schema_version, credential_ref, config, oauth_access_expires_at, oauth_refresh_status, revoked_at, last_verified_at, last_error, created_at, updated_at
`

type UpsertDefaultPublisherConnectionParams struct {
	ProjectID               uuid.UUID          `json:"project_id"`
	Kind                    string             `json:"kind"`
	Label                   string             `json:"label"`
	Status                  string             `json:"status"`
	Capabilities            json.RawMessage    `json:"capabilities"`
	CapabilitySchemaVersion int32              `json:"capability_schema_version"`
	CredentialRef           *string            `json:"credential_ref"`
	Config                  json.RawMessage    `json:"config"`
	LastVerifiedAt          pgtype.Timestamptz `json:"last_verified_at"`
	LastError               *string            `json:"last_error"`
}

func (q *Queries) UpsertDefaultPublisherConnection(ctx context.Context, arg UpsertDefaultPublisherConnectionParams) (PublisherConnection, error) {
	row := q.db.QueryRow(ctx, upsertDefaultPublisherConnection,
		arg.ProjectID,
		arg.Kind,
		arg.Label,
		arg.Status,
		arg.Capabilities,
		arg.CapabilitySchemaVersion,
		arg.CredentialRef,
		arg.Config,
		arg.LastVerifiedAt,
		arg.LastError,
	)
	var i PublisherConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Label,
		&i.Status,
		&i.IsDefault,
		&i.Capabilities,
		&i.CapabilitySchemaVersion,
		&i.CredentialRef,
		&i.Config,
		&i.OauthAccessExpiresAt,
		&i.OauthRefreshStatus,
		&i.RevokedAt,
		&i.LastVerifiedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
