// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ApproveArticle(ctx context.Context, arg ApproveArticleParams) (Article, error)
	CountNonRejectedArticlesForTopic(ctx context.Context, topicID uuid.UUID) (int64, error)
	// CountStockedCanonical counts canonical articles already in flight toward
	// publishing (not backlog, not terminal). The scheduler uses this to fill only
	// the buffer-window deficit instead of regenerating every tick (§5.4).
	CountStockedCanonical(ctx context.Context, projectID uuid.UUID) (int64, error)
	CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error)
	DeactivateProfiles(ctx context.Context, projectID uuid.UUID) error
	DeleteInventoryItem(ctx context.Context, id uuid.UUID) error
	GetActiveProfile(ctx context.Context, projectID uuid.UUID) (ProductProfile, error)
	GetArticle(ctx context.Context, id uuid.UUID) (Article, error)
	GetInventoryItem(ctx context.Context, id uuid.UUID) (ContentInventory, error)
	GetProject(ctx context.Context, id uuid.UUID) (Project, error)
	GetProjectBySlug(ctx context.Context, slug string) (Project, error)
	GetTopic(ctx context.Context, id uuid.UUID) (Topic, error)
	InsertGenerationRun(ctx context.Context, arg InsertGenerationRunParams) (GenerationRun, error)
	InsertProfile(ctx context.Context, arg InsertProfileParams) (ProductProfile, error)
	ListArticlesByStatus(ctx context.Context, arg ListArticlesByStatusParams) ([]Article, error)
	ListArticlesByTopic(ctx context.Context, topicID uuid.UUID) ([]Article, error)
	ListInventory(ctx context.Context, projectID uuid.UUID) ([]ContentInventory, error)
	ListPendingReview(ctx context.Context, projectID uuid.UUID) ([]Article, error)
	ListProfileVersions(ctx context.Context, projectID uuid.UUID) ([]ProductProfile, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListTopics(ctx context.Context, projectID uuid.UUID) ([]Topic, error)
	MarkDistributed(ctx context.Context, id uuid.UUID) (Article, error)
	MarkPublished(ctx context.Context, arg MarkPublishedParams) (Article, error)
	// Cumulative cost for the current calendar month (cost breaker basis, §5.4).
	MonthlySpend(ctx context.Context, projectID uuid.UUID) (pgtype.Numeric, error)
	NextProfileVersion(ctx context.Context, projectID uuid.UUID) (int32, error)
	// Consecutive failures heuristic for alerting (§5.2/§5.4).
	RecentRunFailures(ctx context.Context, arg RecentRunFailuresParams) (int64, error)
	RejectArticle(ctx context.Context, arg RejectArticleParams) (Article, error)
	// Publisher: canonical articles due for auto-publish (§5.6).
	SelectDueCanonical(ctx context.Context, projectID uuid.UUID) ([]Article, error)
	// Scheduler candidate selection: backlog/scheduled topics with a slot inside the
	// buffer window, locked to avoid concurrent double-generation (§5.4).
	SelectGenerationCandidates(ctx context.Context, arg SelectGenerationCandidatesParams) ([]Topic, error)
	// syndication unlock: variants whose canonical is published (§5.6).
	SelectUnlockableVariants(ctx context.Context) ([]Article, error)
	SetArticleQA(ctx context.Context, arg SetArticleQAParams) (Article, error)
	SetTopicScheduledAt(ctx context.Context, arg SetTopicScheduledAtParams) (Topic, error)
	UnlockVariant(ctx context.Context, arg UnlockVariantParams) (Article, error)
	UpdateArticleContent(ctx context.Context, arg UpdateArticleContentParams) (Article, error)
	UpdateInventoryItem(ctx context.Context, arg UpdateInventoryItemParams) (ContentInventory, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (ProductProfile, error)
	UpdateProjectConfig(ctx context.Context, arg UpdateProjectConfigParams) (Project, error)
	UpdateTopicStatus(ctx context.Context, arg UpdateTopicStatusParams) (Topic, error)
	UpsertInventory(ctx context.Context, arg UpsertInventoryParams) (ContentInventory, error)
}

var _ Querier = (*Queries)(nil)
