// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getGenerationRun = `-- name: GetGenerationRun :one
select id, project_id, agent, input, output, model, tokens, cost_usd, status, error, created_at from generation_runs
where id = $1
  and project_id = $2
`

type GetGenerationRunParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetGenerationRun(ctx context.Context, arg GetGenerationRunParams) (GenerationRun, error) {
	row := q.db.QueryRow(ctx, getGenerationRun, arg.ID, arg.ProjectID)
	var i GenerationRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Agent,
		&i.Input,
		&i.Output,
		&i.Model,
		&i.Tokens,
		&i.CostUsd,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const insertGenerationRun = `-- name: InsertGenerationRun :one
insert into generation_runs
  (project_id, agent, input, output, model, tokens, cost_usd, status, error)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
returning id, project_id, agent, input, output, model, tokens, cost_usd, status, error, created_at
`

type InsertGenerationRunParams struct {
	ProjectID uuid.UUID      `json:"project_id"`
	Agent     string         `json:"agent"`
	Input     []byte         `json:"input"`
	Output    []byte         `json:"output"`
	Model     *string        `json:"model"`
	Tokens    *int32         `json:"tokens"`
	CostUsd   pgtype.Numeric `json:"cost_usd"`
	Status    string         `json:"status"`
	Error     *string        `json:"error"`
}

func (q *Queries) InsertGenerationRun(ctx context.Context, arg InsertGenerationRunParams) (GenerationRun, error) {
	row := q.db.QueryRow(ctx, insertGenerationRun,
		arg.ProjectID,
		arg.Agent,
		arg.Input,
		arg.Output,
		arg.Model,
		arg.Tokens,
		arg.CostUsd,
		arg.Status,
		arg.Error,
	)
	var i GenerationRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Agent,
		&i.Input,
		&i.Output,
		&i.Model,
		&i.Tokens,
		&i.CostUsd,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const listGenerationRuns = `-- name: ListGenerationRuns :many
select id, project_id, agent, input, output, model, tokens, cost_usd, status, error, created_at from generation_runs
where project_id = $1
  and ($2::text = '' or agent = $2)
  and ($3::text = '' or status = $3)
  and ($4::timestamptz is null or created_at < $4)
order by created_at desc
limit $5
`

type ListGenerationRunsParams struct {
	ProjectID       uuid.UUID          `json:"project_id"`
	Agent           string             `json:"agent"`
	Status          string             `json:"status"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	LimitRows       int32              `json:"limit_rows"`
}

func (q *Queries) ListGenerationRuns(ctx context.Context, arg ListGenerationRunsParams) ([]GenerationRun, error) {
	rows, err := q.db.Query(ctx, listGenerationRuns,
		arg.ProjectID,
		arg.Agent,
		arg.Status,
		arg.CursorCreatedAt,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GenerationRun
	for rows.Next() {
		var i GenerationRun
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Agent,
			&i.Input,
			&i.Output,
			&i.Model,
			&i.Tokens,
			&i.CostUsd,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthlySpend = `-- name: MonthlySpend :one
select coalesce(sum(cost_usd), 0)::numeric from generation_runs
where project_id = $1
  and status = 'ok'
  and created_at >= date_trunc('month', now())
`

// Cumulative cost for the current calendar month (cost breaker basis, §5.4).
func (q *Queries) MonthlySpend(ctx context.Context, projectID uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, monthlySpend, projectID)
	var column_1 pgtype.Numeric
	err := row.Scan(&column_1)
	return column_1, err
}

const recentRunFailures = `-- name: RecentRunFailures :one
select count(*) from (
  select status from generation_runs
  where project_id = $1 and agent = $2
  order by created_at desc
  limit $3
) recent
where status = 'error'
`

type RecentRunFailuresParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Agent     string    `json:"agent"`
	Limit     int32     `json:"limit"`
}

// Consecutive failures heuristic for alerting (§5.2/§5.4).
func (q *Queries) RecentRunFailures(ctx context.Context, arg RecentRunFailuresParams) (int64, error) {
	row := q.db.QueryRow(ctx, recentRunFailures, arg.ProjectID, arg.Agent, arg.Limit)
	var count int64
	err := row.Scan(&count)
	return count, err
}
