// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seo.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const contentActionCounts = `-- name: ContentActionCounts :many
select status, count(*)::bigint as count
from content_actions
where project_id = $1
group by status
order by status
`

type ContentActionCountsRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) ContentActionCounts(ctx context.Context, projectID uuid.UUID) ([]ContentActionCountsRow, error) {
	rows, err := q.db.Query(ctx, contentActionCounts, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentActionCountsRow
	for rows.Next() {
		var i ContentActionCountsRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createContentAction = `-- name: CreateContentAction :one
insert into content_actions
  (project_id, opportunity_id, action_type, status, target_article_id, target_url,
   normalized_target_url, target_content_hash_before, baseline_window, measurement_window)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
on conflict (project_id, opportunity_id, action_type) do update set
  status = excluded.status,
  target_article_id = excluded.target_article_id,
  target_url = excluded.target_url,
  normalized_target_url = excluded.normalized_target_url,
  target_content_hash_before = excluded.target_content_hash_before,
  baseline_window = excluded.baseline_window,
  measurement_window = excluded.measurement_window,
  updated_at = now()
returning id, project_id, opportunity_id, action_type, status, target_article_id, target_url, normalized_target_url, target_content_hash_before, target_content_hash_after, draft_article_id, baseline_window, measurement_window, published_at, outcome_summary, created_at, updated_at
`

type CreateContentActionParams struct {
	ProjectID               uuid.UUID       `json:"project_id"`
	OpportunityID           uuid.UUID       `json:"opportunity_id"`
	ActionType              string          `json:"action_type"`
	Status                  string          `json:"status"`
	TargetArticleID         pgtype.UUID     `json:"target_article_id"`
	TargetUrl               *string         `json:"target_url"`
	NormalizedTargetUrl     *string         `json:"normalized_target_url"`
	TargetContentHashBefore *string         `json:"target_content_hash_before"`
	BaselineWindow          json.RawMessage `json:"baseline_window"`
	MeasurementWindow       json.RawMessage `json:"measurement_window"`
}

func (q *Queries) CreateContentAction(ctx context.Context, arg CreateContentActionParams) (ContentAction, error) {
	row := q.db.QueryRow(ctx, createContentAction,
		arg.ProjectID,
		arg.OpportunityID,
		arg.ActionType,
		arg.Status,
		arg.TargetArticleID,
		arg.TargetUrl,
		arg.NormalizedTargetUrl,
		arg.TargetContentHashBefore,
		arg.BaselineWindow,
		arg.MeasurementWindow,
	)
	var i ContentAction
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OpportunityID,
		&i.ActionType,
		&i.Status,
		&i.TargetArticleID,
		&i.TargetUrl,
		&i.NormalizedTargetUrl,
		&i.TargetContentHashBefore,
		&i.TargetContentHashAfter,
		&i.DraftArticleID,
		&i.BaselineWindow,
		&i.MeasurementWindow,
		&i.PublishedAt,
		&i.OutcomeSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finishSEORun = `-- name: FinishSEORun :one
update seo_runs set
  status = $3,
  finished_at = $4,
  cost_usd = $5,
  output = $6,
  error = $7
where id = $1 and project_id = $2
returning id, project_id, agent, status, started_at, finished_at, cost_usd, input, output, error
`

type FinishSEORunParams struct {
	ID         uuid.UUID          `json:"id"`
	ProjectID  uuid.UUID          `json:"project_id"`
	Status     string             `json:"status"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	CostUsd    pgtype.Numeric     `json:"cost_usd"`
	Output     json.RawMessage    `json:"output"`
	Error      *string            `json:"error"`
}

func (q *Queries) FinishSEORun(ctx context.Context, arg FinishSEORunParams) (SeoRun, error) {
	row := q.db.QueryRow(ctx, finishSEORun,
		arg.ID,
		arg.ProjectID,
		arg.Status,
		arg.FinishedAt,
		arg.CostUsd,
		arg.Output,
		arg.Error,
	)
	var i SeoRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Agent,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CostUsd,
		&i.Input,
		&i.Output,
		&i.Error,
	)
	return i, err
}

const getContentAction = `-- name: GetContentAction :one
select id, project_id, opportunity_id, action_type, status, target_article_id, target_url, normalized_target_url, target_content_hash_before, target_content_hash_after, draft_article_id, baseline_window, measurement_window, published_at, outcome_summary, created_at, updated_at from content_actions
where id = $1 and project_id = $2
`

type GetContentActionParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetContentAction(ctx context.Context, arg GetContentActionParams) (ContentAction, error) {
	row := q.db.QueryRow(ctx, getContentAction, arg.ID, arg.ProjectID)
	var i ContentAction
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OpportunityID,
		&i.ActionType,
		&i.Status,
		&i.TargetArticleID,
		&i.TargetUrl,
		&i.NormalizedTargetUrl,
		&i.TargetContentHashBefore,
		&i.TargetContentHashAfter,
		&i.DraftArticleID,
		&i.BaselineWindow,
		&i.MeasurementWindow,
		&i.PublishedAt,
		&i.OutcomeSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSEOOpportunity = `-- name: GetSEOOpportunity :one
select id, project_id, type, status, priority_score, confidence, page_url, normalized_page_url, article_id, topic_id, query, evidence, recommended_action, expected_impact, effort, risk_level, created_by_run_id, created_at, updated_at from seo_opportunities
where id = $1 and project_id = $2
`

type GetSEOOpportunityParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetSEOOpportunity(ctx context.Context, arg GetSEOOpportunityParams) (SeoOpportunity, error) {
	row := q.db.QueryRow(ctx, getSEOOpportunity, arg.ID, arg.ProjectID)
	var i SeoOpportunity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Status,
		&i.PriorityScore,
		&i.Confidence,
		&i.PageUrl,
		&i.NormalizedPageUrl,
		&i.ArticleID,
		&i.TopicID,
		&i.Query,
		&i.Evidence,
		&i.RecommendedAction,
		&i.ExpectedImpact,
		&i.Effort,
		&i.RiskLevel,
		&i.CreatedByRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSEOPropertyForProject = `-- name: GetSEOPropertyForProject :one
select id, project_id, site_url, gsc_site_url, ga4_property_id, url_normalization_config, default_country, default_language, created_at, updated_at from seo_properties
where project_id = $1
order by created_at asc
limit 1
`

func (q *Queries) GetSEOPropertyForProject(ctx context.Context, projectID uuid.UUID) (SeoProperty, error) {
	row := q.db.QueryRow(ctx, getSEOPropertyForProject, projectID)
	var i SeoProperty
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SiteUrl,
		&i.GscSiteUrl,
		&i.Ga4PropertyID,
		&i.UrlNormalizationConfig,
		&i.DefaultCountry,
		&i.DefaultLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSEORun = `-- name: InsertSEORun :one
insert into seo_runs
  (project_id, agent, status, started_at, finished_at, cost_usd, input, output, error)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
returning id, project_id, agent, status, started_at, finished_at, cost_usd, input, output, error
`

type InsertSEORunParams struct {
	ProjectID  uuid.UUID          `json:"project_id"`
	Agent      string             `json:"agent"`
	Status     string             `json:"status"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	CostUsd    pgtype.Numeric     `json:"cost_usd"`
	Input      json.RawMessage    `json:"input"`
	Output     json.RawMessage    `json:"output"`
	Error      *string            `json:"error"`
}

func (q *Queries) InsertSEORun(ctx context.Context, arg InsertSEORunParams) (SeoRun, error) {
	row := q.db.QueryRow(ctx, insertSEORun,
		arg.ProjectID,
		arg.Agent,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.CostUsd,
		arg.Input,
		arg.Output,
		arg.Error,
	)
	var i SeoRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Agent,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CostUsd,
		&i.Input,
		&i.Output,
		&i.Error,
	)
	return i, err
}

const listContentActions = `-- name: ListContentActions :many
select id, project_id, opportunity_id, action_type, status, target_article_id, target_url, normalized_target_url, target_content_hash_before, target_content_hash_after, draft_article_id, baseline_window, measurement_window, published_at, outcome_summary, created_at, updated_at from content_actions
where project_id = $1
  and ($2::text = '' or status = $2)
  and ($3::timestamptz is null or created_at < $3)
order by created_at desc
limit $4
`

type ListContentActionsParams struct {
	ProjectID       uuid.UUID          `json:"project_id"`
	Status          string             `json:"status"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	LimitRows       int32              `json:"limit_rows"`
}

func (q *Queries) ListContentActions(ctx context.Context, arg ListContentActionsParams) ([]ContentAction, error) {
	rows, err := q.db.Query(ctx, listContentActions,
		arg.ProjectID,
		arg.Status,
		arg.CursorCreatedAt,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentAction
	for rows.Next() {
		var i ContentAction
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OpportunityID,
			&i.ActionType,
			&i.Status,
			&i.TargetArticleID,
			&i.TargetUrl,
			&i.NormalizedTargetUrl,
			&i.TargetContentHashBefore,
			&i.TargetContentHashAfter,
			&i.DraftArticleID,
			&i.BaselineWindow,
			&i.MeasurementWindow,
			&i.PublishedAt,
			&i.OutcomeSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedCanonicalArticlesForSEO = `-- name: ListPublishedCanonicalArticlesForSEO :many
select id, project_id, topic_id, kind, platform, content_md, seo_meta, geo_score, seo_score, qa_issues, qa_blocking, canonical_url, status, scheduled_at, reviewed_by, reviewed_at, published_at, publish_result, last_publish_error, publish_attempts, next_publish_retry_at, publish_phase, resolved_slug, publish_path, canonical_url_verified_at, last_publish_run_id, created_at, content_hash from articles
where project_id = $1
  and kind = 'canonical'
  and status in ('published','pending_url_verification','publish_failed')
  and canonical_url is not null
order by published_at desc nulls last, created_at desc
`

func (q *Queries) ListPublishedCanonicalArticlesForSEO(ctx context.Context, projectID uuid.UUID) ([]Article, error) {
	rows, err := q.db.Query(ctx, listPublishedCanonicalArticlesForSEO, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TopicID,
			&i.Kind,
			&i.Platform,
			&i.ContentMd,
			&i.SeoMeta,
			&i.GeoScore,
			&i.SeoScore,
			&i.QaIssues,
			&i.QaBlocking,
			&i.CanonicalUrl,
			&i.Status,
			&i.ScheduledAt,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.PublishedAt,
			&i.PublishResult,
			&i.LastPublishError,
			&i.PublishAttempts,
			&i.NextPublishRetryAt,
			&i.PublishPhase,
			&i.ResolvedSlug,
			&i.PublishPath,
			&i.CanonicalUrlVerifiedAt,
			&i.LastPublishRunID,
			&i.CreatedAt,
			&i.ContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSEOIntegrations = `-- name: ListSEOIntegrations :many
select id, project_id, provider, status, credential_ref, last_verified_at, last_error, created_at, updated_at from seo_integrations
where project_id = $1
order by provider asc
`

func (q *Queries) ListSEOIntegrations(ctx context.Context, projectID uuid.UUID) ([]SeoIntegration, error) {
	rows, err := q.db.Query(ctx, listSEOIntegrations, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeoIntegration
	for rows.Next() {
		var i SeoIntegration
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Provider,
			&i.Status,
			&i.CredentialRef,
			&i.LastVerifiedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSEOOpportunities = `-- name: ListSEOOpportunities :many
select id, project_id, type, status, priority_score, confidence, page_url, normalized_page_url, article_id, topic_id, query, evidence, recommended_action, expected_impact, effort, risk_level, created_by_run_id, created_at, updated_at from seo_opportunities
where project_id = $1
  and ($2::text = '' or type = $2)
  and ($3::text = '' or status = $3)
  and ($4::timestamptz is null or created_at < $4)
order by priority_score desc, created_at desc
limit $5
`

type ListSEOOpportunitiesParams struct {
	ProjectID       uuid.UUID          `json:"project_id"`
	Type            string             `json:"type"`
	Status          string             `json:"status"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	LimitRows       int32              `json:"limit_rows"`
}

func (q *Queries) ListSEOOpportunities(ctx context.Context, arg ListSEOOpportunitiesParams) ([]SeoOpportunity, error) {
	rows, err := q.db.Query(ctx, listSEOOpportunities,
		arg.ProjectID,
		arg.Type,
		arg.Status,
		arg.CursorCreatedAt,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeoOpportunity
	for rows.Next() {
		var i SeoOpportunity
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Status,
			&i.PriorityScore,
			&i.Confidence,
			&i.PageUrl,
			&i.NormalizedPageUrl,
			&i.ArticleID,
			&i.TopicID,
			&i.Query,
			&i.Evidence,
			&i.RecommendedAction,
			&i.ExpectedImpact,
			&i.Effort,
			&i.RiskLevel,
			&i.CreatedByRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSEORuns = `-- name: ListSEORuns :many
select id, project_id, agent, status, started_at, finished_at, cost_usd, input, output, error from seo_runs
where project_id = $1
  and ($2::text = '' or agent = $2)
  and ($3::text = '' or status = $3)
  and ($4::timestamptz is null or started_at < $4)
order by started_at desc
limit $5
`

type ListSEORunsParams struct {
	ProjectID       uuid.UUID          `json:"project_id"`
	Agent           string             `json:"agent"`
	Status          string             `json:"status"`
	CursorStartedAt pgtype.Timestamptz `json:"cursor_started_at"`
	LimitRows       int32              `json:"limit_rows"`
}

func (q *Queries) ListSEORuns(ctx context.Context, arg ListSEORunsParams) ([]SeoRun, error) {
	rows, err := q.db.Query(ctx, listSEORuns,
		arg.ProjectID,
		arg.Agent,
		arg.Status,
		arg.CursorStartedAt,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeoRun
	for rows.Next() {
		var i SeoRun
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Agent,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CostUsd,
			&i.Input,
			&i.Output,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sEOOpportunityCounts = `-- name: SEOOpportunityCounts :many
select type, status, count(*)::bigint as count
from seo_opportunities
where project_id = $1
group by type, status
order by type, status
`

type SEOOpportunityCountsRow struct {
	Type   string `json:"type"`
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) SEOOpportunityCounts(ctx context.Context, projectID uuid.UUID) ([]SEOOpportunityCountsRow, error) {
	rows, err := q.db.Query(ctx, sEOOpportunityCounts, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SEOOpportunityCountsRow
	for rows.Next() {
		var i SEOOpportunityCountsRow
		if err := rows.Scan(&i.Type, &i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sEOOverviewStats = `-- name: SEOOverviewStats :one
select
  coalesce(sum(clicks) filter (where date >= current_date - interval '28 days'), 0)::numeric as clicks_28d,
  coalesce(sum(impressions) filter (where date >= current_date - interval '28 days'), 0)::numeric as impressions_28d,
  coalesce(avg(ctr) filter (where date >= current_date - interval '28 days'), 0)::numeric as ctr_28d,
  coalesce(avg(weighted_position) filter (where date >= current_date - interval '28 days'), 0)::numeric as position_28d,
  count(distinct date) filter (
    where date >= current_date - interval '28 days'
      and (clicks is not null or impressions is not null)
  )::bigint as gsc_days_28d
from page_performance_daily
where project_id = $1
`

type SEOOverviewStatsRow struct {
	Clicks28d      pgtype.Numeric `json:"clicks_28d"`
	Impressions28d pgtype.Numeric `json:"impressions_28d"`
	Ctr28d         pgtype.Numeric `json:"ctr_28d"`
	Position28d    pgtype.Numeric `json:"position_28d"`
	GscDays28d     int64          `json:"gsc_days_28d"`
}

func (q *Queries) SEOOverviewStats(ctx context.Context, projectID uuid.UUID) (SEOOverviewStatsRow, error) {
	row := q.db.QueryRow(ctx, sEOOverviewStats, projectID)
	var i SEOOverviewStatsRow
	err := row.Scan(
		&i.Clicks28d,
		&i.Impressions28d,
		&i.Ctr28d,
		&i.Position28d,
		&i.GscDays28d,
	)
	return i, err
}

const sEOTechnicalSummary = `-- name: SEOTechnicalSummary :one
select
  count(*)::bigint as checked_urls,
  count(*) filter (where http_status between 200 and 299)::bigint as ok_urls,
  count(*) filter (where http_status is null or http_status < 200 or http_status >= 300)::bigint as anomaly_urls
from technical_checks tc
join seo_runs sr on sr.id = tc.run_id
where tc.project_id = $1
  and sr.started_at = (
    select max(started_at) from seo_runs where project_id = $1 and agent = 'seo_sync'
  )
`

type SEOTechnicalSummaryRow struct {
	CheckedUrls int64 `json:"checked_urls"`
	OkUrls      int64 `json:"ok_urls"`
	AnomalyUrls int64 `json:"anomaly_urls"`
}

func (q *Queries) SEOTechnicalSummary(ctx context.Context, projectID uuid.UUID) (SEOTechnicalSummaryRow, error) {
	row := q.db.QueryRow(ctx, sEOTechnicalSummary, projectID)
	var i SEOTechnicalSummaryRow
	err := row.Scan(&i.CheckedUrls, &i.OkUrls, &i.AnomalyUrls)
	return i, err
}

const startSEORun = `-- name: StartSEORun :one
insert into seo_runs
  (project_id, agent, status, started_at, input)
values ($1, $2, 'degraded', $3, $4)
returning id, project_id, agent, status, started_at, finished_at, cost_usd, input, output, error
`

type StartSEORunParams struct {
	ProjectID uuid.UUID          `json:"project_id"`
	Agent     string             `json:"agent"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	Input     json.RawMessage    `json:"input"`
}

func (q *Queries) StartSEORun(ctx context.Context, arg StartSEORunParams) (SeoRun, error) {
	row := q.db.QueryRow(ctx, startSEORun,
		arg.ProjectID,
		arg.Agent,
		arg.StartedAt,
		arg.Input,
	)
	var i SeoRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Agent,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CostUsd,
		&i.Input,
		&i.Output,
		&i.Error,
	)
	return i, err
}

const updateContentActionStatus = `-- name: UpdateContentActionStatus :one
update content_actions set
  status = $3,
  updated_at = now()
where id = $1 and project_id = $2
returning id, project_id, opportunity_id, action_type, status, target_article_id, target_url, normalized_target_url, target_content_hash_before, target_content_hash_after, draft_article_id, baseline_window, measurement_window, published_at, outcome_summary, created_at, updated_at
`

type UpdateContentActionStatusParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	Status    string    `json:"status"`
}

func (q *Queries) UpdateContentActionStatus(ctx context.Context, arg UpdateContentActionStatusParams) (ContentAction, error) {
	row := q.db.QueryRow(ctx, updateContentActionStatus, arg.ID, arg.ProjectID, arg.Status)
	var i ContentAction
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OpportunityID,
		&i.ActionType,
		&i.Status,
		&i.TargetArticleID,
		&i.TargetUrl,
		&i.NormalizedTargetUrl,
		&i.TargetContentHashBefore,
		&i.TargetContentHashAfter,
		&i.DraftArticleID,
		&i.BaselineWindow,
		&i.MeasurementWindow,
		&i.PublishedAt,
		&i.OutcomeSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSEOOpportunityStatus = `-- name: UpdateSEOOpportunityStatus :one
update seo_opportunities set
  status = $3,
  updated_at = now()
where id = $1 and project_id = $2
returning id, project_id, type, status, priority_score, confidence, page_url, normalized_page_url, article_id, topic_id, query, evidence, recommended_action, expected_impact, effort, risk_level, created_by_run_id, created_at, updated_at
`

type UpdateSEOOpportunityStatusParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	Status    string    `json:"status"`
}

func (q *Queries) UpdateSEOOpportunityStatus(ctx context.Context, arg UpdateSEOOpportunityStatusParams) (SeoOpportunity, error) {
	row := q.db.QueryRow(ctx, updateSEOOpportunityStatus, arg.ID, arg.ProjectID, arg.Status)
	var i SeoOpportunity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Status,
		&i.PriorityScore,
		&i.Confidence,
		&i.PageUrl,
		&i.NormalizedPageUrl,
		&i.ArticleID,
		&i.TopicID,
		&i.Query,
		&i.Evidence,
		&i.RecommendedAction,
		&i.ExpectedImpact,
		&i.Effort,
		&i.RiskLevel,
		&i.CreatedByRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPagePerformanceDaily = `-- name: UpsertPagePerformanceDaily :one
insert into page_performance_daily
  (project_id, property_id, date, page_url, normalized_page_url, article_id, topic_id,
   clicks, impressions, weighted_position, ctr, ga4_sessions, ga4_engaged_sessions,
   ga4_conversions, indexed_state, technical_status, data_source_notes)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
on conflict (project_id, property_id, date, normalized_page_url) do update set
  page_url = excluded.page_url,
  article_id = excluded.article_id,
  topic_id = excluded.topic_id,
  clicks = excluded.clicks,
  impressions = excluded.impressions,
  weighted_position = excluded.weighted_position,
  ctr = excluded.ctr,
  ga4_sessions = excluded.ga4_sessions,
  ga4_engaged_sessions = excluded.ga4_engaged_sessions,
  ga4_conversions = excluded.ga4_conversions,
  indexed_state = excluded.indexed_state,
  technical_status = excluded.technical_status,
  data_source_notes = excluded.data_source_notes,
  updated_at = now()
returning project_id, property_id, date, page_url, normalized_page_url, article_id, topic_id, clicks, impressions, weighted_position, ctr, ga4_sessions, ga4_engaged_sessions, ga4_conversions, indexed_state, technical_status, data_source_notes, updated_at
`

type UpsertPagePerformanceDailyParams struct {
	ProjectID          uuid.UUID       `json:"project_id"`
	PropertyID         uuid.UUID       `json:"property_id"`
	Date               pgtype.Date     `json:"date"`
	PageUrl            string          `json:"page_url"`
	NormalizedPageUrl  string          `json:"normalized_page_url"`
	ArticleID          pgtype.UUID     `json:"article_id"`
	TopicID            pgtype.UUID     `json:"topic_id"`
	Clicks             pgtype.Numeric  `json:"clicks"`
	Impressions        pgtype.Numeric  `json:"impressions"`
	WeightedPosition   pgtype.Numeric  `json:"weighted_position"`
	Ctr                pgtype.Numeric  `json:"ctr"`
	Ga4Sessions        pgtype.Numeric  `json:"ga4_sessions"`
	Ga4EngagedSessions pgtype.Numeric  `json:"ga4_engaged_sessions"`
	Ga4Conversions     pgtype.Numeric  `json:"ga4_conversions"`
	IndexedState       *string         `json:"indexed_state"`
	TechnicalStatus    *string         `json:"technical_status"`
	DataSourceNotes    json.RawMessage `json:"data_source_notes"`
}

func (q *Queries) UpsertPagePerformanceDaily(ctx context.Context, arg UpsertPagePerformanceDailyParams) (PagePerformanceDaily, error) {
	row := q.db.QueryRow(ctx, upsertPagePerformanceDaily,
		arg.ProjectID,
		arg.PropertyID,
		arg.Date,
		arg.PageUrl,
		arg.NormalizedPageUrl,
		arg.ArticleID,
		arg.TopicID,
		arg.Clicks,
		arg.Impressions,
		arg.WeightedPosition,
		arg.Ctr,
		arg.Ga4Sessions,
		arg.Ga4EngagedSessions,
		arg.Ga4Conversions,
		arg.IndexedState,
		arg.TechnicalStatus,
		arg.DataSourceNotes,
	)
	var i PagePerformanceDaily
	err := row.Scan(
		&i.ProjectID,
		&i.PropertyID,
		&i.Date,
		&i.PageUrl,
		&i.NormalizedPageUrl,
		&i.ArticleID,
		&i.TopicID,
		&i.Clicks,
		&i.Impressions,
		&i.WeightedPosition,
		&i.Ctr,
		&i.Ga4Sessions,
		&i.Ga4EngagedSessions,
		&i.Ga4Conversions,
		&i.IndexedState,
		&i.TechnicalStatus,
		&i.DataSourceNotes,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSEOIntegration = `-- name: UpsertSEOIntegration :one
insert into seo_integrations
  (project_id, provider, status, credential_ref, last_verified_at, last_error)
values ($1, $2, $3, $4, $5, $6)
on conflict (project_id, provider) do update set
  status = excluded.status,
  credential_ref = excluded.credential_ref,
  last_verified_at = excluded.last_verified_at,
  last_error = excluded.last_error,
  updated_at = now()
returning id, project_id, provider, status, credential_ref, last_verified_at, last_error, created_at, updated_at
`

type UpsertSEOIntegrationParams struct {
	ProjectID      uuid.UUID          `json:"project_id"`
	Provider       string             `json:"provider"`
	Status         string             `json:"status"`
	CredentialRef  *string            `json:"credential_ref"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
	LastError      *string            `json:"last_error"`
}

func (q *Queries) UpsertSEOIntegration(ctx context.Context, arg UpsertSEOIntegrationParams) (SeoIntegration, error) {
	row := q.db.QueryRow(ctx, upsertSEOIntegration,
		arg.ProjectID,
		arg.Provider,
		arg.Status,
		arg.CredentialRef,
		arg.LastVerifiedAt,
		arg.LastError,
	)
	var i SeoIntegration
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.Status,
		&i.CredentialRef,
		&i.LastVerifiedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSEOOpportunity = `-- name: UpsertSEOOpportunity :one
insert into seo_opportunities
  (project_id, type, status, priority_score, confidence, page_url, normalized_page_url,
   article_id, topic_id, query, evidence, recommended_action, expected_impact, effort,
   risk_level, created_by_run_id)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
on conflict (project_id, type, normalized_page_url, query, created_by_run_id) do update set
  status = excluded.status,
  priority_score = excluded.priority_score,
  confidence = excluded.confidence,
  page_url = excluded.page_url,
  article_id = excluded.article_id,
  topic_id = excluded.topic_id,
  evidence = excluded.evidence,
  recommended_action = excluded.recommended_action,
  expected_impact = excluded.expected_impact,
  effort = excluded.effort,
  risk_level = excluded.risk_level,
  updated_at = now()
returning id, project_id, type, status, priority_score, confidence, page_url, normalized_page_url, article_id, topic_id, query, evidence, recommended_action, expected_impact, effort, risk_level, created_by_run_id, created_at, updated_at
`

type UpsertSEOOpportunityParams struct {
	ProjectID         uuid.UUID       `json:"project_id"`
	Type              string          `json:"type"`
	Status            string          `json:"status"`
	PriorityScore     pgtype.Numeric  `json:"priority_score"`
	Confidence        pgtype.Numeric  `json:"confidence"`
	PageUrl           *string         `json:"page_url"`
	NormalizedPageUrl string          `json:"normalized_page_url"`
	ArticleID         pgtype.UUID     `json:"article_id"`
	TopicID           pgtype.UUID     `json:"topic_id"`
	Query             *string         `json:"query"`
	Evidence          json.RawMessage `json:"evidence"`
	RecommendedAction *string         `json:"recommended_action"`
	ExpectedImpact    *string         `json:"expected_impact"`
	Effort            int32           `json:"effort"`
	RiskLevel         string          `json:"risk_level"`
	CreatedByRunID    pgtype.UUID     `json:"created_by_run_id"`
}

func (q *Queries) UpsertSEOOpportunity(ctx context.Context, arg UpsertSEOOpportunityParams) (SeoOpportunity, error) {
	row := q.db.QueryRow(ctx, upsertSEOOpportunity,
		arg.ProjectID,
		arg.Type,
		arg.Status,
		arg.PriorityScore,
		arg.Confidence,
		arg.PageUrl,
		arg.NormalizedPageUrl,
		arg.ArticleID,
		arg.TopicID,
		arg.Query,
		arg.Evidence,
		arg.RecommendedAction,
		arg.ExpectedImpact,
		arg.Effort,
		arg.RiskLevel,
		arg.CreatedByRunID,
	)
	var i SeoOpportunity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Status,
		&i.PriorityScore,
		&i.Confidence,
		&i.PageUrl,
		&i.NormalizedPageUrl,
		&i.ArticleID,
		&i.TopicID,
		&i.Query,
		&i.Evidence,
		&i.RecommendedAction,
		&i.ExpectedImpact,
		&i.Effort,
		&i.RiskLevel,
		&i.CreatedByRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSEOProperty = `-- name: UpsertSEOProperty :one
insert into seo_properties
  (project_id, site_url, gsc_site_url, ga4_property_id, url_normalization_config, default_country, default_language)
values ($1, $2, $3, $4, $5, $6, $7)
on conflict (project_id, site_url) do update set
  gsc_site_url = excluded.gsc_site_url,
  ga4_property_id = excluded.ga4_property_id,
  url_normalization_config = excluded.url_normalization_config,
  default_country = excluded.default_country,
  default_language = excluded.default_language,
  updated_at = now()
returning id, project_id, site_url, gsc_site_url, ga4_property_id, url_normalization_config, default_country, default_language, created_at, updated_at
`

type UpsertSEOPropertyParams struct {
	ProjectID              uuid.UUID       `json:"project_id"`
	SiteUrl                string          `json:"site_url"`
	GscSiteUrl             *string         `json:"gsc_site_url"`
	Ga4PropertyID          *string         `json:"ga4_property_id"`
	UrlNormalizationConfig json.RawMessage `json:"url_normalization_config"`
	DefaultCountry         *string         `json:"default_country"`
	DefaultLanguage        *string         `json:"default_language"`
}

func (q *Queries) UpsertSEOProperty(ctx context.Context, arg UpsertSEOPropertyParams) (SeoProperty, error) {
	row := q.db.QueryRow(ctx, upsertSEOProperty,
		arg.ProjectID,
		arg.SiteUrl,
		arg.GscSiteUrl,
		arg.Ga4PropertyID,
		arg.UrlNormalizationConfig,
		arg.DefaultCountry,
		arg.DefaultLanguage,
	)
	var i SeoProperty
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SiteUrl,
		&i.GscSiteUrl,
		&i.Ga4PropertyID,
		&i.UrlNormalizationConfig,
		&i.DefaultCountry,
		&i.DefaultLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTechnicalCheck = `-- name: UpsertTechnicalCheck :one
insert into technical_checks
  (project_id, run_id, page_url, normalized_page_url, article_id, http_status, canonical_status,
   robots_status, title_status, meta_description_status, h1_status, structured_data_status,
   sitemap_status, internal_link_count, outbound_link_count, content_hash, unsafe_mdx_detected, raw_details)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
on conflict (project_id, run_id, normalized_page_url) do update set
  page_url = excluded.page_url,
  article_id = excluded.article_id,
  http_status = excluded.http_status,
  canonical_status = excluded.canonical_status,
  robots_status = excluded.robots_status,
  title_status = excluded.title_status,
  meta_description_status = excluded.meta_description_status,
  h1_status = excluded.h1_status,
  structured_data_status = excluded.structured_data_status,
  sitemap_status = excluded.sitemap_status,
  internal_link_count = excluded.internal_link_count,
  outbound_link_count = excluded.outbound_link_count,
  content_hash = excluded.content_hash,
  unsafe_mdx_detected = excluded.unsafe_mdx_detected,
  raw_details = excluded.raw_details,
  checked_at = now()
returning id, project_id, run_id, page_url, normalized_page_url, article_id, http_status, canonical_status, robots_status, title_status, meta_description_status, h1_status, structured_data_status, sitemap_status, internal_link_count, outbound_link_count, content_hash, unsafe_mdx_detected, raw_details, checked_at
`

type UpsertTechnicalCheckParams struct {
	ProjectID             uuid.UUID       `json:"project_id"`
	RunID                 uuid.UUID       `json:"run_id"`
	PageUrl               string          `json:"page_url"`
	NormalizedPageUrl     string          `json:"normalized_page_url"`
	ArticleID             pgtype.UUID     `json:"article_id"`
	HttpStatus            *int32          `json:"http_status"`
	CanonicalStatus       *string         `json:"canonical_status"`
	RobotsStatus          *string         `json:"robots_status"`
	TitleStatus           *string         `json:"title_status"`
	MetaDescriptionStatus *string         `json:"meta_description_status"`
	H1Status              *string         `json:"h1_status"`
	StructuredDataStatus  *string         `json:"structured_data_status"`
	SitemapStatus         *string         `json:"sitemap_status"`
	InternalLinkCount     *int32          `json:"internal_link_count"`
	OutboundLinkCount     *int32          `json:"outbound_link_count"`
	ContentHash           *string         `json:"content_hash"`
	UnsafeMdxDetected     bool            `json:"unsafe_mdx_detected"`
	RawDetails            json.RawMessage `json:"raw_details"`
}

func (q *Queries) UpsertTechnicalCheck(ctx context.Context, arg UpsertTechnicalCheckParams) (TechnicalCheck, error) {
	row := q.db.QueryRow(ctx, upsertTechnicalCheck,
		arg.ProjectID,
		arg.RunID,
		arg.PageUrl,
		arg.NormalizedPageUrl,
		arg.ArticleID,
		arg.HttpStatus,
		arg.CanonicalStatus,
		arg.RobotsStatus,
		arg.TitleStatus,
		arg.MetaDescriptionStatus,
		arg.H1Status,
		arg.StructuredDataStatus,
		arg.SitemapStatus,
		arg.InternalLinkCount,
		arg.OutboundLinkCount,
		arg.ContentHash,
		arg.UnsafeMdxDetected,
		arg.RawDetails,
	)
	var i TechnicalCheck
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RunID,
		&i.PageUrl,
		&i.NormalizedPageUrl,
		&i.ArticleID,
		&i.HttpStatus,
		&i.CanonicalStatus,
		&i.RobotsStatus,
		&i.TitleStatus,
		&i.MetaDescriptionStatus,
		&i.H1Status,
		&i.StructuredDataStatus,
		&i.SitemapStatus,
		&i.InternalLinkCount,
		&i.OutboundLinkCount,
		&i.ContentHash,
		&i.UnsafeMdxDetected,
		&i.RawDetails,
		&i.CheckedAt,
	)
	return i, err
}
