// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: site_fix_measurements.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateSiteFixMeasurement = `-- name: ActivateSiteFixMeasurement :one
update site_fix_measurements
set status = 'observing',
    started_at = coalesce(started_at, $1),
    absolute_terminal_at = coalesce(
      absolute_terminal_at,
      $1 + (
        ((measurement_policy_snapshot->>'max_measuring_duration_days')::int
          + (measurement_policy_snapshot->>'terminalization_grace_period_days')::int) * interval '1 day'
      )
    ),
    results_deep_link = coalesce(results_deep_link, $2),
    updated_at = now()
where project_id = $3
  and site_fix_id = $4
  and measurement_generation = $5
  and status = 'ready'
returning id, project_id, site_fix_id, measurement_generation, creation_idempotency_key, target_url, normalized_target_url, target_query, target_identity, fix_type, impact_mode, classifier_version, decision_origin, decision_confidence, prospective_observation, growth_hypothesis, primary_metric, secondary_metrics, measurement_policy_version, measurement_policy_snapshot, baseline_window, baseline_snapshot, baseline_status, started_at, absolute_terminal_at, status, terminal_outcome, outcome_reason, attribution_confidence, confounders, results_deep_link, created_at, updated_at
`

type ActivateSiteFixMeasurementParams struct {
	StartedAt             pgtype.Timestamptz `json:"started_at"`
	ResultsDeepLink       *string            `json:"results_deep_link"`
	ProjectID             uuid.UUID          `json:"project_id"`
	SiteFixID             uuid.UUID          `json:"site_fix_id"`
	MeasurementGeneration int32              `json:"measurement_generation"`
}

func (q *Queries) ActivateSiteFixMeasurement(ctx context.Context, arg ActivateSiteFixMeasurementParams) (SiteFixMeasurement, error) {
	row := q.db.QueryRow(ctx, activateSiteFixMeasurement,
		arg.StartedAt,
		arg.ResultsDeepLink,
		arg.ProjectID,
		arg.SiteFixID,
		arg.MeasurementGeneration,
	)
	var i SiteFixMeasurement
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SiteFixID,
		&i.MeasurementGeneration,
		&i.CreationIdempotencyKey,
		&i.TargetUrl,
		&i.NormalizedTargetUrl,
		&i.TargetQuery,
		&i.TargetIdentity,
		&i.FixType,
		&i.ImpactMode,
		&i.ClassifierVersion,
		&i.DecisionOrigin,
		&i.DecisionConfidence,
		&i.ProspectiveObservation,
		&i.GrowthHypothesis,
		&i.PrimaryMetric,
		&i.SecondaryMetrics,
		&i.MeasurementPolicyVersion,
		&i.MeasurementPolicySnapshot,
		&i.BaselineWindow,
		&i.BaselineSnapshot,
		&i.BaselineStatus,
		&i.StartedAt,
		&i.AbsoluteTerminalAt,
		&i.Status,
		&i.TerminalOutcome,
		&i.OutcomeReason,
		&i.AttributionConfidence,
		&i.Confounders,
		&i.ResultsDeepLink,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimDueSiteFixMeasurement = `-- name: ClaimDueSiteFixMeasurement :one
select measurement.id, measurement.project_id, measurement.site_fix_id, measurement.measurement_generation, measurement.creation_idempotency_key, measurement.target_url, measurement.normalized_target_url, measurement.target_query, measurement.target_identity, measurement.fix_type, measurement.impact_mode, measurement.classifier_version, measurement.decision_origin, measurement.decision_confidence, measurement.prospective_observation, measurement.growth_hypothesis, measurement.primary_metric, measurement.secondary_metrics, measurement.measurement_policy_version, measurement.measurement_policy_snapshot, measurement.baseline_window, measurement.baseline_snapshot, measurement.baseline_status, measurement.started_at, measurement.absolute_terminal_at, measurement.status, measurement.terminal_outcome, measurement.outcome_reason, measurement.attribution_confidence, measurement.confounders, measurement.results_deep_link, measurement.created_at, measurement.updated_at
from site_fix_measurements measurement
where measurement.status in ('ready','observing')
  and (
    measurement.absolute_terminal_at <= $1
    or exists (
      select 1
      from site_fix_measurement_checkpoints checkpoint
      where checkpoint.project_id = measurement.project_id
        and checkpoint.measurement_id = measurement.id
        and checkpoint.scheduled_at <= $1
        and checkpoint.next_attempt_at <= $1
        and checkpoint.computed_at is null
    )
  )
order by measurement.absolute_terminal_at, measurement.created_at
limit 1
for update skip locked
`

func (q *Queries) ClaimDueSiteFixMeasurement(ctx context.Context, nowAt pgtype.Timestamptz) (SiteFixMeasurement, error) {
	row := q.db.QueryRow(ctx, claimDueSiteFixMeasurement, nowAt)
	var i SiteFixMeasurement
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SiteFixID,
		&i.MeasurementGeneration,
		&i.CreationIdempotencyKey,
		&i.TargetUrl,
		&i.NormalizedTargetUrl,
		&i.TargetQuery,
		&i.TargetIdentity,
		&i.FixType,
		&i.ImpactMode,
		&i.ClassifierVersion,
		&i.DecisionOrigin,
		&i.DecisionConfidence,
		&i.ProspectiveObservation,
		&i.GrowthHypothesis,
		&i.PrimaryMetric,
		&i.SecondaryMetrics,
		&i.MeasurementPolicyVersion,
		&i.MeasurementPolicySnapshot,
		&i.BaselineWindow,
		&i.BaselineSnapshot,
		&i.BaselineStatus,
		&i.StartedAt,
		&i.AbsoluteTerminalAt,
		&i.Status,
		&i.TerminalOutcome,
		&i.OutcomeReason,
		&i.AttributionConfidence,
		&i.Confounders,
		&i.ResultsDeepLink,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimSiteFixMeasurementHandoff = `-- name: ClaimSiteFixMeasurementHandoff :one
with due as (
  select candidate.id
  from site_fix_measurement_handoff_outbox candidate
  where (
      (candidate.status in ('pending','failed_retryable') and candidate.next_attempt_at <= $3)
      or (candidate.status = 'processing' and candidate.locked_until <= $3)
    )
    and candidate.attempt_count < candidate.max_attempts
  order by candidate.next_attempt_at, candidate.created_at
  limit 1
  for update skip locked
)
update site_fix_measurement_handoff_outbox outbox
set status = 'processing',
    attempt_count = attempt_count + 1,
    lock_token = $1,
    locked_until = $2,
    updated_at = now()
from due
where outbox.id = due.id
returning outbox.id, outbox.project_id, outbox.site_fix_id, outbox.measurement_generation, outbox.event_type, outbox.idempotency_key, outbox.status, outbox.attempt_count, outbox.max_attempts, outbox.next_attempt_at, outbox.lock_token, outbox.locked_until, outbox.last_error_classification, outbox.last_error, outbox.completed_at, outbox.created_at, outbox.updated_at, outbox.occurred_at
`

type ClaimSiteFixMeasurementHandoffParams struct {
	LockToken   pgtype.UUID        `json:"lock_token"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
	NowAt       pgtype.Timestamptz `json:"now_at"`
}

func (q *Queries) ClaimSiteFixMeasurementHandoff(ctx context.Context, arg ClaimSiteFixMeasurementHandoffParams) (SiteFixMeasurementHandoffOutbox, error) {
	row := q.db.QueryRow(ctx, claimSiteFixMeasurementHandoff, arg.LockToken, arg.LockedUntil, arg.NowAt)
	var i SiteFixMeasurementHandoffOutbox
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SiteFixID,
		&i.MeasurementGeneration,
		&i.EventType,
		&i.IdempotencyKey,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LockToken,
		&i.LockedUntil,
		&i.LastErrorClassification,
		&i.LastError,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OccurredAt,
	)
	return i, err
}

const closeSiteFixMeasurementOpenCheckpoints = `-- name: CloseSiteFixMeasurementOpenCheckpoints :many
update site_fix_measurement_checkpoints checkpoint
set computed_at=$1,
    outcome_label=null,
    outcome_reason='skipped_after_terminal_outcome',
    attribution_confidence='none',
    failure_reason='closed_after_terminal_outcome',
    retry_classification='terminal',
    evaluation_attempt_count=evaluation_attempt_count + 1
where checkpoint.project_id=$2
  and checkpoint.measurement_id=$3
  and checkpoint.computed_at is null
returning id, project_id, measurement_id, checkpoint_key, checkpoint_role, scheduled_at, window_start, window_end, attempt_number, required_data_sources, data_availability, minimum_sample, seo_metrics, ga4_metrics, geo_metrics, execution_metrics, guardrail_results, outcome_label, outcome_reason, attribution_confidence, computed_at, failure_reason, retry_classification, created_at, evaluation_attempt_count, next_attempt_at
`

type CloseSiteFixMeasurementOpenCheckpointsParams struct {
	ComputedAt    pgtype.Timestamptz `json:"computed_at"`
	ProjectID     uuid.UUID          `json:"project_id"`
	MeasurementID uuid.UUID          `json:"measurement_id"`
}

func (q *Queries) CloseSiteFixMeasurementOpenCheckpoints(ctx context.Context, arg CloseSiteFixMeasurementOpenCheckpointsParams) ([]SiteFixMeasurementCheckpoint, error) {
	rows, err := q.db.Query(ctx, closeSiteFixMeasurementOpenCheckpoints, arg.ComputedAt, arg.ProjectID, arg.MeasurementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteFixMeasurementCheckpoint
	for rows.Next() {
		var i SiteFixMeasurementCheckpoint
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.MeasurementID,
			&i.CheckpointKey,
			&i.CheckpointRole,
			&i.ScheduledAt,
			&i.WindowStart,
			&i.WindowEnd,
			&i.AttemptNumber,
			&i.RequiredDataSources,
			&i.DataAvailability,
			&i.MinimumSample,
			&i.SeoMetrics,
			&i.Ga4Metrics,
			&i.GeoMetrics,
			&i.ExecutionMetrics,
			&i.GuardrailResults,
			&i.OutcomeLabel,
			&i.OutcomeReason,
			&i.AttributionConfidence,
			&i.ComputedAt,
			&i.FailureReason,
			&i.RetryClassification,
			&i.CreatedAt,
			&i.EvaluationAttemptCount,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeSiteFixMeasurementCheckpoint = `-- name: CompleteSiteFixMeasurementCheckpoint :one
select id, project_id, measurement_id, checkpoint_key, checkpoint_role, scheduled_at, window_start, window_end, attempt_number, required_data_sources, data_availability, minimum_sample, seo_metrics, ga4_metrics, geo_metrics, execution_metrics, guardrail_results, outcome_label, outcome_reason, attribution_confidence, computed_at, failure_reason, retry_classification, created_at, evaluation_attempt_count, next_attempt_at from complete_site_fix_measurement_checkpoint_idempotently(
  $1, $2, $3, $4,
  $5, $6, $7, $8,
  $9, $10, $11,
  $12, $13, $14,
  $15, $16
)
`

type CompleteSiteFixMeasurementCheckpointParams struct {
	ProjectID             uuid.UUID          `json:"project_id"`
	MeasurementID         uuid.UUID          `json:"measurement_id"`
	CheckpointKey         string             `json:"checkpoint_key"`
	AttemptNumber         int32              `json:"attempt_number"`
	DataAvailability      json.RawMessage    `json:"data_availability"`
	SeoMetrics            json.RawMessage    `json:"seo_metrics"`
	Ga4Metrics            json.RawMessage    `json:"ga4_metrics"`
	GeoMetrics            json.RawMessage    `json:"geo_metrics"`
	ExecutionMetrics      json.RawMessage    `json:"execution_metrics"`
	GuardrailResults      json.RawMessage    `json:"guardrail_results"`
	OutcomeLabel          *string            `json:"outcome_label"`
	OutcomeReason         *string            `json:"outcome_reason"`
	AttributionConfidence string             `json:"attribution_confidence"`
	ComputedAt            pgtype.Timestamptz `json:"computed_at"`
	FailureReason         *string            `json:"failure_reason"`
	RetryClassification   string             `json:"retry_classification"`
}

func (q *Queries) CompleteSiteFixMeasurementCheckpoint(ctx context.Context, arg CompleteSiteFixMeasurementCheckpointParams) (SiteFixMeasurementCheckpoint, error) {
	row := q.db.QueryRow(ctx, completeSiteFixMeasurementCheckpoint,
		arg.ProjectID,
		arg.MeasurementID,
		arg.CheckpointKey,
		arg.AttemptNumber,
		arg.DataAvailability,
		arg.SeoMetrics,
		arg.Ga4Metrics,
		arg.GeoMetrics,
		arg.ExecutionMetrics,
		arg.GuardrailResults,
		arg.OutcomeLabel,
		arg.OutcomeReason,
		arg.AttributionConfidence,
		arg.ComputedAt,
		arg.FailureReason,
		arg.RetryClassification,
	)
	var i SiteFixMeasurementCheckpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MeasurementID,
		&i.CheckpointKey,
		&i.CheckpointRole,
		&i.ScheduledAt,
		&i.WindowStart,
		&i.WindowEnd,
		&i.AttemptNumber,
		&i.RequiredDataSources,
		&i.DataAvailability,
		&i.MinimumSample,
		&i.SeoMetrics,
		&i.Ga4Metrics,
		&i.GeoMetrics,
		&i.ExecutionMetrics,
		&i.GuardrailResults,
		&i.OutcomeLabel,
		&i.OutcomeReason,
		&i.AttributionConfidence,
		&i.ComputedAt,
		&i.FailureReason,
		&i.RetryClassification,
		&i.CreatedAt,
		&i.EvaluationAttemptCount,
		&i.NextAttemptAt,
	)
	return i, err
}

const completeSiteFixMeasurementHandoff = `-- name: CompleteSiteFixMeasurementHandoff :one
update site_fix_measurement_handoff_outbox
set status = 'completed',
    lock_token = null,
    locked_until = null,
    completed_at = now(),
    last_error_classification = null,
    last_error = null,
    updated_at = now()
where id = $1
  and project_id = $2
  and status = 'processing'
  and lock_token = $3
returning id, project_id, site_fix_id, measurement_generation, event_type, idempotency_key, status, attempt_count, max_attempts, next_attempt_at, lock_token, locked_until, last_error_classification, last_error, completed_at, created_at, updated_at, occurred_at
`

type CompleteSiteFixMeasurementHandoffParams struct {
	ID        uuid.UUID   `json:"id"`
	ProjectID uuid.UUID   `json:"project_id"`
	LockToken pgtype.UUID `json:"lock_token"`
}

func (q *Queries) CompleteSiteFixMeasurementHandoff(ctx context.Context, arg CompleteSiteFixMeasurementHandoffParams) (SiteFixMeasurementHandoffOutbox, error) {
	row := q.db.QueryRow(ctx, completeSiteFixMeasurementHandoff, arg.ID, arg.ProjectID, arg.LockToken)
	var i SiteFixMeasurementHandoffOutbox
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SiteFixID,
		&i.MeasurementGeneration,
		&i.EventType,
		&i.IdempotencyKey,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LockToken,
		&i.LockedUntil,
		&i.LastErrorClassification,
		&i.LastError,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OccurredAt,
	)
	return i, err
}

const createSiteFixMeasurement = `-- name: CreateSiteFixMeasurement :one
select id, project_id, site_fix_id, measurement_generation, creation_idempotency_key, target_url, normalized_target_url, target_query, target_identity, fix_type, impact_mode, classifier_version, decision_origin, decision_confidence, prospective_observation, growth_hypothesis, primary_metric, secondary_metrics, measurement_policy_version, measurement_policy_snapshot, baseline_window, baseline_snapshot, baseline_status, started_at, absolute_terminal_at, status, terminal_outcome, outcome_reason, attribution_confidence, confounders, results_deep_link, created_at, updated_at from create_site_fix_measurement_idempotently(
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::text,
  $5::text,
  $6::text,
  $7::text,
  $8::jsonb,
  $9::text,
  $10::text,
  $11::text,
  $12::text,
  $13::text,
  $14::boolean,
  $15::text,
  $16::text,
  $17::jsonb,
  $18::text,
  $19::jsonb,
  $20::jsonb,
  $21::jsonb,
  $22::text,
  $23::text,
  $24::text,
  $25::text
)
`

type CreateSiteFixMeasurementParams struct {
	ID                        uuid.UUID       `json:"id"`
	ProjectID                 uuid.UUID       `json:"project_id"`
	SiteFixID                 uuid.UUID       `json:"site_fix_id"`
	CreationIdempotencyKey    string          `json:"creation_idempotency_key"`
	TargetUrl                 string          `json:"target_url"`
	NormalizedTargetUrl       string          `json:"normalized_target_url"`
	TargetQuery               *string         `json:"target_query"`
	TargetIdentity            json.RawMessage `json:"target_identity"`
	FixType                   string          `json:"fix_type"`
	ImpactMode                string          `json:"impact_mode"`
	ClassifierVersion         string          `json:"classifier_version"`
	DecisionOrigin            string          `json:"decision_origin"`
	DecisionConfidence        string          `json:"decision_confidence"`
	ProspectiveObservation    bool            `json:"prospective_observation"`
	GrowthHypothesis          string          `json:"growth_hypothesis"`
	PrimaryMetric             string          `json:"primary_metric"`
	SecondaryMetrics          json.RawMessage `json:"secondary_metrics"`
	MeasurementPolicyVersion  string          `json:"measurement_policy_version"`
	MeasurementPolicySnapshot json.RawMessage `json:"measurement_policy_snapshot"`
	BaselineWindow            json.RawMessage `json:"baseline_window"`
	BaselineSnapshot          json.RawMessage `json:"baseline_snapshot"`
	BaselineStatus            string          `json:"baseline_status"`
	Status                    string          `json:"status"`
	AttributionConfidence     string          `json:"attribution_confidence"`
	ResultsDeepLink           *string         `json:"results_deep_link"`
}

func (q *Queries) CreateSiteFixMeasurement(ctx context.Context, arg CreateSiteFixMeasurementParams) (SiteFixMeasurement, error) {
	row := q.db.QueryRow(ctx, createSiteFixMeasurement,
		arg.ID,
		arg.ProjectID,
		arg.SiteFixID,
		arg.CreationIdempotencyKey,
		arg.TargetUrl,
		arg.NormalizedTargetUrl,
		arg.TargetQuery,
		arg.TargetIdentity,
		arg.FixType,
		arg.ImpactMode,
		arg.ClassifierVersion,
		arg.DecisionOrigin,
		arg.DecisionConfidence,
		arg.ProspectiveObservation,
		arg.GrowthHypothesis,
		arg.PrimaryMetric,
		arg.SecondaryMetrics,
		arg.MeasurementPolicyVersion,
		arg.MeasurementPolicySnapshot,
		arg.BaselineWindow,
		arg.BaselineSnapshot,
		arg.BaselineStatus,
		arg.Status,
		arg.AttributionConfidence,
		arg.ResultsDeepLink,
	)
	var i SiteFixMeasurement
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SiteFixID,
		&i.MeasurementGeneration,
		&i.CreationIdempotencyKey,
		&i.TargetUrl,
		&i.NormalizedTargetUrl,
		&i.TargetQuery,
		&i.TargetIdentity,
		&i.FixType,
		&i.ImpactMode,
		&i.ClassifierVersion,
		&i.DecisionOrigin,
		&i.DecisionConfidence,
		&i.ProspectiveObservation,
		&i.GrowthHypothesis,
		&i.PrimaryMetric,
		&i.SecondaryMetrics,
		&i.MeasurementPolicyVersion,
		&i.MeasurementPolicySnapshot,
		&i.BaselineWindow,
		&i.BaselineSnapshot,
		&i.BaselineStatus,
		&i.StartedAt,
		&i.AbsoluteTerminalAt,
		&i.Status,
		&i.TerminalOutcome,
		&i.OutcomeReason,
		&i.AttributionConfidence,
		&i.Confounders,
		&i.ResultsDeepLink,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deferSiteFixMeasurementCheckpoint = `-- name: DeferSiteFixMeasurementCheckpoint :one
update site_fix_measurement_checkpoints checkpoint
set evaluation_attempt_count = evaluation_attempt_count + 1,
    next_attempt_at = $1,
    failure_reason = $2,
    retry_classification = 'retryable'
where checkpoint.project_id=$3
  and checkpoint.measurement_id=$4
  and checkpoint.checkpoint_key=$5
  and checkpoint.attempt_number=$6
  and checkpoint.computed_at is null
  and checkpoint.next_attempt_at < $1
returning id, project_id, measurement_id, checkpoint_key, checkpoint_role, scheduled_at, window_start, window_end, attempt_number, required_data_sources, data_availability, minimum_sample, seo_metrics, ga4_metrics, geo_metrics, execution_metrics, guardrail_results, outcome_label, outcome_reason, attribution_confidence, computed_at, failure_reason, retry_classification, created_at, evaluation_attempt_count, next_attempt_at
`

type DeferSiteFixMeasurementCheckpointParams struct {
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	FailureReason *string            `json:"failure_reason"`
	ProjectID     uuid.UUID          `json:"project_id"`
	MeasurementID uuid.UUID          `json:"measurement_id"`
	CheckpointKey string             `json:"checkpoint_key"`
	AttemptNumber int32              `json:"attempt_number"`
}

func (q *Queries) DeferSiteFixMeasurementCheckpoint(ctx context.Context, arg DeferSiteFixMeasurementCheckpointParams) (SiteFixMeasurementCheckpoint, error) {
	row := q.db.QueryRow(ctx, deferSiteFixMeasurementCheckpoint,
		arg.NextAttemptAt,
		arg.FailureReason,
		arg.ProjectID,
		arg.MeasurementID,
		arg.CheckpointKey,
		arg.AttemptNumber,
	)
	var i SiteFixMeasurementCheckpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MeasurementID,
		&i.CheckpointKey,
		&i.CheckpointRole,
		&i.ScheduledAt,
		&i.WindowStart,
		&i.WindowEnd,
		&i.AttemptNumber,
		&i.RequiredDataSources,
		&i.DataAvailability,
		&i.MinimumSample,
		&i.SeoMetrics,
		&i.Ga4Metrics,
		&i.GeoMetrics,
		&i.ExecutionMetrics,
		&i.GuardrailResults,
		&i.OutcomeLabel,
		&i.OutcomeReason,
		&i.AttributionConfidence,
		&i.ComputedAt,
		&i.FailureReason,
		&i.RetryClassification,
		&i.CreatedAt,
		&i.EvaluationAttemptCount,
		&i.NextAttemptAt,
	)
	return i, err
}

const enqueueSiteFixMeasurementHandoff = `-- name: EnqueueSiteFixMeasurementHandoff :one
insert into site_fix_measurement_handoff_outbox (
  id, project_id, site_fix_id, measurement_generation, idempotency_key,
  max_attempts, next_attempt_at, occurred_at
) values (
  $1, $2, $3, $4, $5,
  $6, $7, $8
)
on conflict (project_id, site_fix_id, measurement_generation) do update
set idempotency_key = site_fix_measurement_handoff_outbox.idempotency_key
returning id, project_id, site_fix_id, measurement_generation, event_type, idempotency_key, status, attempt_count, max_attempts, next_attempt_at, lock_token, locked_until, last_error_classification, last_error, completed_at, created_at, updated_at, occurred_at
`

type EnqueueSiteFixMeasurementHandoffParams struct {
	ID                    uuid.UUID          `json:"id"`
	ProjectID             uuid.UUID          `json:"project_id"`
	SiteFixID             uuid.UUID          `json:"site_fix_id"`
	MeasurementGeneration int32              `json:"measurement_generation"`
	IdempotencyKey        string             `json:"idempotency_key"`
	MaxAttempts           int32              `json:"max_attempts"`
	NextAttemptAt         pgtype.Timestamptz `json:"next_attempt_at"`
	OccurredAt            pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) EnqueueSiteFixMeasurementHandoff(ctx context.Context, arg EnqueueSiteFixMeasurementHandoffParams) (SiteFixMeasurementHandoffOutbox, error) {
	row := q.db.QueryRow(ctx, enqueueSiteFixMeasurementHandoff,
		arg.ID,
		arg.ProjectID,
		arg.SiteFixID,
		arg.MeasurementGeneration,
		arg.IdempotencyKey,
		arg.MaxAttempts,
		arg.NextAttemptAt,
		arg.OccurredAt,
	)
	var i SiteFixMeasurementHandoffOutbox
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SiteFixID,
		&i.MeasurementGeneration,
		&i.EventType,
		&i.IdempotencyKey,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LockToken,
		&i.LockedUntil,
		&i.LastErrorClassification,
		&i.LastError,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OccurredAt,
	)
	return i, err
}

const getLatestSiteFixMeasurementForFix = `-- name: GetLatestSiteFixMeasurementForFix :one
select id, project_id, site_fix_id, measurement_generation, creation_idempotency_key, target_url, normalized_target_url, target_query, target_identity, fix_type, impact_mode, classifier_version, decision_origin, decision_confidence, prospective_observation, growth_hypothesis, primary_metric, secondary_metrics, measurement_policy_version, measurement_policy_snapshot, baseline_window, baseline_snapshot, baseline_status, started_at, absolute_terminal_at, status, terminal_outcome, outcome_reason, attribution_confidence, confounders, results_deep_link, created_at, updated_at from site_fix_measurements
where project_id = $1 and site_fix_id = $2
order by measurement_generation desc
limit 1
`

type GetLatestSiteFixMeasurementForFixParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	SiteFixID uuid.UUID `json:"site_fix_id"`
}

func (q *Queries) GetLatestSiteFixMeasurementForFix(ctx context.Context, arg GetLatestSiteFixMeasurementForFixParams) (SiteFixMeasurement, error) {
	row := q.db.QueryRow(ctx, getLatestSiteFixMeasurementForFix, arg.ProjectID, arg.SiteFixID)
	var i SiteFixMeasurement
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SiteFixID,
		&i.MeasurementGeneration,
		&i.CreationIdempotencyKey,
		&i.TargetUrl,
		&i.NormalizedTargetUrl,
		&i.TargetQuery,
		&i.TargetIdentity,
		&i.FixType,
		&i.ImpactMode,
		&i.ClassifierVersion,
		&i.DecisionOrigin,
		&i.DecisionConfidence,
		&i.ProspectiveObservation,
		&i.GrowthHypothesis,
		&i.PrimaryMetric,
		&i.SecondaryMetrics,
		&i.MeasurementPolicyVersion,
		&i.MeasurementPolicySnapshot,
		&i.BaselineWindow,
		&i.BaselineSnapshot,
		&i.BaselineStatus,
		&i.StartedAt,
		&i.AbsoluteTerminalAt,
		&i.Status,
		&i.TerminalOutcome,
		&i.OutcomeReason,
		&i.AttributionConfidence,
		&i.Confounders,
		&i.ResultsDeepLink,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrCreateSiteFixMeasurementCheckpoint = `-- name: GetOrCreateSiteFixMeasurementCheckpoint :one
insert into site_fix_measurement_checkpoints (
  id, project_id, measurement_id, checkpoint_key, checkpoint_role,
  scheduled_at, window_start, window_end, attempt_number,
  required_data_sources, data_availability, minimum_sample,
  seo_metrics, ga4_metrics, geo_metrics, execution_metrics, guardrail_results,
  outcome_label, outcome_reason, attribution_confidence,
  computed_at, failure_reason, retry_classification,
  evaluation_attempt_count, next_attempt_at
) values (
  $1, $2, $3, $4, $5,
  $6, $7, $8, $9,
  $10, $11, $12,
  $13, $14, $15, $16, $17,
  $18, $19, $20,
  $21, $22, $23,
  $24, $25
)
on conflict (measurement_id, checkpoint_key, attempt_number) do update
set id = site_fix_measurement_checkpoints.id
returning id, project_id, measurement_id, checkpoint_key, checkpoint_role, scheduled_at, window_start, window_end, attempt_number, required_data_sources, data_availability, minimum_sample, seo_metrics, ga4_metrics, geo_metrics, execution_metrics, guardrail_results, outcome_label, outcome_reason, attribution_confidence, computed_at, failure_reason, retry_classification, created_at, evaluation_attempt_count, next_attempt_at
`

type GetOrCreateSiteFixMeasurementCheckpointParams struct {
	ID                     uuid.UUID          `json:"id"`
	ProjectID              uuid.UUID          `json:"project_id"`
	MeasurementID          uuid.UUID          `json:"measurement_id"`
	CheckpointKey          string             `json:"checkpoint_key"`
	CheckpointRole         string             `json:"checkpoint_role"`
	ScheduledAt            pgtype.Timestamptz `json:"scheduled_at"`
	WindowStart            pgtype.Timestamptz `json:"window_start"`
	WindowEnd              pgtype.Timestamptz `json:"window_end"`
	AttemptNumber          int32              `json:"attempt_number"`
	RequiredDataSources    json.RawMessage    `json:"required_data_sources"`
	DataAvailability       json.RawMessage    `json:"data_availability"`
	MinimumSample          json.RawMessage    `json:"minimum_sample"`
	SeoMetrics             json.RawMessage    `json:"seo_metrics"`
	Ga4Metrics             json.RawMessage    `json:"ga4_metrics"`
	GeoMetrics             json.RawMessage    `json:"geo_metrics"`
	ExecutionMetrics       json.RawMessage    `json:"execution_metrics"`
	GuardrailResults       json.RawMessage    `json:"guardrail_results"`
	OutcomeLabel           *string            `json:"outcome_label"`
	OutcomeReason          *string            `json:"outcome_reason"`
	AttributionConfidence  string             `json:"attribution_confidence"`
	ComputedAt             pgtype.Timestamptz `json:"computed_at"`
	FailureReason          *string            `json:"failure_reason"`
	RetryClassification    string             `json:"retry_classification"`
	EvaluationAttemptCount int32              `json:"evaluation_attempt_count"`
	NextAttemptAt          pgtype.Timestamptz `json:"next_attempt_at"`
}

func (q *Queries) GetOrCreateSiteFixMeasurementCheckpoint(ctx context.Context, arg GetOrCreateSiteFixMeasurementCheckpointParams) (SiteFixMeasurementCheckpoint, error) {
	row := q.db.QueryRow(ctx, getOrCreateSiteFixMeasurementCheckpoint,
		arg.ID,
		arg.ProjectID,
		arg.MeasurementID,
		arg.CheckpointKey,
		arg.CheckpointRole,
		arg.ScheduledAt,
		arg.WindowStart,
		arg.WindowEnd,
		arg.AttemptNumber,
		arg.RequiredDataSources,
		arg.DataAvailability,
		arg.MinimumSample,
		arg.SeoMetrics,
		arg.Ga4Metrics,
		arg.GeoMetrics,
		arg.ExecutionMetrics,
		arg.GuardrailResults,
		arg.OutcomeLabel,
		arg.OutcomeReason,
		arg.AttributionConfidence,
		arg.ComputedAt,
		arg.FailureReason,
		arg.RetryClassification,
		arg.EvaluationAttemptCount,
		arg.NextAttemptAt,
	)
	var i SiteFixMeasurementCheckpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MeasurementID,
		&i.CheckpointKey,
		&i.CheckpointRole,
		&i.ScheduledAt,
		&i.WindowStart,
		&i.WindowEnd,
		&i.AttemptNumber,
		&i.RequiredDataSources,
		&i.DataAvailability,
		&i.MinimumSample,
		&i.SeoMetrics,
		&i.Ga4Metrics,
		&i.GeoMetrics,
		&i.ExecutionMetrics,
		&i.GuardrailResults,
		&i.OutcomeLabel,
		&i.OutcomeReason,
		&i.AttributionConfidence,
		&i.ComputedAt,
		&i.FailureReason,
		&i.RetryClassification,
		&i.CreatedAt,
		&i.EvaluationAttemptCount,
		&i.NextAttemptAt,
	)
	return i, err
}

const getOrCreateSiteFixMeasurementLearning = `-- name: GetOrCreateSiteFixMeasurementLearning :one
insert into site_fix_measurement_learnings (
  id, project_id, terminal_outcome_id, measurement_id, learning_summary, applicability, learning_version
) values (
  $1, $2, $3, $4,
  $5, $6, $7
)
on conflict (project_id, measurement_id) do update
set id = site_fix_measurement_learnings.id
returning id, project_id, terminal_outcome_id, measurement_id, learning_summary, applicability, scoring_eligible, learning_version, created_at
`

type GetOrCreateSiteFixMeasurementLearningParams struct {
	ID                uuid.UUID       `json:"id"`
	ProjectID         uuid.UUID       `json:"project_id"`
	TerminalOutcomeID uuid.UUID       `json:"terminal_outcome_id"`
	MeasurementID     uuid.UUID       `json:"measurement_id"`
	LearningSummary   string          `json:"learning_summary"`
	Applicability     json.RawMessage `json:"applicability"`
	LearningVersion   string          `json:"learning_version"`
}

func (q *Queries) GetOrCreateSiteFixMeasurementLearning(ctx context.Context, arg GetOrCreateSiteFixMeasurementLearningParams) (SiteFixMeasurementLearning, error) {
	row := q.db.QueryRow(ctx, getOrCreateSiteFixMeasurementLearning,
		arg.ID,
		arg.ProjectID,
		arg.TerminalOutcomeID,
		arg.MeasurementID,
		arg.LearningSummary,
		arg.Applicability,
		arg.LearningVersion,
	)
	var i SiteFixMeasurementLearning
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TerminalOutcomeID,
		&i.MeasurementID,
		&i.LearningSummary,
		&i.Applicability,
		&i.ScoringEligible,
		&i.LearningVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getOrCreateSiteFixMeasurementQualityRecord = `-- name: GetOrCreateSiteFixMeasurementQualityRecord :one
insert into site_fix_measurement_quality_records (
  id, project_id, terminal_outcome_id, measurement_id,
  data_quality_state, quality_gaps, recommendation, quality_version
) values (
  $1, $2, $3, $4,
  $5, $6, $7, $8
)
on conflict (project_id, measurement_id) do update
set id = site_fix_measurement_quality_records.id
returning id, project_id, terminal_outcome_id, measurement_id, data_quality_state, quality_gaps, recommendation, scoring_eligible, quality_version, created_at
`

type GetOrCreateSiteFixMeasurementQualityRecordParams struct {
	ID                uuid.UUID       `json:"id"`
	ProjectID         uuid.UUID       `json:"project_id"`
	TerminalOutcomeID uuid.UUID       `json:"terminal_outcome_id"`
	MeasurementID     uuid.UUID       `json:"measurement_id"`
	DataQualityState  string          `json:"data_quality_state"`
	QualityGaps       json.RawMessage `json:"quality_gaps"`
	Recommendation    string          `json:"recommendation"`
	QualityVersion    string          `json:"quality_version"`
}

func (q *Queries) GetOrCreateSiteFixMeasurementQualityRecord(ctx context.Context, arg GetOrCreateSiteFixMeasurementQualityRecordParams) (SiteFixMeasurementQualityRecord, error) {
	row := q.db.QueryRow(ctx, getOrCreateSiteFixMeasurementQualityRecord,
		arg.ID,
		arg.ProjectID,
		arg.TerminalOutcomeID,
		arg.MeasurementID,
		arg.DataQualityState,
		arg.QualityGaps,
		arg.Recommendation,
		arg.QualityVersion,
	)
	var i SiteFixMeasurementQualityRecord
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TerminalOutcomeID,
		&i.MeasurementID,
		&i.DataQualityState,
		&i.QualityGaps,
		&i.Recommendation,
		&i.ScoringEligible,
		&i.QualityVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getOrCreateSiteFixMeasurementTerminalOutcome = `-- name: GetOrCreateSiteFixMeasurementTerminalOutcome :one
insert into site_fix_measurement_terminal_outcomes (
  id, project_id, measurement_id, outcome_label, record_kind, terminal_reason,
  measurement_policy_version, baseline_snapshot, checkpoint_snapshot, outcome_snapshot
) values (
  $1, $2, $3, $4, $5, $6,
  $7, $8, $9, $10
)
on conflict (project_id, measurement_id) do update
set id = site_fix_measurement_terminal_outcomes.id
returning id, project_id, measurement_id, outcome_label, record_kind, terminal_reason, measurement_policy_version, baseline_snapshot, checkpoint_snapshot, outcome_snapshot, created_at
`

type GetOrCreateSiteFixMeasurementTerminalOutcomeParams struct {
	ID                       uuid.UUID       `json:"id"`
	ProjectID                uuid.UUID       `json:"project_id"`
	MeasurementID            uuid.UUID       `json:"measurement_id"`
	OutcomeLabel             string          `json:"outcome_label"`
	RecordKind               string          `json:"record_kind"`
	TerminalReason           string          `json:"terminal_reason"`
	MeasurementPolicyVersion string          `json:"measurement_policy_version"`
	BaselineSnapshot         json.RawMessage `json:"baseline_snapshot"`
	CheckpointSnapshot       json.RawMessage `json:"checkpoint_snapshot"`
	OutcomeSnapshot          json.RawMessage `json:"outcome_snapshot"`
}

func (q *Queries) GetOrCreateSiteFixMeasurementTerminalOutcome(ctx context.Context, arg GetOrCreateSiteFixMeasurementTerminalOutcomeParams) (SiteFixMeasurementTerminalOutcome, error) {
	row := q.db.QueryRow(ctx, getOrCreateSiteFixMeasurementTerminalOutcome,
		arg.ID,
		arg.ProjectID,
		arg.MeasurementID,
		arg.OutcomeLabel,
		arg.RecordKind,
		arg.TerminalReason,
		arg.MeasurementPolicyVersion,
		arg.BaselineSnapshot,
		arg.CheckpointSnapshot,
		arg.OutcomeSnapshot,
	)
	var i SiteFixMeasurementTerminalOutcome
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MeasurementID,
		&i.OutcomeLabel,
		&i.RecordKind,
		&i.TerminalReason,
		&i.MeasurementPolicyVersion,
		&i.BaselineSnapshot,
		&i.CheckpointSnapshot,
		&i.OutcomeSnapshot,
		&i.CreatedAt,
	)
	return i, err
}

const getSiteFixMeasurement = `-- name: GetSiteFixMeasurement :one
select id, project_id, site_fix_id, measurement_generation, creation_idempotency_key, target_url, normalized_target_url, target_query, target_identity, fix_type, impact_mode, classifier_version, decision_origin, decision_confidence, prospective_observation, growth_hypothesis, primary_metric, secondary_metrics, measurement_policy_version, measurement_policy_snapshot, baseline_window, baseline_snapshot, baseline_status, started_at, absolute_terminal_at, status, terminal_outcome, outcome_reason, attribution_confidence, confounders, results_deep_link, created_at, updated_at from site_fix_measurements
where project_id = $1 and id = $2
`

type GetSiteFixMeasurementParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetSiteFixMeasurement(ctx context.Context, arg GetSiteFixMeasurementParams) (SiteFixMeasurement, error) {
	row := q.db.QueryRow(ctx, getSiteFixMeasurement, arg.ProjectID, arg.ID)
	var i SiteFixMeasurement
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SiteFixID,
		&i.MeasurementGeneration,
		&i.CreationIdempotencyKey,
		&i.TargetUrl,
		&i.NormalizedTargetUrl,
		&i.TargetQuery,
		&i.TargetIdentity,
		&i.FixType,
		&i.ImpactMode,
		&i.ClassifierVersion,
		&i.DecisionOrigin,
		&i.DecisionConfidence,
		&i.ProspectiveObservation,
		&i.GrowthHypothesis,
		&i.PrimaryMetric,
		&i.SecondaryMetrics,
		&i.MeasurementPolicyVersion,
		&i.MeasurementPolicySnapshot,
		&i.BaselineWindow,
		&i.BaselineSnapshot,
		&i.BaselineStatus,
		&i.StartedAt,
		&i.AbsoluteTerminalAt,
		&i.Status,
		&i.TerminalOutcome,
		&i.OutcomeReason,
		&i.AttributionConfidence,
		&i.Confounders,
		&i.ResultsDeepLink,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteFixMeasurementGeneration = `-- name: GetSiteFixMeasurementGeneration :one
select id, project_id, site_fix_id, measurement_generation, creation_idempotency_key, target_url, normalized_target_url, target_query, target_identity, fix_type, impact_mode, classifier_version, decision_origin, decision_confidence, prospective_observation, growth_hypothesis, primary_metric, secondary_metrics, measurement_policy_version, measurement_policy_snapshot, baseline_window, baseline_snapshot, baseline_status, started_at, absolute_terminal_at, status, terminal_outcome, outcome_reason, attribution_confidence, confounders, results_deep_link, created_at, updated_at from site_fix_measurements
where project_id = $1
  and site_fix_id = $2
  and measurement_generation = $3
`

type GetSiteFixMeasurementGenerationParams struct {
	ProjectID             uuid.UUID `json:"project_id"`
	SiteFixID             uuid.UUID `json:"site_fix_id"`
	MeasurementGeneration int32     `json:"measurement_generation"`
}

func (q *Queries) GetSiteFixMeasurementGeneration(ctx context.Context, arg GetSiteFixMeasurementGenerationParams) (SiteFixMeasurement, error) {
	row := q.db.QueryRow(ctx, getSiteFixMeasurementGeneration, arg.ProjectID, arg.SiteFixID, arg.MeasurementGeneration)
	var i SiteFixMeasurement
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SiteFixID,
		&i.MeasurementGeneration,
		&i.CreationIdempotencyKey,
		&i.TargetUrl,
		&i.NormalizedTargetUrl,
		&i.TargetQuery,
		&i.TargetIdentity,
		&i.FixType,
		&i.ImpactMode,
		&i.ClassifierVersion,
		&i.DecisionOrigin,
		&i.DecisionConfidence,
		&i.ProspectiveObservation,
		&i.GrowthHypothesis,
		&i.PrimaryMetric,
		&i.SecondaryMetrics,
		&i.MeasurementPolicyVersion,
		&i.MeasurementPolicySnapshot,
		&i.BaselineWindow,
		&i.BaselineSnapshot,
		&i.BaselineStatus,
		&i.StartedAt,
		&i.AbsoluteTerminalAt,
		&i.Status,
		&i.TerminalOutcome,
		&i.OutcomeReason,
		&i.AttributionConfidence,
		&i.Confounders,
		&i.ResultsDeepLink,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFailedTerminalSiteFixMeasurementHandoffs = `-- name: ListFailedTerminalSiteFixMeasurementHandoffs :many
select id, project_id, site_fix_id, measurement_generation, event_type, idempotency_key, status, attempt_count, max_attempts, next_attempt_at, lock_token, locked_until, last_error_classification, last_error, completed_at, created_at, updated_at, occurred_at from site_fix_measurement_handoff_outbox
where status='failed_terminal'
order by updated_at, id
limit least(greatest($1::int,1),100)
`

func (q *Queries) ListFailedTerminalSiteFixMeasurementHandoffs(ctx context.Context, limitRows int32) ([]SiteFixMeasurementHandoffOutbox, error) {
	rows, err := q.db.Query(ctx, listFailedTerminalSiteFixMeasurementHandoffs, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteFixMeasurementHandoffOutbox
	for rows.Next() {
		var i SiteFixMeasurementHandoffOutbox
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SiteFixID,
			&i.MeasurementGeneration,
			&i.EventType,
			&i.IdempotencyKey,
			&i.Status,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.LockToken,
			&i.LockedUntil,
			&i.LastErrorClassification,
			&i.LastError,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteFixMeasurementCheckpoints = `-- name: ListSiteFixMeasurementCheckpoints :many
select id, project_id, measurement_id, checkpoint_key, checkpoint_role, scheduled_at, window_start, window_end, attempt_number, required_data_sources, data_availability, minimum_sample, seo_metrics, ga4_metrics, geo_metrics, execution_metrics, guardrail_results, outcome_label, outcome_reason, attribution_confidence, computed_at, failure_reason, retry_classification, created_at, evaluation_attempt_count, next_attempt_at from site_fix_measurement_checkpoints
where project_id = $1 and measurement_id = $2
order by scheduled_at, checkpoint_key, attempt_number
`

type ListSiteFixMeasurementCheckpointsParams struct {
	ProjectID     uuid.UUID `json:"project_id"`
	MeasurementID uuid.UUID `json:"measurement_id"`
}

func (q *Queries) ListSiteFixMeasurementCheckpoints(ctx context.Context, arg ListSiteFixMeasurementCheckpointsParams) ([]SiteFixMeasurementCheckpoint, error) {
	rows, err := q.db.Query(ctx, listSiteFixMeasurementCheckpoints, arg.ProjectID, arg.MeasurementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteFixMeasurementCheckpoint
	for rows.Next() {
		var i SiteFixMeasurementCheckpoint
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.MeasurementID,
			&i.CheckpointKey,
			&i.CheckpointRole,
			&i.ScheduledAt,
			&i.WindowStart,
			&i.WindowEnd,
			&i.AttemptNumber,
			&i.RequiredDataSources,
			&i.DataAvailability,
			&i.MinimumSample,
			&i.SeoMetrics,
			&i.Ga4Metrics,
			&i.GeoMetrics,
			&i.ExecutionMetrics,
			&i.GuardrailResults,
			&i.OutcomeLabel,
			&i.OutcomeReason,
			&i.AttributionConfidence,
			&i.ComputedAt,
			&i.FailureReason,
			&i.RetryClassification,
			&i.CreatedAt,
			&i.EvaluationAttemptCount,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteFixMeasurementsForResults = `-- name: ListSiteFixMeasurementsForResults :many
select measurement.id, measurement.project_id, measurement.site_fix_id, measurement.measurement_generation, measurement.creation_idempotency_key, measurement.target_url, measurement.normalized_target_url, measurement.target_query, measurement.target_identity, measurement.fix_type, measurement.impact_mode, measurement.classifier_version, measurement.decision_origin, measurement.decision_confidence, measurement.prospective_observation, measurement.growth_hypothesis, measurement.primary_metric, measurement.secondary_metrics, measurement.measurement_policy_version, measurement.measurement_policy_snapshot, measurement.baseline_window, measurement.baseline_snapshot, measurement.baseline_status, measurement.started_at, measurement.absolute_terminal_at, measurement.status, measurement.terminal_outcome, measurement.outcome_reason, measurement.attribution_confidence, measurement.confounders, measurement.results_deep_link, measurement.created_at, measurement.updated_at,
  'site_fix'::text as source_type,
  measurement.site_fix_id as source_id
from site_fix_measurements measurement
where measurement.project_id = $1
order by measurement.updated_at desc, measurement.id
limit least(greatest($3::int, 1), 100)
offset greatest($2::int, 0)
`

type ListSiteFixMeasurementsForResultsParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

type ListSiteFixMeasurementsForResultsRow struct {
	ID                        uuid.UUID          `json:"id"`
	ProjectID                 uuid.UUID          `json:"project_id"`
	SiteFixID                 uuid.UUID          `json:"site_fix_id"`
	MeasurementGeneration     int32              `json:"measurement_generation"`
	CreationIdempotencyKey    string             `json:"creation_idempotency_key"`
	TargetUrl                 string             `json:"target_url"`
	NormalizedTargetUrl       string             `json:"normalized_target_url"`
	TargetQuery               *string            `json:"target_query"`
	TargetIdentity            json.RawMessage    `json:"target_identity"`
	FixType                   string             `json:"fix_type"`
	ImpactMode                string             `json:"impact_mode"`
	ClassifierVersion         string             `json:"classifier_version"`
	DecisionOrigin            string             `json:"decision_origin"`
	DecisionConfidence        string             `json:"decision_confidence"`
	ProspectiveObservation    bool               `json:"prospective_observation"`
	GrowthHypothesis          string             `json:"growth_hypothesis"`
	PrimaryMetric             string             `json:"primary_metric"`
	SecondaryMetrics          json.RawMessage    `json:"secondary_metrics"`
	MeasurementPolicyVersion  string             `json:"measurement_policy_version"`
	MeasurementPolicySnapshot json.RawMessage    `json:"measurement_policy_snapshot"`
	BaselineWindow            json.RawMessage    `json:"baseline_window"`
	BaselineSnapshot          json.RawMessage    `json:"baseline_snapshot"`
	BaselineStatus            string             `json:"baseline_status"`
	StartedAt                 pgtype.Timestamptz `json:"started_at"`
	AbsoluteTerminalAt        pgtype.Timestamptz `json:"absolute_terminal_at"`
	Status                    string             `json:"status"`
	TerminalOutcome           *string            `json:"terminal_outcome"`
	OutcomeReason             *string            `json:"outcome_reason"`
	AttributionConfidence     string             `json:"attribution_confidence"`
	Confounders               json.RawMessage    `json:"confounders"`
	ResultsDeepLink           *string            `json:"results_deep_link"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	SourceType                string             `json:"source_type"`
	SourceID                  uuid.UUID          `json:"source_id"`
}

func (q *Queries) ListSiteFixMeasurementsForResults(ctx context.Context, arg ListSiteFixMeasurementsForResultsParams) ([]ListSiteFixMeasurementsForResultsRow, error) {
	rows, err := q.db.Query(ctx, listSiteFixMeasurementsForResults, arg.ProjectID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSiteFixMeasurementsForResultsRow
	for rows.Next() {
		var i ListSiteFixMeasurementsForResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SiteFixID,
			&i.MeasurementGeneration,
			&i.CreationIdempotencyKey,
			&i.TargetUrl,
			&i.NormalizedTargetUrl,
			&i.TargetQuery,
			&i.TargetIdentity,
			&i.FixType,
			&i.ImpactMode,
			&i.ClassifierVersion,
			&i.DecisionOrigin,
			&i.DecisionConfidence,
			&i.ProspectiveObservation,
			&i.GrowthHypothesis,
			&i.PrimaryMetric,
			&i.SecondaryMetrics,
			&i.MeasurementPolicyVersion,
			&i.MeasurementPolicySnapshot,
			&i.BaselineWindow,
			&i.BaselineSnapshot,
			&i.BaselineStatus,
			&i.StartedAt,
			&i.AbsoluteTerminalAt,
			&i.Status,
			&i.TerminalOutcome,
			&i.OutcomeReason,
			&i.AttributionConfidence,
			&i.Confounders,
			&i.ResultsDeepLink,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceType,
			&i.SourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedRequiredSiteFixesMissingMeasurement = `-- name: ListVerifiedRequiredSiteFixesMissingMeasurement :many
select fix.id, fix.project_id, fix.doctor_finding_id, fix.candidate_id, fix.work_signature_id, fix.supersedes_site_fix_id, fix.status, fix.finding_kind, fix.target_urls, fix.evidence_snapshot, fix.proposed_fix, fix.acceptance_tests, fix.verification_snapshot, fix.failure_reason, fix.retry_count, fix.max_retries, fix.legacy_opportunity_id, fix.legacy_content_action_id, fix.migration_batch_id, fix.approved_at, fix.applied_at, fix.deployed_at, fix.verified_at, fix.created_at, fix.updated_at, fix.doctor_link_dismissed_at, fix.doctor_link_dismissed_by, fix.fix_type, fix.impact_mode, fix.measurement_policy, fix.classifier_version, fix.decision_origin, fix.decision_confidence, fix.growth_hypothesis, fix.primary_metric, fix.secondary_metrics, fix.measurement_policy_version, fix.measurement_policy_snapshot, fix.measurement_plan_snapshot
from site_fixes fix
where fix.status = 'verified'
  and fix.measurement_policy = 'measurement_required'
  and not exists (
    select 1 from site_fix_measurements measurement
    where measurement.project_id = fix.project_id
      and measurement.site_fix_id = fix.id
      and measurement.status <> 'terminal'
  )
order by fix.updated_at, fix.id
limit least(greatest($1::int, 1), 100)
`

func (q *Queries) ListVerifiedRequiredSiteFixesMissingMeasurement(ctx context.Context, limitRows int32) ([]SiteFix, error) {
	rows, err := q.db.Query(ctx, listVerifiedRequiredSiteFixesMissingMeasurement, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteFix
	for rows.Next() {
		var i SiteFix
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DoctorFindingID,
			&i.CandidateID,
			&i.WorkSignatureID,
			&i.SupersedesSiteFixID,
			&i.Status,
			&i.FindingKind,
			&i.TargetUrls,
			&i.EvidenceSnapshot,
			&i.ProposedFix,
			&i.AcceptanceTests,
			&i.VerificationSnapshot,
			&i.FailureReason,
			&i.RetryCount,
			&i.MaxRetries,
			&i.LegacyOpportunityID,
			&i.LegacyContentActionID,
			&i.MigrationBatchID,
			&i.ApprovedAt,
			&i.AppliedAt,
			&i.DeployedAt,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DoctorLinkDismissedAt,
			&i.DoctorLinkDismissedBy,
			&i.FixType,
			&i.ImpactMode,
			&i.MeasurementPolicy,
			&i.ClassifierVersion,
			&i.DecisionOrigin,
			&i.DecisionConfidence,
			&i.GrowthHypothesis,
			&i.PrimaryMetric,
			&i.SecondaryMetrics,
			&i.MeasurementPolicyVersion,
			&i.MeasurementPolicySnapshot,
			&i.MeasurementPlanSnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileVerifiedSiteFixMeasurementHandoffs = `-- name: ReconcileVerifiedSiteFixMeasurementHandoffs :many
with candidates as (
  select fix.project_id, fix.id as site_fix_id, measurement.measurement_generation,
         coalesce(fix.verified_at, measurement.created_at) as occurred_at
  from site_fixes fix
  join site_fix_measurements measurement
    on measurement.project_id = fix.project_id
   and measurement.site_fix_id = fix.id
   and measurement.status <> 'terminal'
  where fix.status = 'verified'
    and not exists (
      select 1 from site_fix_measurement_handoff_outbox existing
      where existing.project_id = fix.project_id
        and existing.site_fix_id = fix.id
        and existing.measurement_generation = measurement.measurement_generation
    )
  order by fix.project_id, fix.id
  limit least(greatest($2::int, 1), 100)
)
insert into site_fix_measurement_handoff_outbox (
  id, project_id, site_fix_id, measurement_generation, idempotency_key,
  max_attempts, next_attempt_at, occurred_at
)
select gen_random_uuid(), candidate.project_id, candidate.site_fix_id,
       candidate.measurement_generation,
       'reconcile:' || candidate.site_fix_id::text || ':' || candidate.measurement_generation::text,
       8, $1, candidate.occurred_at
from candidates candidate
on conflict (project_id, site_fix_id, measurement_generation) do nothing
returning id, project_id, site_fix_id, measurement_generation, event_type, idempotency_key, status, attempt_count, max_attempts, next_attempt_at, lock_token, locked_until, last_error_classification, last_error, completed_at, created_at, updated_at, occurred_at
`

type ReconcileVerifiedSiteFixMeasurementHandoffsParams struct {
	NowAt     pgtype.Timestamptz `json:"now_at"`
	LimitRows int32              `json:"limit_rows"`
}

func (q *Queries) ReconcileVerifiedSiteFixMeasurementHandoffs(ctx context.Context, arg ReconcileVerifiedSiteFixMeasurementHandoffsParams) ([]SiteFixMeasurementHandoffOutbox, error) {
	rows, err := q.db.Query(ctx, reconcileVerifiedSiteFixMeasurementHandoffs, arg.NowAt, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteFixMeasurementHandoffOutbox
	for rows.Next() {
		var i SiteFixMeasurementHandoffOutbox
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SiteFixID,
			&i.MeasurementGeneration,
			&i.EventType,
			&i.IdempotencyKey,
			&i.Status,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.LockToken,
			&i.LockedUntil,
			&i.LastErrorClassification,
			&i.LastError,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retrySiteFixMeasurementHandoff = `-- name: RetrySiteFixMeasurementHandoff :one
update site_fix_measurement_handoff_outbox
set status = case when attempt_count >= max_attempts then 'failed_terminal' else 'failed_retryable' end,
    lock_token = null,
    locked_until = null,
    next_attempt_at = $1,
    last_error_classification = $2,
    last_error = $3,
    updated_at = now()
where id = $4
  and project_id = $5
  and status = 'processing'
  and lock_token = $6
returning id, project_id, site_fix_id, measurement_generation, event_type, idempotency_key, status, attempt_count, max_attempts, next_attempt_at, lock_token, locked_until, last_error_classification, last_error, completed_at, created_at, updated_at, occurred_at
`

type RetrySiteFixMeasurementHandoffParams struct {
	NextAttemptAt           pgtype.Timestamptz `json:"next_attempt_at"`
	LastErrorClassification *string            `json:"last_error_classification"`
	LastError               *string            `json:"last_error"`
	ID                      uuid.UUID          `json:"id"`
	ProjectID               uuid.UUID          `json:"project_id"`
	LockToken               pgtype.UUID        `json:"lock_token"`
}

func (q *Queries) RetrySiteFixMeasurementHandoff(ctx context.Context, arg RetrySiteFixMeasurementHandoffParams) (SiteFixMeasurementHandoffOutbox, error) {
	row := q.db.QueryRow(ctx, retrySiteFixMeasurementHandoff,
		arg.NextAttemptAt,
		arg.LastErrorClassification,
		arg.LastError,
		arg.ID,
		arg.ProjectID,
		arg.LockToken,
	)
	var i SiteFixMeasurementHandoffOutbox
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SiteFixID,
		&i.MeasurementGeneration,
		&i.EventType,
		&i.IdempotencyKey,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LockToken,
		&i.LockedUntil,
		&i.LastErrorClassification,
		&i.LastError,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OccurredAt,
	)
	return i, err
}

const terminalizeExpiredSiteFixMeasurementHandoffs = `-- name: TerminalizeExpiredSiteFixMeasurementHandoffs :many
update site_fix_measurement_handoff_outbox
set status = 'failed_terminal',
    lock_token = null,
    locked_until = null,
    last_error_classification = 'lease_expired_after_attempt_limit',
    last_error = 'processing lease expired after the finite handoff attempt limit',
    updated_at = now()
where status = 'processing'
  and locked_until <= $1
  and attempt_count >= max_attempts
returning id, project_id, site_fix_id, measurement_generation, event_type, idempotency_key, status, attempt_count, max_attempts, next_attempt_at, lock_token, locked_until, last_error_classification, last_error, completed_at, created_at, updated_at, occurred_at
`

func (q *Queries) TerminalizeExpiredSiteFixMeasurementHandoffs(ctx context.Context, nowAt pgtype.Timestamptz) ([]SiteFixMeasurementHandoffOutbox, error) {
	rows, err := q.db.Query(ctx, terminalizeExpiredSiteFixMeasurementHandoffs, nowAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteFixMeasurementHandoffOutbox
	for rows.Next() {
		var i SiteFixMeasurementHandoffOutbox
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SiteFixID,
			&i.MeasurementGeneration,
			&i.EventType,
			&i.IdempotencyKey,
			&i.Status,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.LockToken,
			&i.LockedUntil,
			&i.LastErrorClassification,
			&i.LastError,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const terminalizeSiteFixMeasurement = `-- name: TerminalizeSiteFixMeasurement :one
update site_fix_measurements
set status = 'terminal',
    terminal_outcome = $1,
    outcome_reason = $2,
    attribution_confidence = $3,
    confounders = $4,
    updated_at = now()
where project_id = $5
  and id = $6
  and status <> 'terminal'
returning id, project_id, site_fix_id, measurement_generation, creation_idempotency_key, target_url, normalized_target_url, target_query, target_identity, fix_type, impact_mode, classifier_version, decision_origin, decision_confidence, prospective_observation, growth_hypothesis, primary_metric, secondary_metrics, measurement_policy_version, measurement_policy_snapshot, baseline_window, baseline_snapshot, baseline_status, started_at, absolute_terminal_at, status, terminal_outcome, outcome_reason, attribution_confidence, confounders, results_deep_link, created_at, updated_at
`

type TerminalizeSiteFixMeasurementParams struct {
	TerminalOutcome       *string         `json:"terminal_outcome"`
	OutcomeReason         *string         `json:"outcome_reason"`
	AttributionConfidence string          `json:"attribution_confidence"`
	Confounders           json.RawMessage `json:"confounders"`
	ProjectID             uuid.UUID       `json:"project_id"`
	ID                    uuid.UUID       `json:"id"`
}

func (q *Queries) TerminalizeSiteFixMeasurement(ctx context.Context, arg TerminalizeSiteFixMeasurementParams) (SiteFixMeasurement, error) {
	row := q.db.QueryRow(ctx, terminalizeSiteFixMeasurement,
		arg.TerminalOutcome,
		arg.OutcomeReason,
		arg.AttributionConfidence,
		arg.Confounders,
		arg.ProjectID,
		arg.ID,
	)
	var i SiteFixMeasurement
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SiteFixID,
		&i.MeasurementGeneration,
		&i.CreationIdempotencyKey,
		&i.TargetUrl,
		&i.NormalizedTargetUrl,
		&i.TargetQuery,
		&i.TargetIdentity,
		&i.FixType,
		&i.ImpactMode,
		&i.ClassifierVersion,
		&i.DecisionOrigin,
		&i.DecisionConfidence,
		&i.ProspectiveObservation,
		&i.GrowthHypothesis,
		&i.PrimaryMetric,
		&i.SecondaryMetrics,
		&i.MeasurementPolicyVersion,
		&i.MeasurementPolicySnapshot,
		&i.BaselineWindow,
		&i.BaselineSnapshot,
		&i.BaselineStatus,
		&i.StartedAt,
		&i.AbsoluteTerminalAt,
		&i.Status,
		&i.TerminalOutcome,
		&i.OutcomeReason,
		&i.AttributionConfidence,
		&i.Confounders,
		&i.ResultsDeepLink,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSiteFixMeasurementBaseline = `-- name: UpdateSiteFixMeasurementBaseline :one
update site_fix_measurements
set baseline_snapshot = $1,
    baseline_status = $2,
    status = $3,
    updated_at = now()
where project_id = $4
  and id = $5
  and baseline_status in ('planned','collecting')
returning id, project_id, site_fix_id, measurement_generation, creation_idempotency_key, target_url, normalized_target_url, target_query, target_identity, fix_type, impact_mode, classifier_version, decision_origin, decision_confidence, prospective_observation, growth_hypothesis, primary_metric, secondary_metrics, measurement_policy_version, measurement_policy_snapshot, baseline_window, baseline_snapshot, baseline_status, started_at, absolute_terminal_at, status, terminal_outcome, outcome_reason, attribution_confidence, confounders, results_deep_link, created_at, updated_at
`

type UpdateSiteFixMeasurementBaselineParams struct {
	BaselineSnapshot json.RawMessage `json:"baseline_snapshot"`
	BaselineStatus   string          `json:"baseline_status"`
	Status           string          `json:"status"`
	ProjectID        uuid.UUID       `json:"project_id"`
	ID               uuid.UUID       `json:"id"`
}

func (q *Queries) UpdateSiteFixMeasurementBaseline(ctx context.Context, arg UpdateSiteFixMeasurementBaselineParams) (SiteFixMeasurement, error) {
	row := q.db.QueryRow(ctx, updateSiteFixMeasurementBaseline,
		arg.BaselineSnapshot,
		arg.BaselineStatus,
		arg.Status,
		arg.ProjectID,
		arg.ID,
	)
	var i SiteFixMeasurement
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SiteFixID,
		&i.MeasurementGeneration,
		&i.CreationIdempotencyKey,
		&i.TargetUrl,
		&i.NormalizedTargetUrl,
		&i.TargetQuery,
		&i.TargetIdentity,
		&i.FixType,
		&i.ImpactMode,
		&i.ClassifierVersion,
		&i.DecisionOrigin,
		&i.DecisionConfidence,
		&i.ProspectiveObservation,
		&i.GrowthHypothesis,
		&i.PrimaryMetric,
		&i.SecondaryMetrics,
		&i.MeasurementPolicyVersion,
		&i.MeasurementPolicySnapshot,
		&i.BaselineWindow,
		&i.BaselineSnapshot,
		&i.BaselineStatus,
		&i.StartedAt,
		&i.AbsoluteTerminalAt,
		&i.Status,
		&i.TerminalOutcome,
		&i.OutcomeReason,
		&i.AttributionConfidence,
		&i.Confounders,
		&i.ResultsDeepLink,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
