// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: topics.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveTopicForProject = `-- name: ArchiveTopicForProject :one
update topics set status = 'archived', scheduled_at = null
where id = $1 and project_id = $2
returning id, project_id, channel, title, target_keyword, target_prompt, angle, format, priority, internal_links, status, scheduled_at, created_at, source_content_action_id, recovery_attempts, asset_type, target_plan_id
`

type ArchiveTopicForProjectParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) ArchiveTopicForProject(ctx context.Context, arg ArchiveTopicForProjectParams) (Topic, error) {
	row := q.db.QueryRow(ctx, archiveTopicForProject, arg.ID, arg.ProjectID)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Channel,
		&i.Title,
		&i.TargetKeyword,
		&i.TargetPrompt,
		&i.Angle,
		&i.Format,
		&i.Priority,
		&i.InternalLinks,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.SourceContentActionID,
		&i.RecoveryAttempts,
		&i.AssetType,
		&i.TargetPlanID,
	)
	return i, err
}

const countNonRejectedArticlesForTopic = `-- name: CountNonRejectedArticlesForTopic :one
select count(*) from articles
where topic_id = $1 and status <> 'rejected'
`

func (q *Queries) CountNonRejectedArticlesForTopic(ctx context.Context, topicID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNonRejectedArticlesForTopic, topicID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTopic = `-- name: CreateTopic :one
insert into topics
  (project_id, channel, title, target_keyword, target_prompt, angle, format, priority, internal_links, status, scheduled_at, source_content_action_id)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
returning id, project_id, channel, title, target_keyword, target_prompt, angle, format, priority, internal_links, status, scheduled_at, created_at, source_content_action_id, recovery_attempts, asset_type, target_plan_id
`

type CreateTopicParams struct {
	ProjectID             uuid.UUID          `json:"project_id"`
	Channel               string             `json:"channel"`
	Title                 string             `json:"title"`
	TargetKeyword         *string            `json:"target_keyword"`
	TargetPrompt          *string            `json:"target_prompt"`
	Angle                 *string            `json:"angle"`
	Format                *string            `json:"format"`
	Priority              int32              `json:"priority"`
	InternalLinks         json.RawMessage    `json:"internal_links"`
	Status                string             `json:"status"`
	ScheduledAt           pgtype.Timestamptz `json:"scheduled_at"`
	SourceContentActionID pgtype.UUID        `json:"source_content_action_id"`
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, createTopic,
		arg.ProjectID,
		arg.Channel,
		arg.Title,
		arg.TargetKeyword,
		arg.TargetPrompt,
		arg.Angle,
		arg.Format,
		arg.Priority,
		arg.InternalLinks,
		arg.Status,
		arg.ScheduledAt,
		arg.SourceContentActionID,
	)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Channel,
		&i.Title,
		&i.TargetKeyword,
		&i.TargetPrompt,
		&i.Angle,
		&i.Format,
		&i.Priority,
		&i.InternalLinks,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.SourceContentActionID,
		&i.RecoveryAttempts,
		&i.AssetType,
		&i.TargetPlanID,
	)
	return i, err
}

const getTopic = `-- name: GetTopic :one
select id, project_id, channel, title, target_keyword, target_prompt, angle, format, priority, internal_links, status, scheduled_at, created_at, source_content_action_id, recovery_attempts, asset_type, target_plan_id from topics where id = $1
`

func (q *Queries) GetTopic(ctx context.Context, id uuid.UUID) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopic, id)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Channel,
		&i.Title,
		&i.TargetKeyword,
		&i.TargetPrompt,
		&i.Angle,
		&i.Format,
		&i.Priority,
		&i.InternalLinks,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.SourceContentActionID,
		&i.RecoveryAttempts,
		&i.AssetType,
		&i.TargetPlanID,
	)
	return i, err
}

const getTopicForProject = `-- name: GetTopicForProject :one
select id, project_id, channel, title, target_keyword, target_prompt, angle, format, priority, internal_links, status, scheduled_at, created_at, source_content_action_id, recovery_attempts, asset_type, target_plan_id from topics
where id = $1 and project_id = $2
`

type GetTopicForProjectParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) GetTopicForProject(ctx context.Context, arg GetTopicForProjectParams) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopicForProject, arg.ID, arg.ProjectID)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Channel,
		&i.Title,
		&i.TargetKeyword,
		&i.TargetPrompt,
		&i.Angle,
		&i.Format,
		&i.Priority,
		&i.InternalLinks,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.SourceContentActionID,
		&i.RecoveryAttempts,
		&i.AssetType,
		&i.TargetPlanID,
	)
	return i, err
}

const incrementTopicRecoveryAttempt = `-- name: IncrementTopicRecoveryAttempt :one
update topics set recovery_attempts = recovery_attempts + 1
where id = $1 and project_id = $2
returning id, project_id, channel, title, target_keyword, target_prompt, angle, format, priority, internal_links, status, scheduled_at, created_at, source_content_action_id, recovery_attempts, asset_type, target_plan_id
`

type IncrementTopicRecoveryAttemptParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) IncrementTopicRecoveryAttempt(ctx context.Context, arg IncrementTopicRecoveryAttemptParams) (Topic, error) {
	row := q.db.QueryRow(ctx, incrementTopicRecoveryAttempt, arg.ID, arg.ProjectID)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Channel,
		&i.Title,
		&i.TargetKeyword,
		&i.TargetPrompt,
		&i.Angle,
		&i.Format,
		&i.Priority,
		&i.InternalLinks,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.SourceContentActionID,
		&i.RecoveryAttempts,
		&i.AssetType,
		&i.TargetPlanID,
	)
	return i, err
}

const listArticlesByTopicForProject = `-- name: ListArticlesByTopicForProject :many
select id, project_id, topic_id, kind, platform, content_md, seo_meta, geo_score, seo_score, qa_issues, qa_blocking, canonical_url, status, scheduled_at, reviewed_by, reviewed_at, published_at, publish_result, last_publish_error, publish_attempts, next_publish_retry_at, publish_phase, resolved_slug, publish_path, canonical_url_verified_at, last_publish_run_id, created_at, content_hash, repair_attempts, last_repair_at, repair_status, repair_failure_reason, requires_human_decision, human_decision_options, qa_feedback, recovery_attempts, publication_mode, source_url, external_url, verification_status, external_surface_id, platform_contract_id, platform_contract_version, target_context_id, output_type, platform_metadata, contract_validation from articles
where topic_id = $1 and project_id = $2
order by kind, platform
`

type ListArticlesByTopicForProjectParams struct {
	TopicID   uuid.UUID `json:"topic_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) ListArticlesByTopicForProject(ctx context.Context, arg ListArticlesByTopicForProjectParams) ([]Article, error) {
	rows, err := q.db.Query(ctx, listArticlesByTopicForProject, arg.TopicID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TopicID,
			&i.Kind,
			&i.Platform,
			&i.ContentMd,
			&i.SeoMeta,
			&i.GeoScore,
			&i.SeoScore,
			&i.QaIssues,
			&i.QaBlocking,
			&i.CanonicalUrl,
			&i.Status,
			&i.ScheduledAt,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.PublishedAt,
			&i.PublishResult,
			&i.LastPublishError,
			&i.PublishAttempts,
			&i.NextPublishRetryAt,
			&i.PublishPhase,
			&i.ResolvedSlug,
			&i.PublishPath,
			&i.CanonicalUrlVerifiedAt,
			&i.LastPublishRunID,
			&i.CreatedAt,
			&i.ContentHash,
			&i.RepairAttempts,
			&i.LastRepairAt,
			&i.RepairStatus,
			&i.RepairFailureReason,
			&i.RequiresHumanDecision,
			&i.HumanDecisionOptions,
			&i.QaFeedback,
			&i.RecoveryAttempts,
			&i.PublicationMode,
			&i.SourceUrl,
			&i.ExternalUrl,
			&i.VerificationStatus,
			&i.ExternalSurfaceID,
			&i.PlatformContractID,
			&i.PlatformContractVersion,
			&i.TargetContextID,
			&i.OutputType,
			&i.PlatformMetadata,
			&i.ContractValidation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopics = `-- name: ListTopics :many
select id, project_id, channel, title, target_keyword, target_prompt, angle, format, priority, internal_links, status, scheduled_at, created_at, source_content_action_id, recovery_attempts, asset_type, target_plan_id from topics
where project_id = $1
order by priority asc, created_at desc
`

func (q *Queries) ListTopics(ctx context.Context, projectID uuid.UUID) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopics, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Channel,
			&i.Title,
			&i.TargetKeyword,
			&i.TargetPrompt,
			&i.Angle,
			&i.Format,
			&i.Priority,
			&i.InternalLinks,
			&i.Status,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.SourceContentActionID,
			&i.RecoveryAttempts,
			&i.AssetType,
			&i.TargetPlanID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectDueScheduledTopics = `-- name: SelectDueScheduledTopics :many
select id, project_id, channel, title, target_keyword, target_prompt, angle, format, priority, internal_links, status, scheduled_at, created_at, source_content_action_id, recovery_attempts, asset_type, target_plan_id from topics
where topics.project_id = $1
  and topics.status = 'scheduled'
  and topics.scheduled_at is not null
  and topics.scheduled_at <= now()
  and not exists (
    select 1 from product_writer_authority authority
    where authority.project_id = topics.project_id and authority.product = 'opportunities'
      and authority.write_fenced = true
  )
  and not exists (
    select 1 from content_actions action
    join growth_opportunity_work_aliases alias
      on alias.project_id = action.project_id and alias.legacy_opportunity_id = action.opportunity_id
    where action.project_id = topics.project_id and action.id = topics.source_content_action_id
      and alias.disposition in ('duplicate','doctor_merge')
  )
order by topics.scheduled_at asc
for update skip locked
`

// Scheduler: topics whose operator-set scheduled_at slot has arrived. Unlike
// SelectGenerationCandidates this is time-driven and ignores buffer/priority,
// since the operator explicitly scheduled the slot (§5.4). Locked to avoid
// concurrent double-generation.
func (q *Queries) SelectDueScheduledTopics(ctx context.Context, projectID uuid.UUID) ([]Topic, error) {
	rows, err := q.db.Query(ctx, selectDueScheduledTopics, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Channel,
			&i.Title,
			&i.TargetKeyword,
			&i.TargetPrompt,
			&i.Angle,
			&i.Format,
			&i.Priority,
			&i.InternalLinks,
			&i.Status,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.SourceContentActionID,
			&i.RecoveryAttempts,
			&i.AssetType,
			&i.TargetPlanID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectGenerationCandidates = `-- name: SelectGenerationCandidates :many
select id, project_id, channel, title, target_keyword, target_prompt, angle, format, priority, internal_links, status, scheduled_at, created_at, source_content_action_id, recovery_attempts, asset_type, target_plan_id from topics
where topics.project_id = $1
  and topics.status in ('backlog','scheduled')
  and not exists (
    select 1 from product_writer_authority authority
    where authority.project_id = topics.project_id and authority.product = 'opportunities'
      and authority.write_fenced = true
  )
  and not exists (
    select 1 from content_actions action
    join growth_opportunity_work_aliases alias
      on alias.project_id = action.project_id and alias.legacy_opportunity_id = action.opportunity_id
    where action.project_id = topics.project_id and action.id = topics.source_content_action_id
      and alias.disposition in ('duplicate','doctor_merge')
  )
order by
  case when source_content_action_id is not null then 0 else 1 end,
  topics.priority asc,
  topics.created_at asc
limit $2
for update skip locked
`

type SelectGenerationCandidatesParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
}

// Scheduler candidate selection: backlog/scheduled topics with a slot inside the
// buffer window, locked to avoid concurrent double-generation (§5.4).
func (q *Queries) SelectGenerationCandidates(ctx context.Context, arg SelectGenerationCandidatesParams) ([]Topic, error) {
	rows, err := q.db.Query(ctx, selectGenerationCandidates, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Channel,
			&i.Title,
			&i.TargetKeyword,
			&i.TargetPrompt,
			&i.Angle,
			&i.Format,
			&i.Priority,
			&i.InternalLinks,
			&i.Status,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.SourceContentActionID,
			&i.RecoveryAttempts,
			&i.AssetType,
			&i.TargetPlanID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTopicScheduledAt = `-- name: SetTopicScheduledAt :one
update topics set scheduled_at = $2 where id = $1
returning id, project_id, channel, title, target_keyword, target_prompt, angle, format, priority, internal_links, status, scheduled_at, created_at, source_content_action_id, recovery_attempts, asset_type, target_plan_id
`

type SetTopicScheduledAtParams struct {
	ID          uuid.UUID          `json:"id"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
}

func (q *Queries) SetTopicScheduledAt(ctx context.Context, arg SetTopicScheduledAtParams) (Topic, error) {
	row := q.db.QueryRow(ctx, setTopicScheduledAt, arg.ID, arg.ScheduledAt)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Channel,
		&i.Title,
		&i.TargetKeyword,
		&i.TargetPrompt,
		&i.Angle,
		&i.Format,
		&i.Priority,
		&i.InternalLinks,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.SourceContentActionID,
		&i.RecoveryAttempts,
		&i.AssetType,
		&i.TargetPlanID,
	)
	return i, err
}

const setTopicScheduledAtForProject = `-- name: SetTopicScheduledAtForProject :one
update topics set
  scheduled_at = $3,
  status = case when $3::timestamptz is null then 'backlog' else 'scheduled' end
where id = $1 and project_id = $2
returning id, project_id, channel, title, target_keyword, target_prompt, angle, format, priority, internal_links, status, scheduled_at, created_at, source_content_action_id, recovery_attempts, asset_type, target_plan_id
`

type SetTopicScheduledAtForProjectParams struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
}

func (q *Queries) SetTopicScheduledAtForProject(ctx context.Context, arg SetTopicScheduledAtForProjectParams) (Topic, error) {
	row := q.db.QueryRow(ctx, setTopicScheduledAtForProject, arg.ID, arg.ProjectID, arg.ScheduledAt)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Channel,
		&i.Title,
		&i.TargetKeyword,
		&i.TargetPrompt,
		&i.Angle,
		&i.Format,
		&i.Priority,
		&i.InternalLinks,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.SourceContentActionID,
		&i.RecoveryAttempts,
		&i.AssetType,
		&i.TargetPlanID,
	)
	return i, err
}

const startTopicGenerationForProject = `-- name: StartTopicGenerationForProject :one
update topics set status = 'generating'
where topics.id = $1 and topics.project_id = $2 and topics.status in ('backlog','scheduled')
  and not exists (
    select 1 from product_writer_authority authority
    where authority.project_id = topics.project_id and authority.product = 'opportunities'
      and authority.write_fenced = true
  )
  and not exists (
    select 1 from content_actions action
    join growth_opportunity_work_aliases alias
      on alias.project_id = action.project_id and alias.legacy_opportunity_id = action.opportunity_id
    where action.project_id = topics.project_id and action.id = topics.source_content_action_id
      and alias.disposition in ('duplicate','doctor_merge')
  )
returning id, project_id, channel, title, target_keyword, target_prompt, angle, format, priority, internal_links, status, scheduled_at, created_at, source_content_action_id, recovery_attempts, asset_type, target_plan_id
`

type StartTopicGenerationForProjectParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) StartTopicGenerationForProject(ctx context.Context, arg StartTopicGenerationForProjectParams) (Topic, error) {
	row := q.db.QueryRow(ctx, startTopicGenerationForProject, arg.ID, arg.ProjectID)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Channel,
		&i.Title,
		&i.TargetKeyword,
		&i.TargetPrompt,
		&i.Angle,
		&i.Format,
		&i.Priority,
		&i.InternalLinks,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.SourceContentActionID,
		&i.RecoveryAttempts,
		&i.AssetType,
		&i.TargetPlanID,
	)
	return i, err
}

const updateTopic = `-- name: UpdateTopic :one
update topics set
  channel = $3,
  title = $4,
  target_keyword = $5,
  target_prompt = $6,
  angle = $7,
  format = $8,
  priority = $9,
  internal_links = $10,
  status = $11,
  scheduled_at = $12,
  source_content_action_id = $13
where id = $1 and project_id = $2
returning id, project_id, channel, title, target_keyword, target_prompt, angle, format, priority, internal_links, status, scheduled_at, created_at, source_content_action_id, recovery_attempts, asset_type, target_plan_id
`

type UpdateTopicParams struct {
	ID                    uuid.UUID          `json:"id"`
	ProjectID             uuid.UUID          `json:"project_id"`
	Channel               string             `json:"channel"`
	Title                 string             `json:"title"`
	TargetKeyword         *string            `json:"target_keyword"`
	TargetPrompt          *string            `json:"target_prompt"`
	Angle                 *string            `json:"angle"`
	Format                *string            `json:"format"`
	Priority              int32              `json:"priority"`
	InternalLinks         json.RawMessage    `json:"internal_links"`
	Status                string             `json:"status"`
	ScheduledAt           pgtype.Timestamptz `json:"scheduled_at"`
	SourceContentActionID pgtype.UUID        `json:"source_content_action_id"`
}

func (q *Queries) UpdateTopic(ctx context.Context, arg UpdateTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, updateTopic,
		arg.ID,
		arg.ProjectID,
		arg.Channel,
		arg.Title,
		arg.TargetKeyword,
		arg.TargetPrompt,
		arg.Angle,
		arg.Format,
		arg.Priority,
		arg.InternalLinks,
		arg.Status,
		arg.ScheduledAt,
		arg.SourceContentActionID,
	)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Channel,
		&i.Title,
		&i.TargetKeyword,
		&i.TargetPrompt,
		&i.Angle,
		&i.Format,
		&i.Priority,
		&i.InternalLinks,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.SourceContentActionID,
		&i.RecoveryAttempts,
		&i.AssetType,
		&i.TargetPlanID,
	)
	return i, err
}

const updateTopicStatus = `-- name: UpdateTopicStatus :one
update topics set status = $2 where id = $1
returning id, project_id, channel, title, target_keyword, target_prompt, angle, format, priority, internal_links, status, scheduled_at, created_at, source_content_action_id, recovery_attempts, asset_type, target_plan_id
`

type UpdateTopicStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateTopicStatus(ctx context.Context, arg UpdateTopicStatusParams) (Topic, error) {
	row := q.db.QueryRow(ctx, updateTopicStatus, arg.ID, arg.Status)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Channel,
		&i.Title,
		&i.TargetKeyword,
		&i.TargetPrompt,
		&i.Angle,
		&i.Format,
		&i.Priority,
		&i.InternalLinks,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.SourceContentActionID,
		&i.RecoveryAttempts,
		&i.AssetType,
		&i.TargetPlanID,
	)
	return i, err
}

const updateTopicStatusForProject = `-- name: UpdateTopicStatusForProject :one
update topics set status = $3
where id = $1 and project_id = $2
returning id, project_id, channel, title, target_keyword, target_prompt, angle, format, priority, internal_links, status, scheduled_at, created_at, source_content_action_id, recovery_attempts, asset_type, target_plan_id
`

type UpdateTopicStatusForProjectParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	Status    string    `json:"status"`
}

func (q *Queries) UpdateTopicStatusForProject(ctx context.Context, arg UpdateTopicStatusForProjectParams) (Topic, error) {
	row := q.db.QueryRow(ctx, updateTopicStatusForProject, arg.ID, arg.ProjectID, arg.Status)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Channel,
		&i.Title,
		&i.TargetKeyword,
		&i.TargetPrompt,
		&i.Angle,
		&i.Format,
		&i.Priority,
		&i.InternalLinks,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.SourceContentActionID,
		&i.RecoveryAttempts,
		&i.AssetType,
		&i.TargetPlanID,
	)
	return i, err
}
