// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: topics.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countNonRejectedArticlesForTopic = `-- name: CountNonRejectedArticlesForTopic :one
select count(*) from articles
where topic_id = $1 and status <> 'rejected'
`

func (q *Queries) CountNonRejectedArticlesForTopic(ctx context.Context, topicID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNonRejectedArticlesForTopic, topicID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTopic = `-- name: CreateTopic :one
insert into topics
  (project_id, channel, title, target_keyword, target_prompt, angle, format, priority, internal_links, status, scheduled_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
returning id, project_id, channel, title, target_keyword, target_prompt, angle, format, priority, internal_links, status, scheduled_at, created_at
`

type CreateTopicParams struct {
	ProjectID     uuid.UUID          `json:"project_id"`
	Channel       string             `json:"channel"`
	Title         string             `json:"title"`
	TargetKeyword *string            `json:"target_keyword"`
	TargetPrompt  *string            `json:"target_prompt"`
	Angle         *string            `json:"angle"`
	Format        *string            `json:"format"`
	Priority      int32              `json:"priority"`
	InternalLinks json.RawMessage    `json:"internal_links"`
	Status        string             `json:"status"`
	ScheduledAt   pgtype.Timestamptz `json:"scheduled_at"`
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, createTopic,
		arg.ProjectID,
		arg.Channel,
		arg.Title,
		arg.TargetKeyword,
		arg.TargetPrompt,
		arg.Angle,
		arg.Format,
		arg.Priority,
		arg.InternalLinks,
		arg.Status,
		arg.ScheduledAt,
	)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Channel,
		&i.Title,
		&i.TargetKeyword,
		&i.TargetPrompt,
		&i.Angle,
		&i.Format,
		&i.Priority,
		&i.InternalLinks,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTopic = `-- name: GetTopic :one
select id, project_id, channel, title, target_keyword, target_prompt, angle, format, priority, internal_links, status, scheduled_at, created_at from topics where id = $1
`

func (q *Queries) GetTopic(ctx context.Context, id uuid.UUID) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopic, id)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Channel,
		&i.Title,
		&i.TargetKeyword,
		&i.TargetPrompt,
		&i.Angle,
		&i.Format,
		&i.Priority,
		&i.InternalLinks,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
	)
	return i, err
}

const listTopics = `-- name: ListTopics :many
select id, project_id, channel, title, target_keyword, target_prompt, angle, format, priority, internal_links, status, scheduled_at, created_at from topics
where project_id = $1
order by priority desc, created_at desc
`

func (q *Queries) ListTopics(ctx context.Context, projectID uuid.UUID) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopics, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Channel,
			&i.Title,
			&i.TargetKeyword,
			&i.TargetPrompt,
			&i.Angle,
			&i.Format,
			&i.Priority,
			&i.InternalLinks,
			&i.Status,
			&i.ScheduledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectGenerationCandidates = `-- name: SelectGenerationCandidates :many
select id, project_id, channel, title, target_keyword, target_prompt, angle, format, priority, internal_links, status, scheduled_at, created_at from topics
where project_id = $1
  and status in ('backlog','scheduled')
order by priority desc, created_at asc
limit $2
for update skip locked
`

type SelectGenerationCandidatesParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
}

// Scheduler candidate selection: backlog/scheduled topics with a slot inside the
// buffer window, locked to avoid concurrent double-generation (§5.4).
func (q *Queries) SelectGenerationCandidates(ctx context.Context, arg SelectGenerationCandidatesParams) ([]Topic, error) {
	rows, err := q.db.Query(ctx, selectGenerationCandidates, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Channel,
			&i.Title,
			&i.TargetKeyword,
			&i.TargetPrompt,
			&i.Angle,
			&i.Format,
			&i.Priority,
			&i.InternalLinks,
			&i.Status,
			&i.ScheduledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTopicScheduledAt = `-- name: SetTopicScheduledAt :one
update topics set scheduled_at = $2 where id = $1
returning id, project_id, channel, title, target_keyword, target_prompt, angle, format, priority, internal_links, status, scheduled_at, created_at
`

type SetTopicScheduledAtParams struct {
	ID          uuid.UUID          `json:"id"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
}

func (q *Queries) SetTopicScheduledAt(ctx context.Context, arg SetTopicScheduledAtParams) (Topic, error) {
	row := q.db.QueryRow(ctx, setTopicScheduledAt, arg.ID, arg.ScheduledAt)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Channel,
		&i.Title,
		&i.TargetKeyword,
		&i.TargetPrompt,
		&i.Angle,
		&i.Format,
		&i.Priority,
		&i.InternalLinks,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateTopicStatus = `-- name: UpdateTopicStatus :one
update topics set status = $2 where id = $1
returning id, project_id, channel, title, target_keyword, target_prompt, angle, format, priority, internal_links, status, scheduled_at, created_at
`

type UpdateTopicStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateTopicStatus(ctx context.Context, arg UpdateTopicStatusParams) (Topic, error) {
	row := q.db.QueryRow(ctx, updateTopicStatus, arg.ID, arg.Status)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Channel,
		&i.Title,
		&i.TargetKeyword,
		&i.TargetPrompt,
		&i.Angle,
		&i.Format,
		&i.Priority,
		&i.InternalLinks,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
	)
	return i, err
}
